### ISSUE TITLE
Tägliche Backups

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#10]

**Comment by copyandexecute** [comment]
polylmer hab dich einfach mal assigned weil du hetzner access hast

**Comment by TimLohrer** [comment]
@polylymer @copyandexecute was ist damit? Wie siehts hier aus?

**Comment by polylymer** [comment]
bin dran (an generellen Backups)

**Comment by polylymer** [comment]
@copyandexecute reicht der /home Ordner beider Server samt seinem Inhalt als Backup, oder noch andere spezielle Ordner/Wünsche?

**Comment by TimLohrer** [comment]
> Kannst du mir mal sagen was das alles beinhaltet? Am wichtigsten sind mir die mongodb datenbank einträge sind die da dabei?

Ich denke die sind auf jeden fall dabei, weil darum geht es hier ja hauptsächlich im issue

**Comment by polylymer** [comment]
naja soweit ich das verstehe, wird die docker db "festplatte" in `/home/.../containers/data/db` eingehängt/angelegt. Da müssten ja dann eig alle MongoDB Daten dabei sein? @Krxwallo gerne nochmal bestätigen ob das so stimmt!?

**Comment by polylymer** [comment]
perfekt danke dir 👍. Nach momentanen Stand enthalten wären:
- prod. Server:
 - alle Docker Container
- dev Server:
 - alle Docker Container (NRC und MC)
 - sonstige Minecraft Server (welche mit screen konfiguriert sind)
 - Cloudnet
-> und alles Weitere was in /home liegt

Wie siehts aus mit den Präferenzen bzgl. Uhrzeit? Hätte jetzt einfach mal Pi mal Daumen so ca. 03:00 Uhr Nachts vorgeschlagen.

**Comment by copyandexecute** [comment]
Hört sich 1A an

**Comment by polylymer** [comment]
obv. kommen Backups auf einen anderen Server, auf dem gleichen macht ja relativ wenig Sinn. Zwischen prod und dev Server Backups zu schieben macht auch eher wenig Sinn, weil die im gleichen Rechzentrum/Haus stehen. 
Hätte jetzt vorerst zum ausprobieren das mal auf meinen Server gebackupt. Der steht zwar auch bei Hetzner, aber 5 Häuser weiter wo das Risiko dass beiden was passiert eher gering ist. 
In der Zukunft kann man dann sich mal überlegen ob man die Hetzner Storage Box dafür benutzt, wobei die kostenlose die man beantragen kann auch nicht so viel Speicherplatz hat.

**Comment by TimLohrer** [comment]
> obv. kommen Backups auf einen anderen Server, auf dem gleichen macht ja relativ wenig Sinn. Zwischen prod und dev Server Backups zu schieben macht auch eher wenig Sinn, weil die im gleichen Rechzentrum/Haus stehen. Hätte jetzt vorerst zum ausprobieren das mal auf meinen Server gebackupt. Der steht zwar auch bei Hetzner, aber 5 Häuser weiter wo das Risiko dass beiden was passiert eher gering ist. In der Zukunft kann man dann sich mal überlegen ob man die Hetzner Storage Box dafür benutzt, wobei die kostenlose die man beantragen kann auch nicht so viel Speicherplatz hat.

Jo, wollte nur sicher gehen, man weiß ja nie :D
