### ISSUE TITLE
[Bug]: Armor Trim rendering Bug

### ISSUE THREAD

**Issue by MrMendel** [NoRiskClient/issues#100]
### What happened?

Manche Armor Trims rendern nur aus bestimmten Blickwinkeln andere komplett normal

https://github.com/NoRiskClient/issues/assets/155688870/73112185-d0b2-48b5-b7b6-bfd85dd553ee

 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by MrMendel** [comment]
Sry Falsches Vid

https://github.com/NoRiskClient/issues/assets/155688870/f1ed32c8-8ade-48c0-bdbc-74e063ee830f

**Comment by TimLohrer** [comment]
> Sry Falsches Vid
> Unbenanntes.Video.Mit.Clipchamp.erstellt.4.mp4

Passiert das auch ohne tp / shader?

**Comment by MrMendel** [comment]
Ja

**Comment by TimLohrer** [comment]
@copyandexecute

**Comment by SleepyPxnda** [comment]
Konnte ich nicht reproduzieren, daher close ich das mal
