### ISSUE TITLE
[Bug]: invis preview player on multiplayer servers + no skin textire in gui

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#101]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/55639047/b61c5c10-bcab-4cf6-8560-a55b2607a79e)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Fixed with https://github.com/NoRiskClient/issues/issues/36
