### ISSUE TITLE
JEI : 

### ISSUE THREAD

**Issue by Richart3855** [NoRiskClient/issues#102]
### What happened?

JEI wird im Launcher als mod angezeigt ist aber nicht mit der fabric version kompatibel
![image](https://github.com/NoRiskClient/issues/assets/157588291/6782ea78-4166-4e61-b889-82b73f9c28ae)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.3.8

**Comment by TimLohrer** [comment]
@TomJuri das sollte eig. Ez sein (muss in die fetch mods url als filter) wenn du bock hast kannst du dir das auch mal schnell angucken. Ansonsten sag mir einf. Mal was du vermutest, dann mache ich das

**Comment by TimLohrer** [comment]
> Sorry, habe gestern und heute leider keine Zeit. Morgen bin ich wieder frei...

Kein stress

**Comment by TomJuri** [comment]
Schwierig, die fabric api Version wird bei Modrinth [nicht als dependency angegeben](https://api.modrinth.com/v2/project/u6dRKJwZ/version/ohnVW62C), die Minecraft Version stimmt hier ja… Die einzige Lösung, die ich sehe, wäre keine Mods aus dem Modrinth beta Channel zu erlauben, oder die NRC fabric api Version immer aktuell zu halten.
