### ISSUE TITLE
[Bug]: NRC icon in tablist not showing after some time

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#103]
### What happened?

ja is blöd :/

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
BITTE MEHR INPUT ALS "ja ist blöd" LOOOOOL

**Comment by TimLohrer** [comment]
> BITTE MEHR INPUT ALS "ja ist blöd" LOOOOOL

Sry, dachte der name reicht... es geht um das verschwinden der icons in der Tabliste nach irgendeinem 3m cache oderso

**Comment by copyandexecute** [comment]
Ja aber danach wird es doch neu gefetched o.o

**Comment by copyandexecute** [comment]
Versuch mal bitte rauszufinden wie man es reproduzieren kann und dann fix ich es

**Comment by copyandexecute** [comment]
Any news o.o

**Comment by TimLohrer** [comment]
> Any news o.o

Ne haha 👀 aber schon länger nt mehr gesehen... aber bin auch grad wenig inga e

**Comment by copyandexecute** [comment]
bin dran männer

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/d783c688-d9a0-4d03-9218-f7933fedf030)
v1

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/4862dd98-f5c4-431d-8464-59a1fa7e3450)
v1

**Comment by copyandexecute** [comment]
@TimLohrer @Greeenman999

**Comment by copyandexecute** [comment]
@TimLohrer @Greeenman999 
Ich habe die legendäre "fetchOnlinePlayers" methode reworked, im backend kann man jetzt nur bis zu 80 spielern maximal fetchen für tabliste. 
Ich habe die Anbindung an das Friendsrepo GELÖSCHT, d.h. ihr müsstet euch selbst drumkümmern im friendsrepo, ob die freunde online sind oder nicht 👍

**Comment by copyandexecute** [comment]
die ist btw kavatch approved, also wenn einer muckt, ab zu kavatch
