### ISSUE TITLE
[SECURITY] use auth headers for tokens

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#104]
### Contact Details

aim_shock

### What happened?

Moove token to bearer header

### Where is this happening?

Client, Launcher, Backend

### What platform are you seeing the problem on?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
Kannst du noch Code Snippets providen damit ich es überall umcoden kann?

**Comment by copyandexecute** [comment]
Minigames und Client noch

**Comment by copyandexecute** [comment]
So sollte jetzt überall angepasst sein
