### ISSUE TITLE
[FEATURE-REQUEST]: Obfuscation

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#106]
### Your idea

Es wäre cool wenn wir die Jars obfuscaten, damit so sachen wie Flappy Bird von @PSJahn nicht geklaut werden

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Ich linke mal ein paar leute die dazu vlt was schreiben können
@PSJahn @Krxwallo @polylymer @enricoxD @Greeenman999

**Comment by Greeenman999** [comment]
@copyandexecute Wir haben das Issue schon #99

**Comment by PSJahn** [comment]
> @copyandexecute Wir haben das Issue schon #99
Einfache lösung: Altes closen und das behalten 

Aber ja, ich hätte hierzu zwar etwas zu sagen, jedoch sollten wir über obfuscation nicht in einem public thread reden.

**Comment by copyandexecute** [comment]
Erstmal keine obfuscation, code ist schon verschleiert genug durch unsere Kenntnisse
