### ISSUE TITLE
[Bug]: Color picker does not work

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#113]
### What happened?

![Image](https://github.com/NoRiskClient/issues/assets/55639047/57c13b65-5737-4ec5-b030-d423fbe8a466)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/8f91cbdd-77db-46fd-959e-9c3092571284)
Wurde geaddet, hab leider den Commit nicht gelinkt, vlt kann das einer nachholen

**Comment by copyandexecute** [comment]
https://github.com/NoRiskClient/noriskclient-ui/commit/e88b8fd2feb9b2d71909358b0eccbc0d325e146d
