### ISSUE TITLE
[FEATURE-REQUEST]: Interactive Capes (Cape Minigames)

### ISSUE THREAD

**Issue by PSJahn** [NoRiskClient/issues#119]
### Your idea

Tetris auf cape spielen, so dass es jeder sehen kann?

![image](https://github.com/NoRiskClient/issues/assets/66626848/1a2173db-83ea-4cbc-8828-085cb03ee57b)

Weitere Ideen währen z.B. Keystrokes oder CPS auf seinem Cape damit sie jeder sieht, find ich könnte wild sein

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@PSJahn wenn du das codest ^^

**Comment by SleepyPxnda** [comment]
@PSJahn ich denke mal das hier wird nixmehr oder ?

Ich mache zu, mach auf wenn du wieder dran bist
