### ISSUE TITLE
[Bug]: Scaling the Window messes up the module locations

### ISSUE THREAD

**Issue by PSJahn** [NoRiskClient/issues#120]
### What happened?

Opening the module editor, dragging the modules to a speicifc location then toggling windows/fullscreen mode as an example messes up the module locations big-time. This is very bad...

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by PSJahn** [comment]
> jo am geilsten wäre, wenn die modules so hinsnappen und dann relativ zum Rand oder zu anderen Modulen sind

Leichtester weg diese issue zu fixen währe einfach die postions in einem Vector2f von 0,0 bis 1,1 zu speichern, damit das ganze einfach relative ist. Aber keine Lust das zu implementen hihihi (bin auch nicht wirklich in der Lage da so viel zu ändern)

**Comment by SleepyPxnda** [comment]
Fixed
