### ISSUE TITLE
[Bug]: Autoupdater Windows 10

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#121]
### What happened?

![grafik](https://github.com/NoRiskClient/issues/assets/58366920/4066854e-b2d7-4137-9614-7bab4dbf749c)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by TimLohrer** [comment]
duplicate <https://github.com/NoRiskClient/issues/issues/85>
