### ISSUE TITLE
[FEATURE-REQUEST]: Option to update mods

### ISSUE THREAD

**Issue by Keramikblock** [NoRiskClient/issues#122]
### Your idea

So ein Button um eine Mod zu updaten.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
> Ich meine jetzt Modrinth Mods die man über den Mod installer im Launcher installiert. Zum Beispiel habe ich Xaero's World Map (Version: 1.37.6) installiert und die neuste Version ist 1.37.8. Dann wäre halt ein Update Button oder auto updater praktisch damit man nicht die Mods entfernen und neu hinzufügen muss.

Das muss der launcher selber machen, um sicher zu stellen, das die Version mit uns kompatibel ist ^^
