### ISSUE TITLE
[Bug]: NoRiskClient Asset Verification is not working at all.

### ISSUE THREAD

**Issue by TomJuri** [NoRiskClient/issues#125]
### What happened?

https://github.com/NoRiskClient/noriskclient-launcher/blob/9e47091f36ef0b3c4f02760aa2ebe8dcbf4d608c/src-tauri/src/minecraft/launcher.rs#L377 ist nie true, deswegen wird der ganze Schritt nicht ausgeführt. `path` ist immer ein Ordner und keine Datei.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

### Version (for launcher bugs)

9e47091f36ef0b3c4f02760aa2ebe8dcbf4d608c

**Comment by TimLohrer** [comment]
@TomJuri willst du das machen? (Das wäre ja direkt zusammen mit dem 120% launching Ding)

**Comment by TomJuri** [comment]
Jo, mache ich. Das 120% launching ding habe ich schon gefixt, falls du es noch nicht gesehen hast

**Comment by TomJuri** [comment]
Hmm merkwürdig, bei mir sind das die entries, nur Ordner
![image](https://github.com/NoRiskClient/issues/assets/99533320/30c92df5-d9c8-4359-923e-1e5bb6ed72d8)
![image](https://github.com/NoRiskClient/issues/assets/99533320/666d8665-aca9-4f60-a032-60e204253913)
"Doing something" wird nicht geprintet, auch wenn ich zwischen prod und dev branch switche.

**Comment by TomJuri** [comment]
Nevermind, habe es noch ein paar mal laufen lassen, ging auf ein mal ¯\_(ツ)_/¯
