### ISSUE TITLE
[Bug]: Pets while sneaking and flying

### ISSUE THREAD

**Issue by N1cohd1** [NoRiskClient/issues#129]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/125882726/70ba12dd-c713-42e1-91d2-977de8d18a99)
Wenn man fliegt und währenddessen sneakt werden Pets in der Schulte gerendert (bisher nur mit RedPanda getestet)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Ja irgendwann vielleicht... Aktuelle keine Zeit dafür

**Comment by TimLohrer** [comment]
@enricoxD bruh... was für getAbilities 💀

**Comment by enricoxD** [comment]
@TimLohrer minecraft 🤩😹😼🤯
