### ISSUE TITLE
[Bug]: Wrong Modname being displayed when searching in the "installed"-Tab

### ISSUE THREAD

**Issue by N1cohd1** [NoRiskClient/issues#130]
### What happened?

When you search for a Mod's name in the "Installed"-Tab in the launcher, the image of the search result is correct, but the name displayed is the one of the uppermost mod
![image](https://github.com/NoRiskClient/issues/assets/125882726/e7a0e4de-0a90-4301-9879-fa0b833078d7)
![image](https://github.com/NoRiskClient/issues/assets/125882726/06071998-0386-464d-8aa8-76275f95cd23)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.3.9

**Comment by N1cohd1** [comment]
just noticed that this is also happening when deleting a mod: When you delete a mod, the one below gets moved up, but the name stays the same
![image](https://github.com/NoRiskClient/issues/assets/125882726/69b52659-3654-4889-b729-d1fd8c91f30b)

**Comment by SleepyPxnda** [comment]
Fixed
