### ISSUE TITLE
[Bug]: 500 Internal Server Error beim Login mit Microsoft

### ISSUE THREAD

**Issue by MeIsGaming** [NoRiskClient/issues#132]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/105943733/f80f9b55-402e-4f79-a044-4d27ab360eb1)
Beschreibt den Bug recht gut, ich installiere, starte ganz normal den Client, drücke auf Login und bekomme nach dem Login im Browser den Error. Wollt nur wissen ob das normal ist haha, also ob das eh nur bei den Beta-Testern klappt.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.4.1

**Comment by TimLohrer** [comment]
Du bist nicht auf der whitelist. Es ist eine closed beta. Das soll so.

**Comment by TimLohrer** [comment]
@MeIsGaming willst du closed beta?

**Comment by MeIsGaming** [comment]
@TimLohrer sehr gern, wie gesagt helf gerne mit ^^ (alles weiter gerne auf Discord (me_is_gaming))
