### ISSUE TITLE
[Bug]: Game Absturz 

### ISSUE THREAD

**Issue by Fr3d33** [NoRiskClient/issues#138]
### What happened?

Hey ähm keine ahnung was hier passiert ist, ist einfach kurz nachdem ich den client gestartet habe und auf einen Server gejoint gecrasht: https://mclo.gs/SGG24Cs

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Danke fürs melden, den hatten wir auch schonmal. Auf welchen server bist du denn gejoined? Wir wissen noch nicht, warum das passiert.

**Comment by Fr3d33** [comment]
Ähm müsste mc.norisk.gg gewesen sein

**Comment by TimLohrer** [comment]
@enricoxD wenn fixed dann mach zu :)
