### ISSUE TITLE
[Bug]: Unable to log in

### ISSUE THREAD

**Issue by Ano-rak** [NoRiskClient/issues#139]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/76252585/df4a28a0-890d-4aa7-8f14-4ec1ae87e34a)
Jo habe mittlerweile auch nen Windows PC und als ich da versucht habe mich einzuloggen kam der error im Bild oben.
Logs wurden keine erstellt.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

v0.4.1

**Comment by TimLohrer** [comment]
warst nicht whitelisted ^^
