### ISSUE TITLE
[Bug]: Cosmetics - Linker und rechter Arm bei cosmetic Verbindung vertauscht? 

### ISSUE THREAD

**Issue by HitzlikeaBanana** [NoRiskClient/issues#143]
### What happened?

Ich habe einen neuen cube im Ordner für den rechten Arm erstellt, der Würfel hat den gleichen piviotpoint wie der normale Bone des rechten Arms. Auch die Position ist fast die gleiche. 

Wenn ich das Spiel lade, bewegt sich der cube, den ich erstellt habe, wie der linke Arm und nicht wie der rechte. (Idle animation geht nicht <- vom Körper weg und dann wieder normal, sie geht -> in den Körper und dann wieder normal), was genau die Animation für den linken Arm ist.

Wurden "links" und "rechts" durcheinander gebracht, weil man das Modell von hinten und nicht von vorne betrachtet hat (wie man es eigentlich sollte =)?

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SleepyPxnda** [comment]
I guess, das ist gefixed
