### ISSUE TITLE
[Bug]: Armorstatus Itemdamage not showing correctly 

### ISSUE THREAD

**Issue by DoctorDepp** [NoRiskClient/issues#144]
### What happened?

die prozentzahl beim armorstatus zeigt nicht richtig die durability an. siehe screenshot (100% selbst wenn schon recht viel dura weg ist)

![2024-03-24_15 56 33](https://github.com/NoRiskClient/issues/assets/155568114/3e72bd1a-e224-4cc0-9ac6-968613206e68)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/21df2848-8d68-499b-839f-1cd5b5eaae16)
Danke fürs Reporten sollte mit dem nächsten Update gefixed sein 👍
