### ISSUE TITLE
[FEATURE-REQUEST]: Effiziente Debug Logs

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#145]
Wie der Titel sagt, aussagekräftige Debuglogs damit wir später bugs besser finden.

@TimLohrer macht das überhaupt Sinn das in allen Projekten anzupassen ?

**Comment by TimLohrer** [comment]
Das hier nehmen wir um vor release mal alle logs auf zu räumen, dass wir bugs später schneller und effizienter finden und beheben können.
