### ISSUE TITLE
[Bug]: clock not updating time

### ISSUE THREAD

**Issue by DoctorDepp** [NoRiskClient/issues#146]
### What happened?

clock zeigt nur die exakte zeit, wo sich mc geöffnet hat und hört dann auf sich zu updaten. wenn man zum beispiel den client startet und sich mc exakt um 14:25 öffnet, zeigt die uhr nur 14:25 an selbst wenn schon 14:30 ist 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Danke fürs Reporten, sollte mit dem nächsten Update gefixed sein
