### ISSUE TITLE
[Bug]: Cosmetics Fetchen von einer Person die keinen eintrag hat 

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#148]
### What happened?

<html><body>

  | [15:27:09] [DefaultDispatcher-worker-31/ERROR]: No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class kotlin.collections.Map
-- | --
 

<span class="level level-error multiline">, Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?</span>
</body>
</html>

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
<html><body>

No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class kotlin.collections.Map
--
 

<span class="level level-error multiline">with response from https://api.norisk.gg/cosmetics/user/949c6de2-6324-421d-a3dc-53f9ec8c2dc6?uuid=26a4fcde-de39-4ff0-8ea1-786582b7d8ee:</span>
</body>
</html>

**Comment by TimLohrer** [comment]
Is nur wegen der neuen api oder? Kann weg? @copyandexecute
