### ISSUE TITLE
[Bug]: Custom Mods sind in allen Profilen

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#149]
### What happened?

Wenn man eine Custom Mod hinzufügt ist sie im jedem Profil drinnen. 

Custom Mods werden auch nicht als Mod in der Profilauswahl aufgelistet:
![image](https://github.com/NoRiskClient/issues/assets/68741965/766efe6b-33c1-4e72-9507-4451942c13ba)
![image](https://github.com/NoRiskClient/issues/assets/68741965/e7258b5a-0a01-44b2-842e-319fb4e9ebc6)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.4.2

**Comment by copyandexecute** [comment]
uuuuh, das machst du oder Tim?

**Comment by TimLohrer** [comment]
> uuuuh, das machst du oder Tim?

Ja

**Comment by SleepyPxnda** [comment]
Fixed

**Comment by Kolpixx** [comment]
Wieder genau das selbe Problem oder es wurd einfach nie gefixt lol

**Comment by TimLohrer** [comment]
Reopen aber grad gar kein Bock das zu fixen sry

**Comment by TimLohrer** [comment]
Muss ich zusammen mit https://github.com/NoRiskClient/issues/issues/267 coden.... Sollte dann hoffentlich beides gehen 🙏🏻
