### ISSUE TITLE
[Bug]: Overlay und Capes werden nicht gerendered

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#157]
### What happened?

Anzeigen von Capes und manchen Overlays geht nicht
Analysieren und fixen warum

![Image](https://github.com/NoRiskClient/issues/assets/44275698/db0a0a10-2020-4fbf-b803-475317926de2)

![Image](https://github.com/NoRiskClient/issues/assets/44275698/5ece6e0d-739f-419d-bb18-8cdb9946b778)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Man könnte überlegen bei Overlays einen Skin zu rendern, das Creeperoverlay wird nicht angezeigt, weil es doppelt ist, das enchanting ding weil es eine geringe Intensität hat, finde das erstmal fine

Bei dem Capes müssen wir in der Tat schauen, da bitte ein neues Issue aufmachen
