### ISSUE TITLE
[FEATURE-REQUEST]: Colorchange bei Overlays

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#161]
### Your idea

Wie halt im alten Cosmetics

![Image](https://github.com/NoRiskClient/issues/assets/44275698/9615f0b2-d14e-4007-913d-257238ad0d1c)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Hättest du lust dir mal essentials anzuschauen und überlegen wie wir das einbauen?
wäre dann down für eine session

**Comment by copyandexecute** [comment]
Wurde hier eingebaut https://github.com/NoRiskClient/issues/issues/176
