### ISSUE TITLE
[FEATURE-REQUEST]: Custom Error Popups

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#162]
### Your idea

Solche Error nachrichten, sollten durch ein Custom Popup replaced werden, die OS unabhängig sin

<img width="254" alt="image" src="https://github.com/NoRiskClient/issues/assets/58366920/232b011a-8245-451e-bfff-196cae515e76">

<img width="420" alt="image" src="https://github.com/NoRiskClient/issues/assets/58366920/a7a3d19b-d6ec-4cfc-bfca-d36d919953a1">

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@Greeenman999 @TomJuri 
Ich pinge mal freiwillige

**Comment by TimLohrer** [comment]
Wenn wir das schon machen auch bitte gleich schon bissl parsen... Dann ist einfavher zu sehen was nt passt

**Comment by copyandexecute** [comment]
Perfekt!

**Comment by TimLohrer** [comment]
@copyandexecute Mach mal lieber 3 Wochen draus wegen Abi 😀🔫

**Comment by copyandexecute** [comment]
Kriegen wir hin

**Comment by copyandexecute** [comment]
habs ja so halb gecodet
