### ISSUE TITLE
[FEATURE-REQUEST]: 5x Passwort eingeben bei macOS Wegen KeyChain

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#163]
### Your idea

Titel sagt es, kann man es auf 1x reduzieren?

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Kann ich morgen machen

**Comment by TimLohrer** [comment]
![Image](https://github.com/NoRiskClient/issues/assets/55639047/04b5b8b0-fcb4-413b-961a-0fec3dc2d48a)

Das geht leider nicht, weil die addierten tokens zu lang sind :/
Habe das grad alles gecoded und jz gehts nt 😭 
@copyandexecute
