### ISSUE TITLE
[FEATURE-REQUEST]: R-Shift Main Module

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#165]
### Your idea

Sollte beinhalten
- Alle Module
- "Tabs" also Friends und Cosmetics wo man draufklicken kann
- Eine Suchfunktion

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by PSJahn** [comment]
Update zu dem Image-Carousel: Um die Shadows der Images zu rendern werde ich wohl einen fragment shader anstatt normalen satin shader verwenden müssen, da das sonst mit der performance in die Tonne geht.... wünscht mir Glück

**Comment by copyandexecute** [comment]
Nicee, es fehlen nur noch Suche und die McReal, Cosmetic Tabs oder?

**Comment by copyandexecute** [comment]
PSJahn hat gezaubert
