### ISSUE TITLE
[FEATURE-REQUEST]: Alles "Serverless" Payback mäßig machen

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#166]
### Your idea

Yo Payback, freie bahn (muss ihn Adden)

### Where would this be applied?

Client, Launcher, Shop, Backend

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Was ist damit genau gemeint?

**Comment by copyandexecute** [comment]
Damit ist gemeint, dass wir sachen wie unsere branches.json, mods, maybe sogar cosmetics auslagern, dass falls mal etwas kaputt gehen sollte... es nicht an uns lag und auch wegen permission stuff etc

**Comment by copyandexecute** [comment]
@TimLohrer @Alex1607 @SleepyPxnda könnt ihr darüber mal brainstormen wie wir das am besten machen? lasst dann mal einen call machen für eine satisfying lösung

**Comment by TimLohrer** [comment]
Ja aber bitte in 1,5 wochen... Wegen abi :(

**Comment by Alex1607** [comment]
Wenn ich Serverless richtig verstehe so was wie "AWS Lambda" oder "Google Cloud Run"?
In dem Fall würde ich einfach mal Cloudflare Workers in den Raum werfen. Kosten für Aufrufe sind vernachlässigbar (30ct für 1 Million und 10 Millionen inklusive), Storage könnte sogar der Freeplan ausreichen und hat 25 Milliarden Reads Gratis. 

Generell hat es, glaube ich, auch den Vorteil, dass Cloudflare ohnehin schon genutzt wird und man keinen AWS, Google Cloud oder Azure Account machen muss, die einen, dann versuchen an jeder Ecke mit Traffic etc. abzuziehen.
https://developers.cloudflare.com/workers/platform/pricing/

**Comment by TimLohrer** [comment]
> Wenn ich Serverless richtig verstehe so was wie "AWS Lambda" oder "Google Cloud Run"?
> 
> In dem Fall würde ich einfach mal Cloudflare Workers in den Raum werfen. Kosten für Aufrufe sind vernachlässigbar (30ct für 1 Million und 10 Millionen inklusive), Storage könnte sogar der Freeplan ausreichen und hat 25 Milliarden Reads Gratis. 
> 
> 
> 
> Generell hat es, glaube ich, auch den Vorteil, dass Cloudflare ohnehin schon genutzt wird und man keinen AWS, Google Cloud oder Azure Account machen muss, die einen, dann versuchen an jeder Ecke mit Traffic etc. abzuziehen.
> 
> https://developers.cloudflare.com/workers/platform/pricing/

Das issue is aktuell eher noch ein spike oder eine story... noch nix sicheres geplant

**Comment by copyandexecute** [comment]
@enricoxD wir haben ja darüber geredet

**Comment by copyandexecute** [comment]
kannst ja hier updates posten!

**Comment by enricoxD** [comment]
Weiter in Richtung Serverless sind wird wir ja auch nicht gekommen. Es ging nur darum, wie wir manche Abläufe sicherer machen und automatisieren können, zumindest falls ich das so richtig verstanden habe  

1. Ein Vorschlag dabei war es, zu regulieren, was von wem gemerged werden darf
- Wir erstellen eine Branch basierend auf der development branch -> Um diese in Development zu mergen müssen X andere Coder dem Merge zustimmen -> Nur @copyandexecute kann den Development branch in den production Branch mergen

2. Production files könnten direkt über das Maven repo angeboten werden
- Publishen wir (nur NoRisk sollte die Permission dazu haben) den neusten Stand immer ins Maven Repo, können wir uns das händische hochladen der FIles und anpassen der configs sparen, da Maven uns immer sagt, welcher der neuste Release ist
- Weiterer Gedanke: Für öffentliche Mod Files könnten wir auch mavenCentral o.ä. benuzten, so ist zumindest der Filedownload nicht mehr unsere Sache. Jedoch dauert das uploaden dort öfter mal ein Weilchen

3. Dateien Serverless anzubieten macht eigentlich wenig Sinn, solange die Backends von uns gehostet werden. Selbst wenn der Download noch funktioniert, funktioniert der Client nicht richtig.

Glaube das war alles richtig relevante in die Richtung?

**Comment by copyandexecute** [comment]
@enricoxD nice, hast du maven installiert? 
wer übernimmt das mit dem user @Krxwallo willst du?

**Comment by enricoxD** [comment]
@copyandexecute für den client ist das ja soweit eig schon ready, haben nur paar mehr leute access auf den user, der auch uploaden kann.

Für HGLabor ist in der docker compose eig alles ready, warte nur auf die subdomain. Dann können wir das glaube anfangen zu usen.
User kann ich direkt erstellen, wenn die subdomain geht

**Comment by copyandexecute** [comment]
Krxwallo hat gekocht!
