### ISSUE TITLE
[Bug]: 120% launching

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#17]
### Contact Details

aim_shock

### What happened?

invalid % when launching

### Where is this happening?

Launcher

### Version (for launcher bugs)

0.2.9

**Comment by TimLohrer** [comment]
@TomJuri schau dir das mal an <3

**Comment by TomJuri** [comment]
Schaue es mir morgen nochmal genauer an, scheint aber nur beim letzen schritt (NoRisk Client texture verification) aufzutreten.
https://github.com/NoRiskClient/noriskclient-launcher/blob/17a31f9879130754d88f9a8620bbeedbcf7e7a3e/src-tauri/src/minecraft/progress.rs#L55
Bei der Rechnung hier kommt ~6000 raus (progress)
https://github.com/NoRiskClient/noriskclient-launcher/blob/17a31f9879130754d88f9a8620bbeedbcf7e7a3e/src-tauri/src/minecraft/progress.rs#L63
Und hier wird der maximale Wert berechnet index 5 * 1024 = ~5000 
6000/5000 = 1.2 = 120%

**Comment by TimLohrer** [comment]
> Schaue es mir morgen nochmal genauer an, scheint aber nur beim letzen schritt (NoRisk Client texture verification) aufzutreten.
> 
> https://github.com/NoRiskClient/noriskclient-launcher/blob/17a31f9879130754d88f9a8620bbeedbcf7e7a3e/src-tauri/src/minecraft/progress.rs#L55
> 
> Bei der Rechnung hier kommt ~6000 raus (progress)
> 
> https://github.com/NoRiskClient/noriskclient-launcher/blob/17a31f9879130754d88f9a8620bbeedbcf7e7a3e/src-tauri/src/minecraft/progress.rs#L63
> 
> Und hier wird der maximale Wert berechnet index 5 * 1024 = ~5000 
> 
> 6000/5000 = 1.2 = 120%

Sowas hatte ich mir schon gedacht, weil das seitdem es die norisk assets gibt auftritt... hatte nur noch nix überprüft :D

**Comment by TimLohrer** [comment]
@TomJuri wie siehts aus?

**Comment by TomJuri** [comment]
https://github.com/NoRiskClient/noriskclient-launcher/pull/30
