### ISSUE TITLE
[FEATURE-REQUEST]: Cosmetic Gifting

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#173]
### Your idea

Es sollte möglich sein einem Freund bzw anderen Spieler ein Cosmetic zu "giften".
Die coins sollten dabei vom eigenen Konto abgezogen werden

![image](https://github.com/NoRiskClient/issues/assets/44275698/fcb2218c-9494-4292-aa49-62489954b048)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
mache mich ran

**Comment by copyandexecute** [comment]
Einmal bitte Reviews
