### ISSUE TITLE
[FEATURE-REQUEST]: Toasts einbauen

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#174]
### Your idea

Es sollen die UwU-Lib Toasts und Errortoasts durch eigene NoRiskToasts ersetzt werden

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SleepyPxnda** [comment]
https://github.com/NoRiskClient/noriskclient-ui/pull/10

**Comment by copyandexecute** [comment]
https://github.com/NoRiskClient/issues/assets/58366920/650a4b58-c470-4b82-b5b1-87ec3ed6b502
