### ISSUE TITLE
[FEATURE-REQUEST]: Cosmetic Settings

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#176]
### Your idea

Ja cosmetic setting: farbe, x, y, scale?,...

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
<img width="395" alt="image" src="https://github.com/NoRiskClient/issues/assets/58366920/715c2ce2-b974-4a40-acb7-fff78618adf4">

**Comment by copyandexecute** [comment]
Was fehlt noch? Habe Farbe, Position, Spiegeln... Intensität etc... gibts noch nicht
