### ISSUE TITLE
[FEATURE-REQUEST]: Spoofprotection für cosmetics

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#177]
### Your idea

@TimLohrer weiß was

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
@TimLohrer kannst du nochmal die Idee schreiben?

**Comment by TimLohrer** [comment]
> @TimLohrer kannst du nochmal die Idee schreiben?

Ja kommt nachher

**Comment by copyandexecute** [comment]
Kommt nicht in die Public Beta

**Comment by TimLohrer** [comment]
Nur als info: ich will ungern meine Idee dafür hier reinschreiben, weil das public ist ^^

**Comment by SleepyPxnda** [comment]
Duplicate of #207
