### ISSUE TITLE
[Bug]: Man kann keine Module hinterm GUI bewegen

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#180]
### What happened?

https://github.com/NoRiskClient/issues/assets/68741965/87868e96-4d25-421a-875d-f4d803511280

Wenn man Module hinters GUI verschiebt, kann man sie nicht mehr bewegen und die sind dann halt stuck da.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Da dieser Bug mit der alten UI reported wurde, schließe ich das mal
