### ISSUE TITLE
[Bug]: Arrowtrail: Cloud & Flame spinnen rum

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#181]
### What happened?

https://www.youtube.com/watch?v=NZP0kzNjFKY

Wenn man Cloud oder Flame beim Arrowtrail Modul auswählt spawnen irgendwie auch Partikel hinter einem. Die anderen Trails gehen aber.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Also ja ich sehe den Fehler, aber denke nicht das das so schlimm ist
