### ISSUE TITLE
[Bug]: Mouse buttons don't work with zoom

### ISSUE THREAD

**Issue by shrobbyy** [NoRiskClient/issues#182]
### What happened?

I bind my zoom hotkey to Button 4 (side button on my mouse) and it doesn't work.
Nothing relevant in my logs.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Version (for launcher bugs)

0.4.4

**Comment by copyandexecute** [comment]
Fixed mit 2.0.0
