### ISSUE TITLE
[FEATURE-REQUEST]: Enhanced Player Animations

### ISSUE THREAD

**Issue by shrobbyy** [NoRiskClient/issues#184]
### Your idea

New module called "Enhanced Player Animations" - Adding minor stuff like 3rd-person-eating (Bedrock got that), minimally adjusted sprinting animation etc.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SleepyPxnda** [comment]
Das ist glaube auf unserer Globalen Roadmap irgendwo drauf, ich schließe das hier damit wir den Überblick behalten.
