### ISSUE TITLE
[Bug]: Nametag shadow not displayed properly

### ISSUE THREAD

**Issue by shrobbyy** [NoRiskClient/issues#185]
### What happened?

Text shadow almost invisible, background as a whole turns darker
![image](https://github.com/NoRiskClient/issues/assets/55342674/f7f71225-c013-4b9a-b8c4-2cdbebc31c52)

Shadow Text off for comparison (This is how vanilla looks like)
![image](https://github.com/NoRiskClient/issues/assets/55342674/57cf8219-4670-4379-9410-6d378ba031cd)

Only Shadow Text (Issue: No text shadow when background is turned off)
![image](https://github.com/NoRiskClient/issues/assets/55342674/e53d5207-4145-4a90-8ce2-05a6b7e0937f)

How I expect the name tags to look like when text shadow is enabled but background is turned off
(Used Text Display as an example)
![image](https://github.com/NoRiskClient/issues/assets/55342674/e856fc28-b3a6-4c42-8aac-21dfa99511bd)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Fixed
