### ISSUE TITLE
[Bug]: Joinen von Server aufgrund von "User not found" nicht möglich

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#187]
### What happened?

https://mclo.gs/XL0I8zh

Ich hatte das Problem auch auf dem Experimental Branch, aber keine Ahnung woran das liegt

### Where is this happening?

Client, Backend

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Wie kann man das reproduzieren?

**Comment by copyandexecute** [comment]
bump

**Comment by SleepyPxnda** [comment]
Fixed
