### ISSUE TITLE
[Bug]: Custom Launcher Capes werden nicht angezeigt

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#188]
### What happened?

Im Launcher ausgewählte capes werden nicht ingame angezeigt

In der Datenbank wird es aber richtig persistiert.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/1c2f7c98-f63f-4532-8834-8e1bbffbe30c)

**Comment by copyandexecute** [comment]
Sooo habe das CustomCape jetzt hardcoded, durch das kopieren von anderen Branches ging das immer verloren.
Es wird jetzt live geupdated.

**Comment by copyandexecute** [comment]
Einen bug gibt es noch, es wird nicht live im Wardrobe geupdated... aber das ist mir jetzt mal egal
