### ISSUE TITLE
[Bug]: Linux | XDG Desktop Portal not working

### ISSUE THREAD

**Issue by shrobbyy** [NoRiskClient/issues#189]
### What happened?

[https://wiki.archlinux.org/title/XDG_Desktop_Portal](url) is responsible for allowing applications to open a browser when clicking a link and opening a folder/dialogue when clicking something.

That said, clicking links in chat does nothing, clicking "Open Resourcepack folder" does nothing in NoRisk Client. It works with vanilla.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
@shrobbyy wie siehts hier aus ?

**Comment by shrobbyy** [comment]
Tritt immer noch auf. Kann keine Links öffnen, nicht den Resourcepack Ordner öffnen und auch öffnet sich kein Browser, wenn ich im Cosmetic Shop was auswähle.

**Comment by copyandexecute** [comment]
ufff

**Comment by copyandexecute** [comment]
shrobby komm zurück :(

**Comment by onlyJakob** [comment]
bei Lunar das gleiche https://github.com/flathub/com.lunarclient.LunarClient/issues/20

vermutlich ein Minecraft Bug

**Comment by 0x3C50** [comment]
Kann ich nicht nachbilden. Bei mir öffnet sich ganz normal der ordner der resourcepacks, auch auf linux via xdg-open. Sehe auch im mc code keinen grund warum das nicht funktionieren würde.

Evtl hängts mit flatpak / appimage zusammen, dass da berechtigungen nicht ganz stimmen, aber das kann ich mir eher wenig vorstellen.

**Comment by onlyJakob** [comment]
@shrobbyy welche DE/WM nutzt du?

**Comment by TimLohrer** [comment]
@SirKnubble sag was schlaues.. was mache ich hiermit?

**Comment by SirKnubble** [comment]
> @SirKnubble sag was schlaues.. was mache ich hiermit?

Vergessen. (oder so)
Das wird nen Perms Ding sein wie das mit dem Mic.

**Comment by 0x3C50** [comment]
ohne weitere details können wir hier leider nicht viel machen. ticket schließen und auf antwort warten
