### ISSUE TITLE
[Bug]: Kompatibilität mit anderen Cosmetic Mods

### ISSUE THREAD

**Issue by raided2108** [NoRiskClient/issues#190]
### What happened?

wenn man eine mod wie essential mod installiert, überlappen sich die cosmetics mit denen von dem norisk client. 
![mcreal_secondary_2024-04-19_16 35 51](https://github.com/NoRiskClient/issues/assets/167546609/a4576d1e-f017-4944-b2b9-0d27aa64823e)

### Where is this happening?

Backend

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by TimLohrer** [comment]
Ja die mods kommen raus

**Comment by SleepyPxnda** [comment]
@TimLohrer haben wir hier noch ein Doing ?

**Comment by SleepyPxnda** [comment]
Wenn man beide Cosmeticmods gleichzeitig benutzt, dann ist man selber schuld

**Comment by raided2108** [comment]
Essentials ist nicht nur für cosmetics sondern auch für world hosting und
andere Features. Ka was genau meine Schuld ist beim mehrere mods
gleichzeitig benutzen

Felix Grohme ***@***.***> schrieb am Fr., 5. Juli 2024, 11:22:

**Comment by SleepyPxnda** [comment]
@raided2108 Wusste ich nicht, dass man das auch mit Essentials machen kann.

Da wir so einen Funktion aber auch im NRC haben, sehe ich da nicht den Sinn das kompatibel zu machen.
Zudem müssten wir dann immer schauen, dass unsere Cosmetics mit allen anderen Cosmetic Mods kompatibel sind.
Diese Limitierung wollen wir uns aber nicht setzen. Daher musst sich ein User leider entscheiden welche Cosmetic Mod er nimmt oder mit den Konsequenzen leben nur eine Cosmetic Mod aktiv zu nutzen.

Was du machen könntest, wäre ein NRC-Outfit anzulegen, dass du immer ausrüstest, wenn du Essentials Cosmetics benutzen möchtest

**Comment by raided2108** [comment]
Ja okay kann ich verstehen. Danke für die Antwort!

Felix ***@***.***> schrieb am Sa., 6. Juli 2024, 10:42:
