### ISSUE TITLE
macOS Autoupdater not working again [Bug]: 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#193]
### What happened?

Der Autoupdater funktioniert wieder nicht (macOS)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

**Comment by copyandexecute** [comment]
@MeisterAH Hattest du es als App installiert?

**Comment by MeisterAH** [comment]
ja es ist im application ordner

**Comment by SleepyPxnda** [comment]
Fixed soweit ich weiß
