### ISSUE TITLE
[Bug]: Copy to Clipboard im Screenshot Module ist broken

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#194]
### What happened?

MacOs throwed error
und auf Windows gehts auch nicht geil...
einmal bitte gucken wie andere mods das machen und anpassen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
@TimLohrer wie kann ich das noriskclient-screenshot repo verlinken?

**Comment by SleepyPxnda** [comment]
Fixed
