### ISSUE TITLE
[Bug]: Der legendäre TCP Socket Error

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#197]
### What happened?

![grafik](https://github.com/NoRiskClient/issues/assets/58366920/d601a0e0-3d15-47a0-b26d-8486f440918a)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/3b37f486-44b4-4051-a806-26702e27d608)

**Comment by copyandexecute** [comment]
https://discord.com/channels/616186924390023171/1234142081203835000

**Comment by copyandexecute** [comment]
https://github.com/seanmonstar/reqwest/issues/2265

**Comment by copyandexecute** [comment]
Liegt anscheinend an AntiVirus

**Comment by SleepyPxnda** [comment]
Ich denke mal das hier ist auch fixed, zumindest hat niemand mehr darüber geredet, falls wieder auftritt gerne re-open
