### ISSUE TITLE
[FEATURE-REQUEST]: Search Function für die Mods

### ISSUE THREAD

**Issue by sl3meyy** [NoRiskClient/issues#200]
### Your idea

Quasi eine Art Such Funktion für die Mods im Client (diese Zoom sachen usw) Dass man nicht ewig suchen muss, so wie Lunar und badlion z.B. auch, wie auf dem Foto, mit extrem hoher auflösung, gezeigt.
![image](https://github.com/NoRiskClient/issues/assets/149706711/c0cdfc08-f0cc-4ad4-86ea-24d1680a28ad)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Kommt in der neuen version
