### ISSUE TITLE
[Bug]: Error beim Start

### ISSUE THREAD

**Issue by Fr3d33** [NoRiskClient/issues#202]
### What happened?

Ich kriege einen Error wenn ich Minecraft durch den Client Starte. Wenn ich auf den Spielerkopf klicke lädt es kurz und dann kriege ich diesen Error: https://mclo.gs/feb4d04

### Where is this happening?

Client, Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

v.0.4.7

**Comment by TimLohrer** [comment]
Sowas bitte erst in #closed-beta, dass sin meistens temporäre probleme wärend updaten von uns
