### ISSUE TITLE
[Bug]: Subwaysurfers Auswahlmenu Sound ist überall auf HGLabor in den ersten 3 Slots

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#208]
### What happened?

Einfach auf den Buildserver gehen und die ersten 3 slots durchscrollen
Sound kommt, aber UI ist versteckt

https://github.com/NoRiskClient/issues/assets/44275698/0ebc38bb-d75b-4d8d-804d-59035b81b619

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
sollte fixed sein?
