### ISSUE TITLE
Keystrokes

### ISSUE THREAD

**Issue by 0hAlex** [NoRiskClient/issues#21]
### Your idea

![2023-11-19_15 22 19](https://github.com/NoRiskClient/issues/assets/85081415/869c60e6-1de6-41fe-b7ac-60d31f213ab8)
Keystrokes, ziemlich basic
finde dass space und right/leftclick optinal sein sollte, also dass man es auch so einstellen können sollte dass man nur wasd keystrokes hat

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@PSJahn

**Comment by copyandexecute** [comment]
![Image](https://github.com/NoRiskClient/issues/assets/58366920/a59418be-7d09-46c7-b947-1c515af57da9)

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/2a1378ac-4d63-4558-b9f4-45e0ee83b7eb)

**Comment by TimLohrer** [comment]
Sehr geil

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/b99853ce-2a7e-4658-8e29-48ed1bd93826)
Keystrokes sollte jetzt funktionieren. Damit man aber das volle potential ausschöpfen kann muss ich was weiteres coden

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/ba1d2d7c-a9d4-471b-816b-3af963d6b8df)
Nämlich das hier @TimLohrer wenn du mir dafür ein Issue aufmachen könntest wäre mega

**Comment by TimLohrer** [comment]
> ![grafik](https://github.com/NoRiskClient/issues/assets/58366920/ba1d2d7c-a9d4-471b-816b-3af963d6b8df)
> Nämlich das hier @TimLohrer wenn du mir dafür ein Issue aufmachen könntest wäre mega

Kommt nachher

**Comment by TimLohrer** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/58366920/300266688-ba1d2d7c-a9d4-471b-816b-3af963d6b8df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTAxNjUsIm5iZiI6MTcwNjQ0OTg2NSwicGF0aCI6Ii81ODM2NjkyMC8zMDAyNjY2ODgtYmExZDJkN2MtYTlkNC00NzFiLTgxNmItM2FmOTYzZDZiOGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzNTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzhjY2I4OTYxMDUxNjkxYmU5YmEzZjU4YjRlN2Q1MzYwZGYwNGQ4ODRkMzVkZGY5ZWJiNmMwNTY2NzBhZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D67kR6CXd5S1fIAFU11VOfc5dOh0dByu44GiGGvRrO8) Nämlich das hier @TimLohrer wenn du mir dafür ein Issue aufmachen könntest wäre mega

https://github.com/NoRiskClient/issues/issues/113
