### ISSUE TITLE
[Bug]: Netherite Tools sind zu klein 

### ISSUE THREAD

**Issue by Legolariors** [NoRiskClient/issues#210]
### What happened?

die größe von netherite tools sind in der hand zu klein 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Screenshot? Konnte ich nicht reproduzieren.

**Comment by SleepyPxnda** [comment]
Fixed, falls immernoch nen Problem gerne re-open
