### ISSUE TITLE
[Bug]: Authorization bug on first sign in with windows

### ISSUE THREAD

**Issue by qeinz** [NoRiskClient/issues#211]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/66924611/37e2b155-04bd-4c70-8fb2-61e127fbe839)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

v0.4.9

**Comment by SirKnubble** [comment]
Zu wenig Infos, versuch einfach später nochmal, überlastet.

**Comment by SleepyPxnda** [comment]
Fixed
