### ISSUE TITLE
[Bug]: Screenshot-Modul komplett broken

### ISSUE THREAD

**Issue by SirKnubble** [NoRiskClient/issues#212]
### What happened?

Screenshot-Module ist immernoch cursed.

- Async: Screenshots sind straightup full-black
![Bild_2024-06-19_160202235](https://github.com/NoRiskClient/issues/assets/102559031/0f5e1813-e493-4c74-afe5-64e930c98a04)

- Screenshot POVs sind vertauscht. Machst in First-person -> Output ist in Third-person und umgekehrt.

DA IST DEIN ISSUE, TIM!

### Where is this happening?

Client

**Comment by SleepyPxnda** [comment]
[OPEN] funktioniert auch net

**Comment by copyandexecute** [comment]
https://imgur.com/HbP4j3M sollte passen
