### ISSUE TITLE
[Bug]: Übersetzung fehlt

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#215]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/44275698/cebeae04-b1af-4f7b-990c-5b2c048ea9c8)
![image](https://github.com/NoRiskClient/issues/assets/44275698/86f80659-afab-49ba-be75-ca3e90cbd3a7)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
[PR: Update translation de_de](https://github.com/NoRiskClient/translations/pull/2)
[PR: Update translation en_us](https://github.com/NoRiskClient/translations/pull/3)

**Comment by brentspine** [comment]
Um das Issue zu fixen, sollten meine beiden Pull Requests angenommen werden. (Oben verlinkt)

**Comment by brentspine** [comment]
Siehe Folgende:

https://github.com/NoRiskClient/translations/pull/2/commits/324829dfb657e68221c46573ab968885e0a5acf8
https://github.com/NoRiskClient/translations/pull/3/commits/64e68a342686ad2177582ba90aa7a7e4d193fe6f

**Comment by SleepyPxnda** [comment]
Hier kann man denke alle PRs mal verlinken

[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/1)
[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/2)
[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/3)
[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/4)
[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/5)
[#https://github.com/NoRiskClient/translations/pull/6](https://github.com/NoRiskClient/translations/pull/6)

**Comment by Hapixh** [comment]
Gibt noch einen weiteren...  Ist die Cooldown  message. 
![image](https://github.com/NoRiskClient/issues/assets/165488563/93bde1a2-d0c0-4ecc-b4e0-f97632156d13)

**Comment by brentspine** [comment]
Könnte ein Key Error sein. Ich mache gleich ein eigenes Issue auf
