### ISSUE TITLE
[Bug]: CosmeticUI unleserlich mit GUI Scale 2

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#216]
### What happened?

Die UI ist super klein wenn man auf GUI Scale 2 ist.
Auch mit 4k Bildschirmen ist sie unleserlich.

![image](https://github.com/NoRiskClient/issues/assets/44275698/c3ee4b2d-ad3b-4938-b825-bc248b58fd8c)

![image](https://github.com/NoRiskClient/issues/assets/44275698/68a6e88f-6db6-460d-bad2-741d714446e5)

![image](https://github.com/NoRiskClient/issues/assets/44275698/77d514e2-d0aa-44d9-af39-364ca46bfd24)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
![image](https://github.com/NoRiskClient/issues/assets/44275698/a1cb4ce5-b56d-44da-955a-a0d4f58e9480)
![image](https://github.com/NoRiskClient/issues/assets/44275698/327dde06-e402-4fdd-aa81-71a7b34addd1)

**Comment by copyandexecute** [comment]
fixed 
![grafik](https://github.com/user-attachments/assets/a1b4845f-a221-49bf-bb2c-26fef49cc493)
