### ISSUE TITLE
[FEATURE-REQUEST]: Cosmetic Tabs einzeln anzeigen

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#220]
### Your idea

![image](https://github.com/NoRiskClient/issues/assets/44275698/f0cbeffb-344d-49d5-9779-16261bb60a4d)

Es ist imo super inintuitive das man die Kategorie über den Text wechselt, ohne das Video gesehen zu haben.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
stimm ich dir zu, wie fix ich das am besten

**Comment by copyandexecute** [comment]
habs probiert und hab nichts satifygisns gefunden

**Comment by SleepyPxnda** [comment]
Alles klar, dann schließ ich das
