### ISSUE TITLE
[Bug]: UI Elemente können aus dem Bildschirm geschoben werden

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#221]
### What happened?

So eine Art "Bordersnapping" wäre geil

![image](https://github.com/NoRiskClient/issues/assets/44275698/e7ce3e01-2bca-4378-bc99-1d67cff12575)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Habs probiert zu fixen und war zu dumm, wenn jemand übernehmen will gerne ansonsten erstmal auf warteliste

**Comment by 0x3C50** [comment]
anscheinend schon gefixt. kanns bei mir zumindest nicht mehr replizieren
