### ISSUE TITLE
[FEATURE-REQUEST]: Stärkerer Contrast zwischen "Mod an" und "Mod aus"

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#222]
### Your idea

Der Unterschied zwischen "Mod an" und "Mod aus" ist so klein, dass man fast nicht erkennen kann in welchem Status die Mod ist.

![image](https://github.com/NoRiskClient/issues/assets/44275698/ed670c90-701a-4d24-baa7-9df3d6234a1e)
![image](https://github.com/NoRiskClient/issues/assets/44275698/bb5e5dad-a668-4f76-b809-d96b42da1d6c)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
@PSJahn kannst du nochmal schreiben was du dafür empfohlen hast

**Comment by PSJahn** [comment]
öh weiß nicht mehr, custom rgb value für enabled/disabled per module maybe aber sonst kp mehr

**Comment by PSJahn** [comment]
oder einfach die border größer die ist klein as fuck

**Comment by MeisterAH** [comment]
ist das hier nicht schon fixed, weil jetzt sind die namen ja ausgraut/weiß

**Comment by SirKnubble** [comment]
Wenn sogar ich den Unterschied erkenn durch den grauen/weißen Title, dann kann das jeder (außer Narrator)
