### ISSUE TITLE
[BUG]: Motion Blur macht MC-Real Screenshots kaputt

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#226]
### Your idea

Es wäre praktisch, wenn man bei MCReal einstellen könnte, wie viel ticks zwischen den Screenshots gewartet werden soll.
Wenn man mit Motionblur spielt und ein Screenshot macht, dann ist ein Bild immer etwas unscharf wegen den Motionblur
![image](https://github.com/NoRiskClient/issues/assets/68741965/85730b76-5c86-4994-b70b-75c994fa3033)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SleepyPxnda** [comment]
Kann ich leider nicht richtig nachstellen, kannst du evtl nen kleines Video davon machen ?

**Comment by copyandexecute** [comment]
Ach interessant das ist auch wenn man sich nicht bewegt

**Comment by copyandexecute** [comment]
danke bin dran
