### ISSUE TITLE
[Bug]: Custom Crosshair | Dot funktioniert nicht

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#227]
### What happened?

Die Dot Einstellung beim Custom Crosshair Modul funktioniert nicht.
![image](https://github.com/NoRiskClient/issues/assets/68741965/c6f3f5a9-93ac-411b-836b-fe88faa7dffb)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/5efb84f1-76f4-40b4-a455-7a0bdf2010bb)
uff kannst du schreiben wie ich das reproduzieren kann oder mir die config schicken?

**Comment by SleepyPxnda** [comment]
Fixed

**Comment by copyandexecute** [comment]
kanns leider nicht reproduzieren kannst du mir wieder die aktuelle config schicken

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/14a8f2ec-7dcd-4924-a972-fca0966697fa)
![grafik](https://github.com/user-attachments/assets/6c9bf8e1-86c8-4ea9-ba50-c815b53d0f98)
![grafik](https://github.com/user-attachments/assets/8427aea1-9b4f-4d77-99d9-614a8d208d0f)
![grafik](https://github.com/user-attachments/assets/cfaca813-4d3f-437b-8915-0aba39c1cb3f)


hmmm aber mir fällt auf der dot ist kein wirklicher dot, ich code das vlt mal neu das war von moozi deswegen keine ahnung aktuell

**Comment by Kolpixx** [comment]
Ist noch nicht gefixt @SirKnubble (oder warum closed?)

**Comment by SirKnubble** [comment]
> Ist noch nicht gefixt @SirKnubble (oder warum closed?)

War es bei mir schon? Gerne reopen

**Comment by Kolpixx** [comment]
> > Ist noch nicht gefixt @SirKnubble (oder warum closed?)
> 
> War es bei mir schon? Gerne reopen

Ist auch anscheinend irgendwie nur bei mir verbuggt oderso, aber Norisk wollte das halt maybe noch umcoden, sodass das auch ein richtiger dot ist:
> hmmm aber mir fällt auf der dot ist kein wirklicher dot, ich code das vlt mal neu das war von moozi deswegen keine ahnung aktuell

**Comment by SirKnubble** [comment]
> Ist auch anscheinend irgendwie nur bei mir verbuggt oderso, aber Norisk wollte das halt maybe noch umcoden, sodass das auch ein richtiger dot ist

Ihr macht mich fertig 😭 (alles gut)

Dann mach ichs auf Paused

**Comment by Kolpixx** [comment]
Joa jetzt funktionierts irgendwie. Bin von einer AMD iGPU zu einer Nvidia Karte rübergeswitcht. Maybe liegts aus irgendeinen Grund daran? Ka sehr weird irgendwie.
