### ISSUE TITLE
[Bug]: Custom Mods lassen sich nicht im Launcher löschen.

### ISSUE THREAD

**Issue by siraytr** [NoRiskClient/issues#228]
### What happened?

Wenn man auf den Button 'Delete' klickt, kommt ein Fehler und die Mod kann nicht gelöscht werden. Man kann jedoch die Mod am angegebenen Pfad manuell löschen. Ach so, und beim Settings-Tab im Launcher kann ich nicht ganz herunter scrollen.
![Error](https://github.com/NoRiskClient/issues/assets/113358673/088316b9-c7b5-4bc4-a638-a8dd8e5d10b9)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Version (for launcher bugs)

v0.5.2

**Comment by SirKnubble** [comment]
Du benutzt Linux?

Falls ja, maybe der path-env error (fix rs)

**Comment by siraytr** [comment]
Sry für die späte Antwort knupsel bin letzte Zeit sehr inaktiv vorallem weil ich mein BIOS zernommen haben. 
(antworte Grad vom Handy /: )

Ich benutz Linux.

Beim 2 Punkt von dir muss ich mich nochmal kurz informieren. Muss ich das selber fixxen ? Glaube hab mal irgendwas mit fixrs oder so gemacht idk ob das das war.

**Comment by siraytr** [comment]
Sry wegen der späten Antwort, Knupsel. Ich war in letzter Zeit sehr inaktiv, vor allem weil ich mein BIOS zerschossen habe.
(Antworte gerade vom Handy /: )

Ich benutze Linux.

Beim zweiten Punkt von dir muss ich mich nochmal kurz informieren. Muss ich das selber fixen? Ich glaube, ich habe mal irgendwas mit Fixrs oder so gemacht, aber ich bin mir nicht sicher, ob das das war (lange her und ich bin grad verwirrt xD).

**Comment by SirKnubble** [comment]
Warum Knubsel 😭

War grundsätzlich ne Notiz, gerade an Tim, dass das maybe was mit Linux Pathing zu tun hat.

**Comment by TimLohrer** [comment]
> Warum Knubsel 😭
> 
> War grundsätzlich ne Notiz, gerade an Tim, dass das maybe was mit Linux Pathing zu tun hat.

Hattest du da nt mal n pr oder muss ich das noch machen?
Sonst mach nen pr auf meinen branch, wenn du das schon lokal hast, dann geht das alles schneller ^^

**Comment by SirKnubble** [comment]
> > Warum Knubsel 😭
> > 
> > War grundsätzlich ne Notiz, gerade an Tim, dass das maybe was mit Linux Pathing zu tun hat.
> 
> Hattest du da nt mal n pr oder muss ich das noch machen?
> Sonst mach nen pr auf meinen branch, wenn du das schon lokal hast, dann geht das alles schneller ^^

Hatte ich, kp ist in den Backrooms.
Mach wenn ich Zuhause bin.

**Comment by SleepyPxnda** [comment]
@SirKnubble mach mal

**Comment by SleepyPxnda** [comment]
Allet klar
