### ISSUE TITLE
[FEATURE-REQUEST]: Do not show Unlink Discord Button on Main Page

### ISSUE THREAD

**Issue by eazypaulCode** [NoRiskClient/issues#229]
### Your idea

I think it's not very smart to add a button without confirmation to the main page that unlinks the user's discord account. Maybe add a confirmation or even better move it somewhere else (settings?)?

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by SleepyPxnda** [comment]
Nah das net wichtig und auch kinda unnötig
