### ISSUE TITLE
Armor Status

### ISSUE THREAD

**Issue by 0hAlex** [NoRiskClient/issues#23]
### Your idea

![image](https://github.com/NoRiskClient/issues/assets/85081415/814ffe2a-133b-435f-ac62-e46ec5e0564d)
Armor status halt, item ganz oben ist das in meiner main Hand, das sollte man enablen und disblen können

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/48fa5b3b-c7d0-444f-b52d-61a5829fb659)

**Comment by copyandexecute** [comment]
Armor Status Done https://gyazo.com/2c864005117e63fa6d164954209175de
