### ISSUE TITLE
[Bug]: Required Mods updaten

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#231]
### What happened?

Aus https://discord.com/channels/774271756549619722/1256985251960324226/1256985251960324226

Required Mods wie Iris sind nicht aktuell und führen bei anderen Mods zu Problemen

### Where is this happening?

Client, Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
Updated to 1.7.2+1.20.4
