### ISSUE TITLE
[Bug]: Kaufen von Coins endet manchmal in "Empty Basket"

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#232]
### What happened?
Aus https://discord.com/channels/774271756549619722/1256968614960173157/1256968614960173157

![image](https://github.com/NoRiskClient/issues/assets/44275698/a4ced3c7-b619-4db3-aca9-bdbf27fb923c)

### Where is this happening?

Client, Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/0a0a2d5f-9d9b-4493-a84f-db72a7d0aa6a)
