### ISSUE TITLE
[Bug]: Zahl im Tab verschoben

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#233]
### What happened?

Aus https://discord.com/channels/774271756549619722/1255589960631980144/1255589960631980144

![image](https://github.com/NoRiskClient/issues/assets/44275698/8b7bedc9-ce1e-43f5-a031-2f5cdfaf7df0)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/05d55db9-a73c-4cae-83a3-4871a74531a7)
