### ISSUE TITLE
[Bug]: F3 disabled alle NRC Module

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#234]
### What happened?

Aus https://discord.com/channels/774271756549619722/1255538053615849472/1255538053615849472

"wenn man zB den pie chart (F3 + 1) öffnet, bleiben die module sichtbar und wenn man das F3 menu dann wieder schließt, sind die module immernoch unsichtbar. (kann man wiederholen, um es wieder "normal" zu machen)"

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Hapixh** [comment]
Yo, reproducible

**Comment by copyandexecute** [comment]
digga was ein bug, bin dran danke
