### ISSUE TITLE
[Bug]: MC-Real doppelte Kommentarzeile

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#237]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/44275698/7bb85bc4-6615-4ead-9466-61d3771e56b4)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by 0x3C50** [comment]
passiert wenn man mehrere male auf den kommentar button klickt. man sollte evtl schon schauen ob da ein textfeld offen ist

**Comment by 0x3C50** [comment]
Fixed in 125fd5e9
