### ISSUE TITLE
[Bug]: authentication problem after username change 

### ISSUE THREAD

**Issue by antoni12341** [NoRiskClient/issues#24]
### What happened?

I changed the username and the NoRiskClient dont updated this information, so i could no longer enter premium servers. Restart the client doesnt help in this case, you have to re-login.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.3 (20230927)

**Comment by copyandexecute** [comment]
Gute Neugikeiten ich code gerade den refresh den norisktokens und anscheinend kann ich damit auch dieses problem zufällig lösen.

**Comment by TimLohrer** [comment]
> Gute Neugikeiten ich code gerade den refresh den norisktokens und anscheinend kann ich damit auch dieses problem zufällig lösen.

Geil!

**Comment by copyandexecute** [comment]
Ist Quasi zu 95% gefixed... gibt zwar noch ein problem aber haha... psst
