### ISSUE TITLE
[Bug]: Änderungen am Alpha Channel stellen die Farbe auf Rot

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#240]
### What happened?

https://github.com/NoRiskClient/issues/assets/44275698/c8c94d91-f735-44c9-ab79-a6a4e5db6333

Video beschreibt alles

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by 0x3C50** [comment]
ARGB farbe integer wurde als RGBA interpretiert

**Comment by 0x3C50** [comment]
scheint tatsächlich schon gefixt zu sein. bei mir stimmt alles.
