### ISSUE TITLE
[Bug]:  Block outline Probleme  mit shader

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#242]
### What happened?

If I want to make the width of the block outline thicker but add a shader, it doesn't work (I can't add a video because my file is too large. Here is the link to the video) https://imgur.com/fXcZ0eN

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/g2w30qK
```

**Comment by copyandexecute** [comment]
@0x3C50 kannst du da bitte reinschauen ob man das überhaupt supporten kann? das ist alter mooozi code, also kp wie die outline gecodet wurde

**Comment by 0x3C50** [comment]
sollte gehen

**Comment by 0x3C50** [comment]
ok @copyandexecute update: der shader ist das problem. wir nutzen schon rendertype lines, der shader sollte da die breite respektieren. das tut er nicht. da können wir wenig tun ohne den shader etwas kaputtzumachen

**Comment by TimLohrer** [comment]
wontfix, shader sind eh immer funky.
wenn crazy nachfrage sein sollte reopen
