### ISSUE TITLE
[Bug]: Nametag icon verschwindet mit shader

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#243]
### What happened?

Wenn ich einen shader anmache, verschwindet das Nametagicon. Video  (wasserzeichen, da ich die Datei über eine Website verkleinert habe) https://imgur.com/a/gKu8OTL

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://imgur.com/fXcZ0eN
```

**Comment by copyandexecute** [comment]
danke fürs reporten ist gefixed 
![grafik](https://github.com/user-attachments/assets/e2218b13-c228-4c10-998e-828b5016b192)
