### ISSUE TITLE
[FEATURE-REQUEST]: ToggleSprint Module

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#244]
### Your idea

Ein Module das es erlaubt, direkt beim joinen schon im SPRINTING State zu sein.

Das soll es auf PVP Servern einfacher machen, sodass man nicht immer beim joinen erstmal STRG drücken muss.

Es geht hier nicht um das togglen von sprinten oder nicht, das ist bereits in den Vanilla Einstellungen zu finden.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SirKnubble** [comment]
@copyandexecute bitti simples aber wichtiges Feature das sich oft gewünscht wurde

**Comment by copyandexecute** [comment]
Gibts halt schon in minecraft... aber wrappe ich da mal was

**Comment by copyandexecute** [comment]
added auf norisk-dev bitte testen

**Comment by Fylexxy** [comment]
Bei mir ist es ab und zu so das es einfach aufhört und nicht mehr funktioniert, keine Ahnung weshalb.
