### ISSUE TITLE
[Bug]:  Mods können aus dem Screen gezogen werden 

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#245]
### What happened?

Wenn man eine Mod verschieben möchte, kann man diese aus dem Sichtfeld schieben. Maybe könnte man eine Border oder so am Rand des screens coden, damit so etwas verhindert wird?!  Video: https://imgur.com/a/FGLEYWW

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/KUGuFLS
```

**Comment by SleepyPxnda** [comment]
Duplicate of #221
