### ISSUE TITLE
[Bug]: Unable auf McReal etwas hochzuladen nach löschen eines Posts

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#247]
### What happened?

Ich habe ein Screenshot hochgeladen, und diesen dann wieder von McReal gelöscht. Nach dem Löschen dieses posts kann ich jetzt nichts neues mehr hochladen. (Andere user haben auch das Problem) 

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/6Nf8mIu
```

**Comment by SleepyPxnda** [comment]
I guess, das liegt daran, dass du nur einmal am Tag was hochladen kannst oder ?

**Comment by copyandexecute** [comment]
https://discord.com/channels/774271756549619722/1252965661391716402/1263057577500217414
