### ISSUE TITLE
[Bug]:  Profile funktionieren nicht

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#248]
### What happened?

Ich versuche immer Bugs mit einem neuen Profile zu reproducen, damit ich sicher gehen kann, dass es an keiner Mod, bzw an einem Profile Fehler liegen kann. Dabei ist mir aufgefallen, dass wen ich ein neues Profile erstelle die mods aus dem alten profile auch in dem neuen sind. Also ist das Quasi kein neues Cleanes Profile sondern ein Klon des Main Profiles. 

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/REYawOn
```

**Comment by TimLohrer** [comment]
Also der einzige weg den ich sehe wie das passieren könnte wäre wenn du per unendlichem Zufall die gleiche profile UUID gerolled bekommst, aberrrr..............

**Comment by SleepyPxnda** [comment]
Fixed
