### ISSUE TITLE
[Bug]: Ingame GUI in der Replaymod 

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#249]
### What happened?

Wenn ich in ein replay gehe, sehe ich meinen chat, scoreboard und meine Mods. Zudem kann ich im replay auch screenshots machen, diese aber nicht kopieren, da ich nicht mit dem Chat Interagieren kann,
![NRC](https://github.com/NoRiskClient/issues/assets/165488563/bfa6e78f-7d7b-4ca8-829d-4f2bdfaf9de7)

### How to reproduce ?

1. Füge die Replaymod über zum Client hinzu.
2. Erstelle ein Replay
3. Schau dir das Replay an.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/aQH1abU
```

**Comment by Hapixh** [comment]
WICHTIG: Render sieht normal aus!

**Comment by SirKnubble** [comment]
Intended von Replay Mod, kein Bug.
> Closed.
