### ISSUE TITLE
[Bug]: Capes are not rendered in the cosmetic GUI Cape tab

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#25]
### What happened?

![Image](https://github.com/NoRiskClient/issues/assets/55639047/4ce94065-fb1c-4320-8288-91eb2b5a9ba1)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Nur die Capes?

**Comment by TimLohrer** [comment]
> Nur die Capes?

Ja, und irgendwie nur im online mode !?!?
im dev environment geht alles
