### ISSUE TITLE
[Bug]:  Pfeil bleibt bugt in Cosmetics

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#250]
### What happened?

Wenn man von einem Pfeil abgeschossen wird, bugt dieser in den Cosmetics

### How to reproduce ?

1. Wähle ein cosmetic aus
2. Schieße dich selber ab 

https://github.com/NoRiskClient/issues/assets/165488563/df380b60-5710-4f75-9da5-edf3672e1d53

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/7qAoelL
```

**Comment by SleepyPxnda** [comment]
Laut Hapixh passiert das immer und überall
