### ISSUE TITLE
[Bug]:  Stack kann nicht in der Suchleiste gesucht werden

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#252]
### What happened?

Wenn man nach Stack im Mod menu sucht, wird diese nicht angezeigt.

https://github.com/NoRiskClient/issues/assets/165488563/f62b02e5-1cab-470b-bffb-c8365612764f

### How to reproduce ?

1. Öffne das Mod menu
2. Suche nach Stack 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/JL0mOFC
```

**Comment by copyandexecute** [comment]
@SleepyPxnda da brauch ich einen akademiker kannst du das coden? 
![grafik](https://github.com/user-attachments/assets/7ca5ea5d-3663-4487-8650-7db59a20814e)
habs damals nicht hinbekommen man muss das glaube geil mit levenstehin oder fuzzy search algorithm machen

**Comment by SleepyPxnda** [comment]
Jo schau ich mir an 🚀

**Comment by SleepyPxnda** [comment]
@copyandexecute Wo ist das denn ?

**Comment by copyandexecute** [comment]
CarouselScreen UI Module

**Comment by SleepyPxnda** [comment]
Jo habs gefunden, sitze dran. 
Algorithmik ist tbh net mein Fachgebiet lol

**Comment by Greeenman999** [comment]
Chat Module hatte "chat stack" als Search Term. Jetzt wird erst der Name überprüft und dann die Search Terms. Dass das mit dem "Pings" und "Ping" nicht ging lag daran, dass das keypressed event vor dem chartyped event ausgeführt wurde. Hierdurch hat beim input text bei der Suche immer der letzte Buchstabe gefehlt. Also bei Eingabe "Pings" wurde nach "Ping" gesucht. Jetzt wird immer mit dem aktuellen Text gesucht. (61a42f02)

**Comment by copyandexecute** [comment]
Gute arbeit @Greeenman999 kannst du noch coden dass wenn man Pings sucht und dann das s entfernt, man zu Ping kommt?

**Comment by copyandexecute** [comment]
das gleiche auch wenn man wheel eingibt und dann zb wheelsssss dass man bei wheel bleibt

**Comment by Greeenman999** [comment]
Done ✅
