### ISSUE TITLE
[Bug]: Möglicher Key-Error bei Übersetzung

### ISSUE THREAD

**Issue by brentspine** [NoRiskClient/issues#253]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/55391576/332012cc-e415-4ab3-bcfd-3e6ac1e7821d)

Der Key "nrc.generic.errors.cooldown" existiert. Wäre gut, wenn das geprüft wird. Ich füge jetzt erstmal `generic.error` und `generic.errors` hinzu.

![image](https://github.com/NoRiskClient/issues/assets/55391576/b5270363-e50d-4e00-934b-3889544a5762)

### How to reproduce ?

Bild von Hapixh [hier](https://github.com/NoRiskClient/issues/issues/215#issuecomment-2215225530)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by brentspine** [comment]
Siehe:

https://github.com/NoRiskClient/translations/pull/2/commits/9acb97bb63cffb2a8164f207491fcbbeabbb580d
https://github.com/NoRiskClient/translations/pull/3/commits/8c783cdf52569359b9c2b08be7c5cf502edef573

**Comment by SirKnubble** [comment]
Steht 400 davor.
Glaube wenn es Cooldown wäre mit fehlender Übersetzung würde es nur nrc.generic... anzeigen.

**Comment by brentspine** [comment]
> Steht 400 davor.
> Glaube wenn es Cooldown wäre mit fehlender Übersetzung würde es nur nrc.generic... anzeigen.

Ich denke mal das ist der Status-Code von der Request, auch wenn 429 besser passen würde

**Comment by SirKnubble** [comment]
Kommt mit dem Translation Update (oder so, wenn nicht reopen)
