### ISSUE TITLE
Repaly mod close circle = Game Crash 

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#254]
### What happened?

Wenn ich circle-close auswähle, crashed mein Game... Habe schon neue Repalys aufgenommen ect. 

### How to reproduce ?

1. Nehme ein Replay auf
2. Wähle bei den presets circle close 

https://github.com/user-attachments/assets/7516218f-3a9c-461a-93a6-54e93f84a4bc

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/U180xdw
```

**Comment by SirKnubble** [comment]
```
Caused by: java.lang.IllegalArgumentException: Random range is empty: [10.0, 5.0).
```

**Comment by SleepyPxnda** [comment]
@SirKnubble Die Frage ist, ist das ReplayMod oder unser Addon ?

Im Falle von unserem Addon sollten wir da Vorkehrungen treffen, damit das nichtmehr passieren kann ?

**Comment by SirKnubble** [comment]
> @SirKnubble Die Frage ist, ist das ReplayMod oder unser Addon ?
> 
> Im Falle von unserem Addon sollten wir da Vorkehrungen treffen, damit das nichtmehr passieren kann ?

Müsste das Addon sein.
Replay Mod hat ja keine Presets, die sind von @copyandexecute 

Einfach beim Input prüfen, ob der Wert im 2. Feld >= dem 1. Wert ist, sollte das fixed sein.

**Comment by SleepyPxnda** [comment]
alles klar, dann bleibt das offen und @copyandexecute kann das fixen

**Comment by SirKnubble** [comment]
Close, weil easy fix wenn man mal bock hat das zu continuen.
