### ISSUE TITLE
Invite to World" funktioniert nicht via Toast

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#255]
### What happened?

Wenn man in eine Welt invited wird, und auf den Grünen haken clickt passiert nichts.

### How to reproduce ?

1. Lasse dich von einem Freund in deine Welt inviten
2. Versuche nachdem er dich invited hat auf den Grünen Haken zu clicken

https://github.com/user-attachments/assets/340dcada-ed39-44dc-bc12-f681d1488b15

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.3

### Relevant log output

```shell
https://mclo.gs/TjqhJxf
```

**Comment by Alex1607** [comment]
Hey, das ist manchmal etwas Tricky. Die Box für den Haken ist leider etwas weird Versuche Mal bei so einem Toast etwas mit dem Cursor drüber zu hovern bis der hacken seine Farbe leicht ändert. Dann sollte es gehen

Das ist NoRisk und mir auch schon beim testen aufgefallen und ich meine er wollte sich drum kümmern. Das Issue hier sollte ihn aber hoffentlich nochmal dran erinnern :D

**Comment by brentspine** [comment]
Die Übersetzung wurde btw mittlerweile, zumindest in Deutsch und Englisch, hinzugefügt. @Alex1607 weißt du wie es aussieht, wann sich aktiv um die translations gekümmert wird?

**Comment by Alex1607** [comment]
Leider nein @brentspine, da bin ich nicht direkt mit involviert

**Comment by copyandexecute** [comment]
@brentspine bin dran! hab einige bugs gefixed bald stehen übersetzungen an

**Comment by copyandexecute** [comment]
fixed mit nächsten bug
