### ISSUE TITLE
[Bug]: No Searchbar

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#256]
### What happened?

Wenn man ein module auswählt und dann wieder rausgeht kann man nichts mehr in die searchbar eingeben.

![C0D0BA38-C59F-4F0F-BAF4-CD18905959A6](https://github.com/user-attachments/assets/bf816588-aa69-41c4-abe2-a0f0f0042958)

<img width="1934" alt="6D0ABF5B-6741-4B84-BB05-EFB6571670F2" src="https://github.com/user-attachments/assets/29e2a767-6792-4119-affc-c18363c51bfc">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

0.5.2

**Comment by SirKnubble** [comment]
Valid, easy reproduzierbar in beiden Branches.
