### ISSUE TITLE
[FEATURE-REQUEST]: No "back button" in Wheel Actions

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#257]
### What happened?

Es gibt keinen zurück Knopf beim Wheel module , man kann zwar mit esc raus aber ja
<img width="854" alt="10E40D60-E713-41DA-A166-15212634AC75" src="https://github.com/user-attachments/assets/1c7b9057-7717-4ada-97e2-dd9e7ad7938c">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
ist eher ein feature request ig!

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/362c68f4-a4fa-42ef-9621-6626bc4db0d5)
Wheels sind jetzt hier
