### ISSUE TITLE
[Bug]: Capes laden nicht

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#258]
### What happened?

Alltime und Weekly capes laden nicht (zumindest bei mir)

<img width="723" alt="E300514F-7960-4298-AAF2-04BE2E754FEF" src="https://github.com/user-attachments/assets/55564b02-0a43-4e1d-9942-50ec40281c3c">
<img width="727" alt="34DF58E0-0774-430F-AAE0-3EAB9A9228C2" src="https://github.com/user-attachments/assets/0b863a05-389b-4faa-ac72-f26a0be961ef">

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.2

**Comment by SirKnubble** [comment]
Funktioniert. Game darf währenddessen nicht laufen/starten.
> Closed.

**Comment by SleepyPxnda** [comment]
Sollten wir uns evtl doch mal anschauen wieso das so ist ?

@TimLohrer

**Comment by TimLohrer** [comment]
> Sollten wir uns evtl doch mal anschauen wieso das so ist ?
> 
> @TimLohrer 

Big launcher update kocht

**Comment by SleepyPxnda** [comment]
Alles klar, dann close ich das, wenn du das eh auf dem Schirm hast.
