### ISSUE TITLE
[Bug]:NRC capes werden nicht im Cosmetic Tab angezeigt

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#259]
### What happened?

<img width="1277" alt="061FBA1D-3E9B-43BC-8DDF-752E2801CE36" src="https://github.com/user-attachments/assets/108333b4-97af-4cf0-84ed-e032301cdea7">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Fixed
