### ISSUE TITLE
[Bug]: Fix Launcher client log "undefined"

### ISSUE THREAD

**Issue by PSJahn** [NoRiskClient/issues#26]
### What happened?

When the client throws an error whilst launching, the client log simply shows "undefined".

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.2.9

**Comment by TimLohrer** [comment]
Das ist meines wissens nach nur wenn man versucht eine 2. Instanz zu launchen... Sonst gehe die errors da

**Comment by PSJahn** [comment]
> Das ist meines wissens nach nur wenn man versucht eine 2. Instanz zu launchen... Sonst gehe die errors da

Da bin ich mir nicht sicher, der error wird jedoch wenn man den Link kopiert korrekt angezeigt, nur im Launcher nicht

**Comment by TimLohrer** [comment]
danke @Krxwallo ich hatte echt keinen Bock das zu machen lmao
