### ISSUE TITLE
[Bug]: Minecraft capes werden nicht angezeigt

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#260]
### What happened?

Minecraft capes werden in der cosme
<img width="387" alt="55C2FE9C-254E-4DCC-8ADE-27B8AE9B0367" src="https://github.com/user-attachments/assets/e6777261-21a0-4293-bf33-e5d23d838df9">
tic preview nicht angezeigt

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Fixed
