### ISSUE TITLE
[Bug]: Text too long

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#261]
### What happened?

Der Text des Buttons geht über denn rand des buttons hinaus
<img width="980" alt="2B7D905E-5245-4FB2-8CEA-180ADF3FDFEA" src="https://github.com/user-attachments/assets/c14d121d-c078-4826-95d3-a13e57489a21">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by brentspine** [comment]
Hi, könntest du mir sagen bei welchem Modul das ist?

**Comment by MeisterAH** [comment]
hey, es ist bei allen Modules wo man denn Background ändern kann der ganze Text ist "OPTIONS_BACKGROUND"

**Comment by SleepyPxnda** [comment]
Zugriff auf den Code wirst du wahrscheinlich nicht bekommen, ich kann mir das anschauen, sollte da ein Übersetzungskey fehlen

**Comment by brentspine** [comment]
> Zugriff auf den Code wirst du wahrscheinlich nicht bekommen, ich kann mir das anschauen, sollte da ein Übersetzungskey fehlen

Ne sorry ich meinte auf den Client. Genauergesagt einen Zugriffscode im DC

**Comment by SleepyPxnda** [comment]
@brentspine du meinst also Beta Zugriff ?

**Comment by brentspine** [comment]
Ja, habe ich ziemlich komisch formuliert wie ich gerade sehe

**Comment by SleepyPxnda** [comment]
@brentspine Ich glaube, es reicht wenn du die fehlenden Stellen meldest oder per PR in noriskclient/issues reportest. Wir haben gerade genug Beta Leute und Bug Tester ☺️

**Comment by SleepyPxnda** [comment]
Konnte ich jetzt nicht reproduzieren, wenn nochmal auftritt mach nen Issue wieder auf

Danke <3

**Comment by MeisterAH** [comment]
hm also ich habs noch

**Comment by brentspine** [comment]
Such mal jemand im Source Code nach "OPTIONS_BACKGROUND", dann können wir den kompletten Key hinzufügen

**Comment by brentspine** [comment]
Bump

**Comment by copyandexecute** [comment]
hab das einfach removed lol
