### ISSUE TITLE
[FEATURE-REQUEST]: Module outlines editierbar machen

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#262]
### Your idea

Wäre cool wenn man einfach einstrellen könnte das es gar keinen background gibt bei denn modules gibt also ohne outline etc.
![261DB2AE-9700-412C-A91A-FEC2FE1A2B68_4_5005_c](https://github.com/user-attachments/assets/2dbf05f0-9a65-4142-a268-809294e37c69)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
einfach die opacity auf null setzen

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/12d0b7fb-67dc-4f51-b0ea-37e0dff5fc97)
![grafik](https://github.com/user-attachments/assets/fa41b6f7-fc69-4573-85e9-4f3ded09368f)
