### ISSUE TITLE
[Bug]: Module kann doppelt auf dem Screen angezeigt werden

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#263]
### What happened?

Ich kann es leider auch nicht reproduzieren aber iwie hab ich jetzt 2 mal das gleiche module und kann das zweite auch nicht wegdrücken oder verschieben 
![747C10A6-47FD-4BAE-A191-00D5CE1E511B_4_5005_c](https://github.com/user-attachments/assets/d93a692d-b76f-4f18-bdba-d05cfa5f0b10)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by MeisterAH** [comment]
die modules die sich geduplicated haben werden gefreezed. Außerdem ist es mir grad nochmal passiert aber ich kann es trotzdem nicht reproduzieren, weil ich bin nur einem anderem Server gejoint und da war dann noch ein module aber wenn ich nochmal einem anderen server joinen passiert nichts (es ist nicht server spezifisch) 
![A9307C61-7538-4FD9-B2E5-AD4861335DEB_4_5005_c](https://github.com/user-attachments/assets/580c3587-c49b-49e8-adee-7c10d981c605)

**Comment by MeisterAH** [comment]
hatte ein anderer User auch

**Comment by BigBrainRobin29** [comment]
Ja, hier: https://github.com/NoRiskClient/issues/issues/275

**Comment by SleepyPxnda** [comment]
Für den Überblick schließe ich das andere

**Comment by MeisterAH** [comment]
Schritte zum reproducen:
1. ein Module wie FPS etc. auswählen sodas es auf dem Bildschirm angezeigt wird
2. auf die settings des modules gehen und nichts verändern 
3. die settings schließen ohne was zu verändern
credits BigBrainRobin29

**Comment by copyandexecute** [comment]
danke fürs reporten <3

**Comment by MeisterAH** [comment]
ich habs iwie wieder
<img width="377" alt="image" src="https://github.com/user-attachments/assets/81a08de1-5c5f-48f7-a61c-390b15ed95bc">

**Comment by copyandexecute** [comment]
Wie reproducen?

**Comment by MeisterAH** [comment]
Ich weiß nicht bin nur einen Server gejoint. Es ist danach aber auch nicht nochmal passiert.

**Comment by SleepyPxnda** [comment]
@MeisterAH noch aktuell ?

**Comment by MeisterAH** [comment]
ne kann geschlossen werden 👍
