### ISSUE TITLE
[Bug]: Launcher installs wrong mod version

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#265]
### What happened?

Genau das selbe Problem wie hier: https://discord.com/channels/774271756549619722/1252973534112907295/1263914401690288239

Hab nicht viel Ahnung was da passiert, aber hier paar Infos und wie man es reproducen kann. Alles immer mit resettetem Launcher getestet.

Wenn ich bspw. die Entity Culling mod in der norisk-dev Instanz (1.20.4) installiere und danach versuche die selbe Mod in der 1.21 Instanz zu installieren, dann downloaded der Launcher die 1.20.4 Version der Mod und das Spiel kann nicht starten.

1. Es muss eine Featured Mod sein
2. Die Mod muss die gleiche Mod Version in den beiden Instanzen haben (bspw. haben [3D Skin Layers](https://modrinth.com/mod/3dskinlayers) oder [Entity Culling](https://modrinth.com/mod/entityculling) beide die selbe Mod Version für die 1.20.4 und für die 1.21)
3. Der Launcher installiert die falsche Datei, aber bennent sie zu der um, die sie eigentlich hätte runterladen sollen
4. Wenn ich zuerst die Mod in der 1.21 Instanz installiere und danach in der norisk-dev Instanz (1.20.4), dann passiert genau das gleiche andersrum.

Hash von der Mod, wenn ich sie über den Launcher installiere:
![image](https://github.com/user-attachments/assets/b1a27885-2d82-4bd9-b68a-277b04dc490c)

Hash von der Mod, wenn ich sie über Modrinth installiere:
![image](https://github.com/user-attachments/assets/ebee825b-b191-4a29-b72b-cf424049d10b)

### How to reproduce ?

1. 3D Skin Layers über den Launcher zur norisk-dev Instanz (1.20.4) hinzufügen
2. norisk-dev Instanz (1.20.4) einmal starten, damit sich die mod installiert
3. Die selbe Mod in der 1.21 Instanz installieren
4. 1.21 starten

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.2

### Relevant log output

```shell
https://mclo.gs/df56enQ
https://mclo.gs/AIMHhsi
```

**Comment by SirKnubble** [comment]
Kann ich nicht reproduzieren.

**Comment by SleepyPxnda** [comment]
@TimLohrer schau mal

**Comment by copyandexecute** [comment]
@TimLohrer bump
