### ISSUE TITLE
[Bug]: Mods not displayed in profiles

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#267]
### What happened?

Es wird nicht die anzahl der mods angezeigt im profile tab angezeigt wenn man alle mods manuell rein gemacht hat

![50A43281-AA79-4296-B55D-1F7E5A368465_4_5005_c](https://github.com/user-attachments/assets/3c6f4dc9-9556-4be8-94cf-d1c08976ffa4)
<img width="726" alt="BA21CCBE-C899-473B-9DC2-B549B35B8CD7" src="https://github.com/user-attachments/assets/f81af9a0-93c1-4909-874f-9aab457f0260">

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.2

**Comment by copyandexecute** [comment]
Keine ahnung ob man das geil gefixed bekommt

**Comment by TimLohrer** [comment]
> Keine ahnung ob man das geil gefixed bekommt

Kann man, ja, will ich, nein.
