### ISSUE TITLE
[Bug]: Creeperlighting & Whiter Armor incompactible with Freecam

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#268]
### What happened?

die overlays sind inkompatibel mit der Freecam (Modrinth Edition) mod 
![CDE01F55-5AA7-42FB-B9A4-9AC36C14E6BE_1_201_a](https://github.com/user-attachments/assets/5bdf504e-9f5e-4c7d-baad-ad4fb5837cae)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Funktioniert bei mir
