### ISSUE TITLE
[Bug]: Auras fehlen

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#269]
### What happened?

Es gibt keine Auros mehr im shop. Wenn das gewollt ist kann man aber immernoch Auras im Shop suchen
<img width="250" alt="CD587B8F-1F4E-4260-B357-4E65D0B8A6FE" src="https://github.com/user-attachments/assets/dc8201d4-e25d-4b96-9ded-3da9724130fc">

### Where is this happening?

Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by SleepyPxnda** [comment]
Da müssen wir glaube einfach schauen. Auras sind glaube ich geplant nur aktuell keine drinne.
Ich würde das schließen.
