### ISSUE TITLE
[Bug]: low resolution Stack. texture

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#270]
### What happened?

![465ABF6A-DF26-46FD-B681-50C1176C1274_1_201_a](https://github.com/user-attachments/assets/cde6c998-991a-4aa1-9b30-f4dc9348a9f4)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by SleepyPxnda** [comment]
@MeisterAH Was ist hier das Problem ?

**Comment by MeisterAH** [comment]
es war doch hoch auflösender mal oder?

**Comment by SleepyPxnda** [comment]
Keine Ahnung

**Comment by copyandexecute** [comment]
@PSJahn könntest du da mal bitte reingucken?

**Comment by PSJahn** [comment]
Soweit ich weiß war das ein random bug der ab und zu auftauchte und ehrlich gesagt bin ich mir auch nicht hunderprozentig sicher, was das ganze auslösen könnte, eventuell wieder mal sodium o.Ä., denn eigentlich ist solches texture filtering nicht standard mc feature was es also eigentlich unmöglich macht, dass das überhaut passiert
