### ISSUE TITLE
[Bug]: TNT Timer doesn't work

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#274]
### What happened?

Auch wenn ich das TNT Timer module an habe wird kein Timer über dem TNT angezeigt
![96B6B96F-070C-4C4E-A901-7BEB133FADA0_1_201_a](https://github.com/user-attachments/assets/25b62a80-f346-4aa3-b75f-e8af4c2dec8e)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by 0x3C50** [comment]
Fixed in a8af0e42
@copyandexecute kann geschlossen werden
