### ISSUE TITLE
[Bug]: Double Icon

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#276]
### What happened?

![0A838CE9-2482-4371-8A42-DD58351257A0_4_5005_c](https://github.com/user-attachments/assets/5d48a69d-b529-4550-a502-c98cd9b7a109)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
welche icon einstellung hast du ausgewählt?

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/80aad282-2c58-4d5b-91b5-eae365f51b69)
bin dran

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/e8cdf6e1-b969-44a2-9c21-dae50900baa2)
