### ISSUE TITLE
[Bug]: Blurry Icons

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#277]
### What happened?

Wenn man bei einem Module wo man denn Background einstellen kann "OPTION_BACKGROUND" auswählt werden auch die Icons geblured
![F0401BF6-9DEA-4E97-A4EF-CBAC20BBDA83_4_5005_c](https://github.com/user-attachments/assets/523df18b-1a5c-46f9-a10c-dc819bb15407)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by 0x3C50** [comment]
Gefixt in b6f2ff5b
