### ISSUE TITLE
[Bug]: Launcher Skin Face Image not available

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#28]
### What happened?

Well man sich abmeldet wird kein Skin gerendert

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

### Version (for launcher bugs)

0.2.9

**Comment by mcshept** [comment]
Kleine Anmerkung dazu. Wenn der Skin mehrere Layers hat, wird beim Face nur der erste Layer gerendert.

**Comment by TimLohrer** [comment]
> Kleine Anmerkung dazu. Wenn der Skin mehrere Layers hat, wird beim Face nur der erste Layer gerendert.

Ja ik, aber das ist leider auch nicht ganz so einfach... ich werd's versuchen
