### ISSUE TITLE
Blur Mod fehlt in der 1.21

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#280]
https://github.com/user-attachments/assets/22a6bb38-5a7f-4833-94d2-565d9cd057ae

### What happened?

Normalerweise gab es doch die Blur mod, um Menu Blur ein/ aus zu schalte. Diese Fehlt in der 1.21 Irgendwie 

### How to reproduce ?

1. Client in der 1.21 öffnen
2. Nach Blur suchen 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.6

### Branch (for client bugs)

1.21

### Relevant log output

```shell
https://mclo.gs/GC94ME6
```

**Comment by copyandexecute** [comment]
Yes, habe die Blur mod komplett entfernt weil die jetzt in vanilla 1.21 eingebaut wurde
