### ISSUE TITLE
[BUG]: NoRisk Kopf wird überall angezeigt. 

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#283]
### What happened?

Wenn man auf Servern seinen eigenen Kopf in der Hotbar haben solte, wird der von NoRisk angezeigt. Zudem  wird der Kopf von NoRisk angezeigt, wenn man Blöcke Pingt. (NoRisk weiß anscheinend bescheid) https://discord.com/channels/774271756549619722/1265037248534155335

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

None

**Comment by SleepyPxnda** [comment]
Fixed
