### ISSUE TITLE
[Bug]: Enchanting Glint wird nicht angezeigt als Vorschau

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#284]
### What happened?

Das Enchanting glint Cosmetic wird in der Preview nicht angezeigt
<img width="1275" alt="DA8E1936-2B1B-4211-A375-810E1A3F01E1" src="https://github.com/user-attachments/assets/29f4a87f-391c-4223-90db-6d9cdae4a395">

### Where is this happening?

Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/3917f6cd-aa89-4fef-a1ec-ba97fc87faa7)
 besser als das wirds nicht
