### ISSUE TITLE
[Bug]: Falsch Farbe

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#285]
### What happened?

Ka wie das ding nochmal heißt aber wenn man das ganz runter stellt also damit es durchsichtig wird dann ist es einf rot aber wenn man dann wieder esc drückt um wieder ins spiel zu gehen ist dann auch durchsichtig
<i
![4811A027-5E16-46E0-A63F-528CCEE28310_4_5005_c](https://github.com/user-attachments/assets/e5da6e20-cdf0-4b15-b914-989d0d44ee59)

sry für diese schlechte Formulierung

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

0.5.2

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
ist gewollt, das ist die border
