### ISSUE TITLE
[Bug]: Einladungen annehmen während man im Game ist

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#286]
### What happened?

Wenn man ein game gerade gestartet hat kann man auch eine andere Einladung akzeptieren
![22B338B3-66A7-48C4-AA7C-D49B81205183_1_201_a](https://github.com/user-attachments/assets/ae2a08e8-3ec6-4391-a377-0907812a4914)

### How to reproduce ?

1. eine Einladung an jemanden senden
2. der andere muss auch eine Einladung schicken 
3. der andere muss deine Einladung akzeptieren und dabei die Einladung des anderen akzeptieren

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

0.5.2

### Branch (for client bugs)

1.21

**Comment by SleepyPxnda** [comment]
Also einerseits witziges Ding 2 Games gleichzeitig zu spielen.
Andererseits ist das dann noch bisschen verbuggt

@copyandexecute mach wie du denkst 😆

**Comment by copyandexecute** [comment]
ist intended, man soll ja mehrere gleichzeitig fighten können wegen aufmerksamkeitsspanne
