### ISSUE TITLE
[Bug]: SlimeOverlay ist komplett Grün

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#293]
### What happened?

![grafik](https://github.com/user-attachments/assets/57a4a484-42a1-405c-93f6-bc20fdad1bd2)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by SleepyPxnda** [comment]
Ah du meinst, dass es nicht wie ein Schleim aussieht ?
