### ISSUE TITLE
[Bug]: Man kann unsichtbare Entitys mit dem Wheel auswählen

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#294]
### What happened?

Man kann wenn man z.B. eine Invisibility Potion auf ein Mob wirft, es trotzdem noch über das Wheel auswählen
![2024-07-28_19 59 11](https://github.com/user-attachments/assets/afda7a18-cb40-45ec-ad3d-c1df31644e12)

### How to reproduce ?

1. Invisibility Potion auf ein Mob
2. Chat öffnen
3. Mob auswählen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by Hapixh** [comment]
Yo, das stimmt so!
