### ISSUE TITLE
[Bug]: Game läuft ohne spieler

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#296]
### What happened?

Wenn man TicTacToe etc. auswählt und mit jemanden spielt und der partner sich aber während des Matches ausloggt geht das Game weiter obwohl der spieler nicht mehr online ist

### How to reproduce ?

1. Mitspieler inviten zu einem Multiplayer minigame
2. Mitspieler muss während des Games leften

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by SleepyPxnda** [comment]
Konnte ich nicht reproduzieren

**Comment by SleepyPxnda** [comment]
Nvmd is nen Bug
Hinweis hier aber: Der MITSPIELER muss leaven, nicht der Spiel-Ersteller. Beim Ersteller wird das Spiel richtig beendet.

**Comment by copyandexecute** [comment]
Ich kanns nicht reproduzieren also lokal nicht, gucke gleich mal ingame

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/fac42b14-6709-423d-b3e8-9d8ac0389c9f)
konnte es nicht reproduzieren
