### ISSUE TITLE
[FEATURE-REQUEST]: Respect Window sizes for modules

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#297]
### Your idea

Modules wie Fps etc. sollten immer da bleiben wo sie sind 
erstes video NRC:
https://youtu.be/Uc6Be9BwGaU

Beispiel Lunar Client:
https://youtu.be/qwsgoT_RiU0

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
bin dran

**Comment by copyandexecute** [comment]
https://gyazo.com/559615e0fc02432548a5feb78bedada2

**Comment by MeisterAH** [comment]
joa fast https://imgur.com/a/DRR6uHN

**Comment by copyandexecute** [comment]
Jetzt sollte es aber echt gefixed sein
