### ISSUE TITLE
[FEATURE-REQUEST]: "Cleaner" Wheel

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#298]
### Your idea

ich finde das dass früherer Wheel sehr viel aufgeräumter wirkt imo.

altes Wheel:
![image](https://github.com/user-attachments/assets/9fedece9-233c-41bd-a6a6-b6207d606411)

neues Wheel:
![image](https://github.com/user-attachments/assets/cd9de2e2-922a-43e2-9045-128186d782f3)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/b0a811d5-1c30-4e3e-8146-dcfb154326ee)
Hab ich so halb hinzugefügt @MeisterAH passt das fürs erste?
Müsste noch coden wenn man zu viele hat, dass die nicht am Boden sind aber sonst erstmal okay oder
