### ISSUE TITLE
[Bug]: Game schließt nicht

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#306]
### What happened?

Wenn man tictactoe gegen den Computer spielt und dann auf rematch klickt schließt sich das spiel nicht obwohl ein cooldown angzeigt wird 
<img width="443" alt="image" src="https://github.com/user-attachments/assets/a4d82bed-55cd-42e8-baa2-3fa7e5741c11">

### How to reproduce ?

1. tictactoe gegen den bot spielen
2. nach dem spiel auf rematch klicken

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
Nicht mehr valid oder?
