### ISSUE TITLE
[FEATURE-REQUEST]: Rematch button für pong

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#308]
### Your idea

Es fehlt der rematch button für pong wenn man gegen denn Computer spielt

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/f6d81d32-2c9e-4d1a-a4d6-dd65482c69ab)
