### ISSUE TITLE
[FEATURE-REQUEST]: infinite scrolling 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#309]
### Your idea

Wäre sehr nice wenn man durch das Mod menu unendlich scrollen könnte also dass es dann nicht bei Motion blur stoppt sondern durchläuft also es dann bei tictactoe ankommt.
<img width="1823" alt="image" src="https://github.com/user-attachments/assets/d929e5fa-1d61-40c6-a42c-a2441e162678">

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
ich kann dir coden dass man dann zum anderen ende springt aber so infinite infinite geht leider nicht
