### ISSUE TITLE
[Bug]: pivot point incorrect if cosmetic is offsetted

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#31]
### What happened?

Wenn man ein offset einstellt stimmt der pivot point beim rotieren vom z.B. Kopf nicht mehr

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Passiert auch, wenn man es mit dem feature auf der x bzw y achse im cosmetic gui verscheibt

**Comment by copyandexecute** [comment]
das könnte alles fixen
