### ISSUE TITLE
[FEATURE-REQUEST]: Bigger scroll button 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#310]
### Your idea

Grade ist bisschen umständlich den Button zu treffen oder einf ein skill issue
![C92FDEEB-1A8A-485E-BED0-0CBFA21AB388](https://github.com/user-attachments/assets/d6b6b52a-7934-44b5-8900-cd56c89a1ea5)

### Where would this be applied?

Client, Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@TimLohrer meinung?

**Comment by TimLohrer** [comment]
> [@TimLohrer](https://github.com/TimLohrer) meinung?

check in dem Fall, mache bissl dicker ok?
