### ISSUE TITLE
[Bug]: Gepingte Blöcke werden nicht richtig angezeigt

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#312]
### What happened?

https://www.youtube.com/watch?v=-BXC5WxPGA8

Wie man sehen kann sind die Pings sehr verbuggt. Sowohl im Singleplayer als auch im Multiplayer. Manchmal wird der falsche Block gepingt, manchmal wird der Block nicht angezeigt. Alles sehr komisch.

### How to reproduce ?

Pings testen

https://www.youtube.com/watch?v=-BXC5WxPGA8

In der 1.20.4 und auch in der 1.21 existiert der Bug. (Man kann 1.20.4 auf Github btw nicht selecten)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
Oh sorry, update kommt natürlich erst wenn ich es im discord geposted habe my bad!
