### ISSUE TITLE
[FEATURE-REQUEST]: Warenkorb

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#316]
### What happened?

Die Preise die bei den Cosmeitcs angezeigt werden, stimmen nicht mit den Richtigen Preisen überein. 

### Where is this happening?

Uploading 0806(1).mp4…

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

2.0.6

### Branch (for client bugs)

None

**Comment by copyandexecute** [comment]
hi kannst du das bild bitte posten?

**Comment by SleepyPxnda** [comment]
Ne Hapixh war nur inkompetent. 
Hat aber auf das Problem aufmerksam gemacht, dass der Preis sehr unintuitiv ist.

Vllt aber ne Idee, das irgendwie zu markieren, dass man alle ausgewählten Cosmetics kauft. Hier hatte @Hapixh die Idee eines Warenkorbs ?

 @copyandexecute da irgendeine Idee ?

**Comment by copyandexecute** [comment]
noch bedarf?
