### ISSUE TITLE
[Bug]: MC-Real Server IP wird immer angezeigt

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#319]
### What happened?

Egal ob Hacken gesetzt oder nicht, IP wird immer ans MC-Real drangehängt

### How to reproduce ?

1. Screenshot
2. MCReal hochladen
3. "IP anzeigen" nicht anhacken
4. Post anschauen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by 0x3C50** [comment]
gefixt in d297baba
