### ISSUE TITLE
[FEATURE-REQUEST]: rank system

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#32]
### Your idea

Rank system (z.B Admin, Helper, Vip, Designer)

+ norisk icon neben nametag ist immernoch kaputt und sollte je nach rank anders aussehen

### Where would this be applied?

Client, Backend

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Hallo github wieso werden meine links nicht angezeigt

**Comment by copyandexecute** [comment]
![Uploading grafik.png…]()
nur noch backend testen

**Comment by copyandexecute** [comment]
Sooo Icons sollten korrekt gerendert werden, was mach noch adden muss ist iwie dass man Ränge vergeben kann + die jeweiligen icons für die Ränge + Ränge in die Constants adden

**Comment by copyandexecute** [comment]
ansonsten müsste man es nur testen

**Comment by copyandexecute** [comment]
Kann man closen oder?
