### ISSUE TITLE
[Bug]: Pong laggt bei Wandberührungen zurück

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#320]
### What happened?

Runde Pong starten
Ball bei einer Wandberührung beobachten

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
Das ist ein klassischer wont fix
