### ISSUE TITLE
[Bug]: Custom Capes müssen bei jedem Spielstart neu ausgewählt werden

### ISSUE THREAD

**Issue by SleepyPxnda** [NoRiskClient/issues#321]
### What happened?

Ja custom capes sind halt immer basic wenn ich das Spiel start

### How to reproduce ?

1. Client starten
2. Custom Cape auswählen
3. Client schließen
4. Client starten
5. Custom Cape in Cosmetics ist wieder standard

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
Worüber custom cape auswählen, über launcher?

**Comment by SleepyPxnda** [comment]
Jap

**Comment by copyandexecute** [comment]
@TimLohrer ich code hier noch dass das cape im outfit bleibt auch wenn nicht ausgewählt!

**Comment by copyandexecute** [comment]
https://gyazo.com/12727fb3805a2ec878d849d3ab1ad1a4
