### ISSUE TITLE
[Bug]: Capes im launcher buggen

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#322]
### What happened?

Es wird das komplette cape template glaube ich angezeigt wenn darüber hovered 
<img width="722" alt="image" src="https://github.com/user-attachments/assets/8c6017ed-6eef-4253-ae19-4e783f536cd9">

### How to reproduce ?

1. open launcher
2. go to capes
3. auf weekly capes oder all time capes klicken
4. über das cape hovern

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.6

### Branch (for client bugs)

None

**Comment by copyandexecute** [comment]
Kann ich nicht reproducen, @TimLohrer maybe macos error, guckst du rein?

**Comment by TimLohrer** [comment]
> Kann ich nicht reproducen, @TimLohrer maybe macos error, guckst du rein? 

Mache ich ab dem 16. <3

**Comment by copyandexecute** [comment]
Liegt an MacOs, hatte das heute auch, @TimLohrer

**Comment by TimLohrer** [comment]
> Liegt an MacOs, hatte das heute auch, [@TimLohrer](https://github.com/TimLohrer)

Alr, wird angeschaut Chef o7

**Comment by TimLohrer** [comment]
@copyandexecute Bin auf MacOS und kann nt reproduzieren

**Comment by TimLohrer** [comment]
Auf jeden Fall in meinem branch nicht

**Comment by TimLohrer** [comment]
Oh, das as auch schon alte launcher version
denke das is schon gone oder?

**Comment by MeisterAH** [comment]
ne ist immer noch so

**Comment by TimLohrer** [comment]
@copyandexecute schaut sich das mal an, bei mir passiert das iwie einfach nt 🤷‍♂

**Comment by copyandexecute** [comment]
Ist bei mir auch so, aber Tim kann nicht reproducen, deswegen guck ich mal rein

**Comment by copyandexecute** [comment]
<img width="621" alt="image" src="https://github.com/user-attachments/assets/13c1cbee-7352-4b9e-a01c-6af6b2c4ded7">

**Comment by copyandexecute** [comment]
fixed mit nächsten update @TimLohrer guck mal ob jetzt bei dir alles geht lol

**Comment by MeisterAH** [comment]
ist das in der launcher version 0.5.11 schon drin, weil ich habe den bug noch. Tatsächlich kommt aber der bug jetzt erst, wenn man über das cape hovered ![Image](https://github.com/user-attachments/assets/a413a679-5936-4406-97a4-7bc80691ac6f)
