### ISSUE TITLE
[Bug]: No Searchbar

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#324]
### What happened?

Die Searchbar verschwindet wenn man ein Module bewegt 

### How to reproduce ?

1. Mod menu öffnen
2. ein module bewegen 
3. die searchbar suchen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/e3477e8e-9f4d-4245-acf5-be688cacf7b6)

**Comment by copyandexecute** [comment]
Reworked man kann jeztt immer suchen und tippen
