### ISSUE TITLE
[Bug]: Friendlist scrollen funtkioniert nicht

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#327]
### What happened?

In der Friendlist kann man nicht runterscrollen

### How to reproduce ?

1. Freunde suchen xD
2. Friendlist öffnen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by TigerCrafter** [comment]
Jetzt geht es wieder

**Comment by TigerCrafter** [comment]
Wenn man 15 (vielleicht auch mehr) Freunde auf GUI Scale 4 hat, kann man noch immer nicht scrollen bei GUI Scale 5 geht es aber.

**Comment by copyandexecute** [comment]
cant reproduce bump :(

**Comment by copyandexecute** [comment]
nächstes update hat mehr padding vlt hilft das
