### ISSUE TITLE
[Bug]: Keystrokes unsichtbar

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#328]
### What happened?

Unter der Uhr oben links sollten eigentlich die Keystrokes sein
![grafik](https://github.com/user-attachments/assets/a5047a7b-aa13-444b-bdeb-684564b331f3)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Branch (for client bugs)

1.21

**Comment by 0x3C50** [comment]
![Image](https://github.com/user-attachments/assets/ab0243ca-57c7-4ae5-a44b-dccac381229e)

gefixt, mit dem dümmsten fix ever
