### ISSUE TITLE
[Bug]: Pong spectate Bug

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#329]
### How to reproduce ?

Wenn man einem Pong-Game zuschaut, steht dort durchgehend "Game starts in 3..." und sobald man es schließt, öffnet es sich neu aber es ist eingefroren.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
fixed
