### ISSUE TITLE
[Bug]: Cosmetics shadows / light bugs

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#33]
### What happened?

![Image](https://github.com/NoRiskClient/issues/assets/55639047/e6b22418-76c6-488a-a206-e19ed65c0fad)

![Image](https://github.com/NoRiskClient/issues/assets/55639047/5bac3512-e914-4683-adac-5d8ca6571c80)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Hab mal im owo lib discord gefragt
