### ISSUE TITLE
[FEATURE-REQUEST]: Hotbar Scrolling während dem moven von Minigames deaktivieren

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#330]
### Your idea

Während man Minigames mit dem Mausrad nach hinten/vorne verschiebt, sollte das Hotbar scrolling deaktiviert werden.

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
habs jetzt ohne setting gemacht, falls das jemand will dann melden...
