### ISSUE TITLE
[Bug]: No skin

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#331]
### How to reproduce ?

Der Skin wird nicht geladen wenn man beim launcher auf skin geht.
<img width="721" alt="image" src="https://github.com/user-attachments/assets/3c2e22f5-cc17-4579-a051-a0a33a0dfb4e">

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.6

**Comment by SleepyPxnda** [comment]
@MeisterAH ist das noch aktuell ?

**Comment by MeisterAH** [comment]
kann ich grad nicht nach schauen sag ich dir wenn ich wieder zurück bin

**Comment by MeisterAH** [comment]
ist btw immernoch so es wird nur das cape geladen, aber nicht der skin

**Comment by copyandexecute** [comment]
@TimLohrer

**Comment by copyandexecute** [comment]
@MeisterAH ist noch immer so? und wie kann man das reproduzieren

**Comment by MeisterAH** [comment]
jup is noch so, einf launcher öffnen und skin tab öffnen

**Comment by TimLohrer** [comment]
Somehow is das nur auf macos so :(

**Comment by TimLohrer** [comment]
Ok, ich glaube es liegt daran, aber müssen wir beim nächsten launcher update schauen, wenn ich npm run tauri dev mache gehts 🙃![Image](https://github.com/user-attachments/assets/590a67dc-85ed-4201-8dda-5508acda17c1)

**Comment by TimLohrer** [comment]
Bitte offen lassen bis confirmed! Können wir erst nach dem nächsten update testen!

**Comment by MeisterAH** [comment]
also in der 0.5.11 ist das bei mir noch immer so :(
