### ISSUE TITLE
[Bug]: Resource Pack/Mod Name too long

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#332]
### How to reproduce ?

wenn die Namen/beschreibung der tps/mods zu lang sind überlappen sie sich 

<img width="529" alt="image" src="https://github.com/user-attachments/assets/5bd6ebe6-a711-4ac0-9a55-bfb6a069828d">

Beispiel:
In der Resource Pack Suchleiste "sta" eingeben

### Where is this happening?

Client, Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.6

**Comment by copyandexecute** [comment]
@TimLohrer bekommste den hin oder @SirKnubble
