### ISSUE TITLE
[FEATURE-REQUEST]: Automatic back

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#333]
### Your idea

Wäre nice wenn es nachdem es 100% beim launchen erreicht hat dann nach ner minute oderso automatisch wieder zum main screen zurück geht 
<img width="723" alt="image" src="https://github.com/user-attachments/assets/241297b1-95a3-4e2e-8710-a9afb9521ac0">

### Where would this be applied?

Client, Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by SirKnubble** [comment]
+ Wenn man auf den Head klickt und der Client läuft der dir nicht nen Error gibt sondern wieder zu dem Screen wie im Screenshot geht.
