### ISSUE TITLE
[Feature Request X Bug]: Module HUD Rework

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#334]
### How to reproduce ?

Ich habe die Größe der FPS und CPS Modules geändert und auf einmal ist das passiert. (Siehe Bild)
![2024-08-10_21 44 20](https://github.com/user-attachments/assets/9b61f4d9-428b-4806-b02a-c33da50f18ff)

(Rechts oben)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Bekannt

**Comment by copyandexecute** [comment]
# Hud Polishing

- [ ] Module Skalieren über Button unten rechts am Hud Module
- [ ] "Demo Module" coden, usecase: ArmorStatus dass da dummy rüstung gerendert wird damit man weiß wie man es anordnen muss
- [ ] HUD Snapping
- [ ] Multi Select

**Comment by copyandexecute** [comment]
https://github.com/user-attachments/assets/79d4eb74-765b-47b5-831d-85f5872f408a

**Comment by 0x3C50** [comment]
> # Hud Polishing
> 
>     * [x]  Module Skalieren über Button unten rechts am Hud Module
> 
>     * [x]  "Demo Module" coden, usecase: ArmorStatus dass da dummy rüstung gerendert wird damit man weiß wie man es anordnen muss
> 
>     * [ ]  HUD Snapping
> 
>     * [ ]  Multi Select


https://github.com/user-attachments/assets/dd2a926b-5958-42bf-a062-dc107b643ef7

https://github.com/user-attachments/assets/01108d0c-13ec-44e6-bf90-22ec5281ad17

**Comment by TigerCrafter** [comment]
Wenn man ein Modul an den Rand zieht, dann loslässt und nochmehr an den Rand zieht, muss man, wenn man es wieder vom Rand weghaben will den ganzen Weg wieder mit der Maus zurück (Vielleicht erkennt mans am Video nicht so gut)

https://github.com/user-attachments/assets/aaa50c11-0a57-4f96-b1f8-0b0d48a6e71d
