### ISSUE TITLE
[Bug]: capes im Shop verbuggt

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#335]
### How to reproduce ?

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/f23fe6c5-fdf1-42db-86c3-d59535a4629e">

### Where is this happening?

Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
How to reproduce ?

**Comment by MeisterAH** [comment]
einfach in denn cosmetic shop gehen

**Comment by MeisterAH** [comment]
ok nvm problem hat sich in luft aufgelöst 🥰
