### ISSUE TITLE
[Bug]: Player Head Spam Bug

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#336]
### How to reproduce ?

Wenn man auf den Player Head spammt (wenn der Client noch nicht offen ist), kommt der Bug, wo man scrollen kann und auch manchmal der "Not Whitelisted" Bug

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.6

**Comment by MeisterAH** [comment]
jo ist bei mir auch so

**Comment by TigerCrafter** [comment]
Ich kenne mich da nicht aus, aber kann man nicht einfach einen "Cooldown" für die runClient function einbauen?

**Comment by SirKnubble** [comment]
> Ich kenne mich da nicht aus, aber kann man nicht einfach einen "Cooldown" für die runClient function einbauen?

Bin dran

**Comment by SirKnubble** [comment]
Fixed
