### ISSUE TITLE
[Bug]: TOKEN REFRESH BUG multiple devices

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#337]
### How to reproduce ?

wenn man eine branch startet wird der norisktoken aktualisiert [Gerät 1]
wenn man den launcher startet ist noch der alte norisktoken gespeichert und deswegen wird ein error geworfen [Gerät2]

Fix:
Man checkt ob NoRiskToken valid ist ->
Man checkt vorher ob der Mc Token gültig ist, wenn ja -> NoRisk Token Refreshen 
wenn nein -> Mc Token Refreshen und dann NRC Token refreshen

checki checki check?

![grafik](https://github.com/user-attachments/assets/292851b9-6c63-4b10-afc4-9ed0c344b817)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@TimLohrer kannst du das dann bitte nach deinem urlaub machen? :3 wenn was unklar ist hit me up

**Comment by TimLohrer** [comment]
> @TimLohrer kannst du das dann bitte nach deinem urlaub machen? :3 wenn was unklar ist hit me up

Ich versuchs... Prob erst in so 1,5 Wochen.. sry

**Comment by copyandexecute** [comment]
Sheesh

**Comment by copyandexecute** [comment]
Dann geh ich wohl ran

**Comment by copyandexecute** [comment]
obwohl ne da kracht es gewaltig, das ballert

**Comment by copyandexecute** [comment]
UPDATE IST RAUS
