### ISSUE TITLE
[Bug]: TicTacToe gegen sich selbst

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#338]
### How to reproduce ?

das ist ig ein feature aber wenn man nachdem match das man gegen sich spielt dann auf rematch klickt dann schließt sich das fenster nicht außerdem ist man immer das kreuz.
![4FDB5F55-97CB-44F8-A2AD-D7DECD263072_1_201_a](https://github.com/user-attachments/assets/c25ba7af-ff48-4739-ae32-9b9325e81d37)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
So ein halber duplicate von https://github.com/NoRiskClient/issues/issues/403 wird gefixed

**Comment by copyandexecute** [comment]
fixed mit nächstem release
