### ISSUE TITLE
[Bug]: Mehrere mcreals Kommentare auf einmal 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#339]
### How to reproduce ?

Man kann den Kommentar Button mehr mals drücken ohne einen kommentar zu schreiben 
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/e94d1b61-28f6-4a24-8a39-d58396608a8c">

schritte zum reproduzieren:
1. mcreal machen
2. mcreal menu öffnen und auf das eigene mcreal (oder von jemand anderem) den kommentar button spammen

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Fixed
