### ISSUE TITLE
[FEATURE-REQUEST]: Dev Mode im Launcher

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#34]
### Your idea

Ich kaufe aktuell 2 Server einen für Production und Dev damit in zukunft keine Sachen kaputt gehen bzw alles was im Dev Mode passiert auf eigene gefahr ist.

Will deswegen in den Settings ein "Dev Mode" häkchen haben was auch bewirkt dass eine Java Flag gesetzt wird + alle API calls mit "dev." starten 

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
Hättest du Lust das zu machen @TimLohrer ? wäre wichtig ganz wichtig für die Zukunft damit der Schaden immer minimal bleibt

**Comment by TimLohrer** [comment]
> Hättest du Lust das zu machen @TimLohrer ? wäre wichtig ganz wichtig für die Zukunft damit der Schaden immer minimal bleibt

Ja

**Comment by copyandexecute** [comment]
Ne ich glaub actually nicht oder? Also höchsten wenn du noch "D" davor packst aber rt keine ahnung ich habs wie gesagt anders gemacht muss man mal testen

**Comment by copyandexecute** [comment]
Folgende Sachen fehlen noch für funktionierenden Dev Mode:

Die System.getProperty() richtig setzen im launcher und benennen (das hat glaube @TimLohrer schon gemacht aber keinen commit hier drauf verwiesen)

Wir müssen im launcher gucken ob der dev/experimental mode aktiviert ist und da alle APIs anpassen (api-staging)

Die Apis habe ich teilweise in die Mods bereits angepasst wie folgt:
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/1d1a44ef-0fab-44aa-ac29-03099284f8b0)

Dann müssten wir einen Dev Token einführen weil ja eine andere NoRisk User Database mit anderen Token verwendet wird...
der Token muss irgendwo gespeichert werden und jemand muss moozii anschreiben dass die url korrekt umgeleitet wird

und das wars? odeeer vergess ich was ne oder

**Comment by copyandexecute** [comment]
Hab moozi angeschrieben dass er eine weitere URl adden soll ✔️
