### ISSUE TITLE
[Bug]: zoom bug

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#340]
### How to reproduce ?

Wenn man stirbt und dabei zoomt dann zoomt man immernoch nachdem man respawned ist.

schritte. zum reproduzieren:
1. zoom module aktivieren
2. sterben und dabei zoomen
3. respawnen (nicht mehr zoom key drücken)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TigerCrafter** [comment]
Ist auch, wenn man einen Server verlässt. Hat aber glaube ich nicht so hohe Priorität.

**Comment by copyandexecute** [comment]
Grüner Mann du schaffst das
