### ISSUE TITLE
[Bug]: Fehlermeldungen in Launcher

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#343]
### How to reproduce ?

1. Starte den Launcher
2. Starte den Client (Bis dort steht 100% Launching)
3. Starte den Launcher neu (Oder drücke STRG+R)
4. Drücke auf den Player Head
Wenn bei Schritt Vier nur die Fehlermeldung kommt: "Error launching Minecraft: client is already running" dann einfach nochmal auf den Player Head klicken

(Hat vielleicht was mit #336 zu tun)

Original posted by nightrx_1: https://discord.com/channels/774271756549619722/1272846575085031515/1272846575085031515

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.6

**Comment by TimLohrer** [comment]
@TigerCrafter was geanu passiert da? Also was ist das unerwartete Verhalten?

**Comment by TigerCrafter** [comment]
> @TigerCrafter was geanu passiert da? Also was ist das unerwartete Verhalten?

Die Fehlermeldungen. Also nicht nur die Fehlermeldung dass das Game schon läuft. Man wird halt vollgespammt. Und habe es glaube ich reportet, als dadurch noch der Scroll Bug gekommen ist. Ich glaube es kommt auch "Not Whitelisted" manchmal

**Comment by TimLohrer** [comment]
Sollte schon fixed sein, @copyandexecute das war das wegem neuen token beim start, aber is nt mehr oder?

**Comment by TimLohrer** [comment]
Kann ich nt reproducen

**Comment by TimLohrer** [comment]
Info, enrico hat ausversehen linked
das is nt fixed
