### ISSUE TITLE
[FEATURE-REQUEST]: Disable Edge Rightclick Menu

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#344]
### Your idea

Man sollte das Rechtsklick-Menü im Launcher deaktivieren. Das ist durch hinzufügen des Codes: `addEventListener("contextmenu", (e) => {
    e.preventDefault();
  });` in der noriskclient-launcher\scr\main.js möglich

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows

**Comment by TimLohrer** [comment]
Kommt mit @SirKnubble branch merge
