### ISSUE TITLE
[Bug]: update problem

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#345]
### How to reproduce ?

beim norisk client können keine neuen updates mehr heruntergeaden werden das ist schade den so kann ich die neuen sachen ab den neuen spielen nicht spielen also habe ich nur flappy bird und as andere spiel!

um es klarr zumachen es stet nur screat fpr updates aber es passirt nichts !

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by MeisterAH** [comment]
hi, könntest du vielleicht deine Logs schicken und einen screenshot vom launcher?

**Comment by TigerCrafter** [comment]
Hi erstmal. Eigentlich sollte es über die Pfeile links und rechts von "NoRisk-Dev Version" änderbar sein. Könntest du uns bitte einen Screenshot von deinem Problem schicken, damit wir es besser verstehen könenn 😊

**Comment by McCram12** [comment]
Also ich habe keine Fehler bekommen aber so lange ich warte steht ja nur suche nach abdate und ich kann auch keine Version wechseln ich habe nur die die norisk dev version

**Comment by TigerCrafter** [comment]
Danke für deine Antwort! Könntest du mir bitte einen Screenshot von deinem Problem schicken, damit ich besser verstehen kann, was du meinst.

**Comment by McCram12** [comment]
Das kann ich machen aber erst nachher aber helfen wird es nicht ist einfach nur der Launcher mit der Schrift suche nach Updates und mehr nicht ich bekomme nur das Update nicht

**Comment by MeisterAH** [comment]
hey, könntest du uns deine latest.log schicken weil, anscheinend funktioniert der auto updater nicht richtig bei dir. Hast du irgendwelche Antiviren programme die das vielleicht blockieren könnten @McCram12 ?

**Comment by TigerCrafter** [comment]
Wenn es nicht funktioniert probiere, das Setup von GitHub.com/NoRiskClient/noriskclient-launcher/releases runter zu laden

**Comment by TigerCrafter** [comment]
> hey, könntest du uns deine latest.log schicken weil, anscheinend funktioniert der auto updater nicht richtig bei dir. Hast du irgendwelche Antiviren programme die das vielleicht blockieren könnten @McCram12 ?

Ich glaube eigentlich, dass auch eine ältere Version neuere Branches detected sollte

**Comment by McCram12** [comment]
es geht wieder hate eine ältere version vom launcher
