### ISSUE TITLE
[FEATURE-REQUEST]: Custom Mods erkennen

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#346]
### Your idea

Wenn man eine Mod selber in denn Client macht dann werden erstens nicht die Icons davon geladen und man kann sich die gleiche Mod nochmal herunterladen. Wäre nice wenn man das irgendwie fixen könnte.

Hier zum Beispiel mit der Mod Visuality:
<img width="717" alt="785B171E-494E-4EBC-B654-8588D48868C5" src="https://github.com/user-attachments/assets/570cd024-0f89-424a-b089-f5ce245bc14e">
<img width="721" alt="02047F05-2FA5-419E-937D-C38F3C25F8B8" src="https://github.com/user-attachments/assets/b4b24a24-c2e9-452d-b42a-4dbc21478b42">

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Das geht technisch einfach nicht.

**Comment by TimLohrer** [comment]
Custom ist immer auf eigene faust und verantwortung
