### ISSUE TITLE
[Bug]: Minigames werden mit Shader falsch gerendert

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#347]
### How to reproduce ?

Alle Minigames (außer FlappyBird, Stack und Tetris (Übrig bleiben: Pong und TicTactoe)) werden mit Shadern falsch gerendert (Siehe Bilder)
![2024-08-16_17 43 49](https://github.com/user-attachments/assets/d3b0b512-2db6-4d92-ba4d-e0d364006285)
![2024-08-16_17 42 26](https://github.com/user-attachments/assets/7664c67a-1040-4c85-ba2b-b6027647644a)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
@PSJahn @0x3C50 Da brauch ich eure GLSL Power, das kann man probably nicht fixen oder? 
bzw wäre einfach nicht worth

**Comment by 0x3C50** [comment]
sieht so aus als ob das shaderpack mit dem core shader den wir da nutzen nicht klarkommen. ich glaub da können wir wenig machen
