### ISSUE TITLE
[Bug]: always wide skins

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#348]
### How to reproduce ?

Es werden immer wide skins in der cape preview angezeigt obwohl der skin slim ist 
<img width="485" alt="image" src="https://github.com/user-attachments/assets/ea977abc-de23-48cc-9449-00b9a050da9f">

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.6

**Comment by TigerCrafter** [comment]
Ist doch eher ein Feature Request, oder?

**Comment by MeisterAH** [comment]
joa, wie man es halt betrachtet

**Comment by copyandexecute** [comment]
@TimLohrer uff ka ob das easy geht probably nicht ohne zu requesten

**Comment by MeisterAH** [comment]
ist leider immer noch so (v.0.5.15)
