### ISSUE TITLE
[FEATURE-REQUEST]: rotation und preview rations in config for cosmetics

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#35]
### Your idea

Bei manchen cosmetics sieht sonst die preview scheiße aus :/

![Image](https://github.com/NoRiskClient/issues/assets/55639047/5be00039-9bac-4b30-ab05-c7fa44e6802f)

![Image](https://github.com/NoRiskClient/issues/assets/55639047/a0763281-5dd6-4b32-924a-4aa2a4b937d6)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SleepyPxnda** [comment]
@TimLohrer Macht das hier mit der neuen Wardrobe überhaupt noch Sinn ?

**Comment by SleepyPxnda** [comment]
Bzw im aktuellen Stand sieht das eigentlich gut aus ?

**Comment by TimLohrer** [comment]
> Bzw im aktuellen Stand sieht das eigentlich gut aus ?

Yap, deshalb erstmal auf pausiert 👍
