### ISSUE TITLE
[FEATURE-REQUEST]: hide nametags

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#350]
### Your idea

Es wäre auch sehr schön wenn man auch die nametags hiden könnte wenn an ein minigames spectatet oder ein minigame spielt

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Geile Idee

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/79469327-d526-48c2-a8f6-7e4fd165718f)
tadaaa gibts jetzt als setting in minigamesmodule
