### ISSUE TITLE
[Bug]: Stuck while connecting to featured server

### ISSUE THREAD

**Issue by eazypaulCode** [NoRiskClient/issues#351]
### How to reproduce ?

When trying to connect to a featured server in the launcher and the connection fails, you are stuck in the following screen: https://eazypaul.de/u/sX1G0I.png

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

v0.5.6

**Comment by copyandexecute** [comment]
@enricoxD Notiz an mich, eigenen hetzner server holen in deutschland und das fixen

**Comment by enricoxD** [comment]
> @enricoxD Notiz an mich, eigenen hetzner server holen in deutschland und das fixen

Ich glaube du verwechselst da was, hier gehts um die Server, die im Launcher als gefeatured angezeigt werden. 
![image](https://github.com/user-attachments/assets/8bb989cd-6a61-4c8e-96f0-5097a8945ccc)

Bei mir gehts aber?

**Comment by copyandexecute** [comment]
oh

**Comment by copyandexecute** [comment]
gucke mal rein

**Comment by copyandexecute** [comment]
Über launcher geht
