### ISSUE TITLE
Addons liste beim scrolen buggy

### ISSUE THREAD

**Issue by Hapixh** [NoRiskClient/issues#352]
### How to reproduce ?

Wenn man im Launcher auf Addons klickt, auf mods geht, etwas runterscrollt und dann einen filter angibt, wird man nicht zurück an den Anfang der Liste gebracht. Wenn man jedoch sein mausrad nur etwas bewegt wird man an den Anfang der Liste zurückgebracht.

https://github.com/user-attachments/assets/7e8fd1ba-4cf6-49e4-8349-0fafb94563da

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
@TimLohrer das sollte easy one sein oder

**Comment by TimLohrer** [comment]
> [@TimLohrer](https://github.com/TimLohrer) das sollte easy one sein oder

PAHAHAHAHAAHHAHAHA....... nein. Diese scheiß VirtualList werde ich irgendwann noch anzünden alter.. das  war auf fatal bei dem logs filtern usw usw... Aber bistimmt possible ^^
