### ISSUE TITLE
[FEATURE-REQUEST]: animated cape uploade

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#353]
### Your idea

es wäe cool das man vieleicht auf gifs als cape hochladen kann wie sowas

![lavablackstone](https://github.com/user-attachments/assets/4409ce45-ba25-49e8-ac93-5ebc22dc45cb)

### Where would this be applied?

Client, Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Kommt nicht
