### ISSUE TITLE
[Bug]: game not loading

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#354]
### How to reproduce ?

das game wird nicht angzeigt (bei mir tic tac toe)

![2024-08-22_13 00 25](https://github.com/user-attachments/assets/5898d012-f83d-4e0c-a6e9-09af702c93bc)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TigerCrafter** [comment]
Bei mir ist das so mit Shader

**Comment by TigerCrafter** [comment]
Ist bei mir auch so!

**Comment by TigerCrafter** [comment]
> @TigerCrafter Ist das noch immer so?

Hab schon auf Discord geachrieben

**Comment by copyandexecute** [comment]
Wie kann ich das reproducen?

**Comment by TigerCrafter** [comment]
> Wie kann ich das reproducen?

Ist seitdem (soweit ich weiß) bei niemandem anderen mehr passiert. Ist das gleiche wie mit Shader

**Comment by McCram12** [comment]
Keine ahnung es ist einfach passiert und mein Gegner hatte das selbe Übertragungs- oder Serverprobleme?

**Comment by copyandexecute** [comment]
ich close mal
