### ISSUE TITLE
[FEATURE-REQUEST]: BugHunter Cape

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#355]
### Your idea

Ein Cape für BugHunter

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
Sowas bitte nicht als feature request... Ihr bekommt schon noch euer Hack

**Comment by TigerCrafter** [comment]
> Sowas bitte nicht als feature request... Ihr bekommt schon noch euer Hack

NoRisk hat gesagt ich solle als Feature Request machen

**Comment by TimLohrer** [comment]
> > Sowas bitte nicht als feature request... Ihr bekommt schon noch euer Hack
> 
> NoRisk hat gesagt ich soll es als Feature Request machen

Ah ok, sorry.. wusste ich nicht ^^

**Comment by copyandexecute** [comment]
Gibt jetzt BugHunter Icon dank @TimLohrer
