### ISSUE TITLE
[Bug]: Riptide funktioniert bei weather changer nicht

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#356]
### How to reproduce ?

Wenn es regnet und man weather changer auf clear macht funktioniert der trident mit riptide nicht mehr, aber wenn es nicht regnet und man den weather changer auf regen stellt kann man mit dem trident fliegen obwohl es eigentlich nicht regnet

Original posted by deadeye_7: https://discord.com/channels/774271756549619722/1275082289293955286

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Weitere sehr schöne aufgabe für dich Grüner mann du schaffst das

**Comment by copyandexecute** [comment]
@Greeenman999 good job 
![grafik](https://github.com/user-attachments/assets/d65d3b07-9f79-4233-bb86-a319facb556b)
aber wenn man das module AUS hat aber auf thunder gestellt ist, wird trotzdem der gradient applied, bitte checken

**Comment by Greeenman999** [comment]
oops ist jetzt gefixt im nächsten push
