### ISSUE TITLE
[Bug]: Subwaysurfers: Able to be in the subwaysurfers mode in the lobby

### ISSUE THREAD

**Issue by DasPhiller** [NoRiskClient/issues#357]
### How to reproduce ?

1. Start subwaysurfers
2. Stop it at the right time (shown in clip)
Clip: https://streamable.com/iw46u3

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by TigerCrafter** [comment]
Das kommt bitte dorthin: https://github.com/HGLabor/issues/issues/

**Comment by DasPhiller** [comment]
> Das kommt bitte dorthin: https://github.com/HGLabor/issues/issues/

https://github.com/HGLabor/issues/issues/19
:D
