### ISSUE TITLE
[Bug]: Change Skin in Launcher

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#359]
### How to reproduce ?

Man kann den Skin nicht im Launcher ändern. Wenn man auf den Save Button drückt, passiert nichts.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.6

### Linked Discord Bug
By zock8: https://discord.com/channels/774271756549619722/1274691758277787669

**Comment by copyandexecute** [comment]
Also ich würde das ja rausnehmen, aber da gibts ärger mit @TimLohrer 
deswegen geht das an dich letsgooo

**Comment by TimLohrer** [comment]
> Also ich würde das ja rausnehmen, aber da gibts ärger mit @TimLohrer 
> deswegen geht das an dich letsgooo

Is in meinem pr fixed... Hast btw du damals mit deinem auth rework kaputt gemacht 😭🫶

**Comment by SleepyPxnda** [comment]
Fixed by https://github.com/NoRiskClient/noriskclient-launcher/pull/62

**Comment by TimLohrer** [comment]
von mir aus erst in done wenn alles validated

**Comment by TimLohrer** [comment]
Commit dazu: <https://github.com/TimLohrer/noriskclient-launcher/commit/d8e6122ba34ef3102dc8ae5fdbc99e73aeeb70d0>
