### ISSUE TITLE
[Bug]: Weavy Capes breaks all custom capes (cosmetic preview and normal player)

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#36]
### What happened?

![Image](https://github.com/NoRiskClient/issues/assets/55639047/7152b465-ac77-48b2-9201-83b3fae69a74)

![Image](https://github.com/NoRiskClient/issues/assets/55639047/c5dbe0db-b3dd-4993-a58e-d2119f4454b5)

![Image](https://github.com/NoRiskClient/issues/assets/55639047/c488d7db-b8bd-4b95-bbf6-b028e60ea993)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/a5be65eb-380e-4510-b749-0f827d9298b0)
wavy, jetzt noch inventar

**Comment by copyandexecute** [comment]
elytra 
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/66a715ae-1265-47a4-9dbf-d279be496b6e)

**Comment by TimLohrer** [comment]
Wohooo 🎉

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/7a6ac852-79a9-4e5e-97eb-c567164f4d51)
musste noch custom wavey mod support addden damit die UI auch ging

**Comment by copyandexecute** [comment]
Hypixel Skin support auch da 
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/9fc1331d-8bd9-45be-8c9f-bbcb1a8f761e)

**Comment by copyandexecute** [comment]
handleCapeSelection() anders coden sonst gibt es einen Bug beim auswählen von anderen Capes (Notiz an mich)

**Comment by copyandexecute** [comment]
+ Wavey Capes Multiplayer UI Support: 

![Image](https://github.com/NoRiskClient/issues/assets/58366920/00356ecf-a3d3-4b46-86f5-931e5ad2bd46)

**Comment by SleepyPxnda** [comment]
Glaube das tut jetzt auch
