### ISSUE TITLE
[Bug]: Wheel-Buttons Vertauscht

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#360]
### Description

Manchmal sind die Wheel-Buttons vertauscht.

### How to reproduce ?
1. Den Command "/teleport {uuid} @s" und "/teleport @s {uuid}" zum Wheel hinzufügen
2. Den Command "/teleport {uuid} @s" öfters (nicht gespammt) über das Wheel ausführen
3. Du wirst zu dem Entity teleportiert, obwohl es eigentlich zu dir teleportiert werden sollte

### Where is this happening?

Client

### What Client Branch did you use?

1.21

### Linked Discord Bug
By nightrx_1: https://discord.com/channels/774271756549619722/1271884103486148729

**Comment by TigerCrafter** [comment]
Passiert nur wenn sich das Entity bewegt. Die Anzeige des Wheels bewegt sich mit dem Entity. Die Hitbox der Buttons nicht (glaube ich)

**Comment by copyandexecute** [comment]
Ach bei bewegung?
