### ISSUE TITLE
[Bug]: Es ist möglich den Client mehrmals zu starten

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#364]
### How to reproduce ?

Wenn man den Launcher mehrmals öffnet, kann man auch den Client mehrmals starten.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SirKnubble** [comment]
Obviously. Ist kein Bug.

**Comment by BigBrainRobin29** [comment]
Ok, aber wenn man mit nur einem Launcher den Client nochmal starten will, geht das nicht.

**Comment by SirKnubble** [comment]
Soll es auch nicht.

**Comment by BigBrainRobin29** [comment]
Ok
