### ISSUE TITLE
[Bug MCREAL-APP]: Pin-Screen doesn't refresh automatically 

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#365]
### How to reproduce ?

Wenn man ein McReal pinnt, auto refreshed der Pin-Screen nicht

### Where is this happening?

McReal-App

### What platform are you seeing the problem on?

Android

### Version

1.0.2

**Comment by TigerCrafter** [comment]
Es ist auch wenn man die Sprache ändert. Wenn man zurück auf die Startseite geht, muss man die Seite neu laden, damit es sich aktualisiert.

**Comment by TimLohrer** [comment]
@TigerCrafter Mache gleich neue Version... Sollte dann fixed sein ^^
