### ISSUE TITLE
[Bug MCREAL-APP]: McReal doesn't load

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#366]
### How to reproduce ?

Wenn im Friends Tab zwei McReals sind, laden bei Discovery die ersten zwei McReals nicht

### Where is this happening?

McReal-App

### What platform are you seeing the problem on? (for launcher bugs)

Android

### Version

1.0.2

**Comment by TimLohrer** [comment]
Also bei mir iwie auch aber ngl kp wieso.. Muss ich mir nochmal genaue anschauen ^^

**Comment by TimLohrer** [comment]
Habs gefunden :D
Commit kommt gleich 👍
