### ISSUE TITLE
[FEATURE-REQUEST MCREAL-APP]: Blurred Box behind Font

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#367]
### Your idea

Vielleicht eine Blurred Box hinter "Friends" und "Discovery"

Idea by hennycraft: https://discord.com/channels/774271756549619722/1276878206661562451/1278015575095771270

### Where would this be applied?

McReal-App 

### What platforms would this affect?

Android, IOS

**Comment by TimLohrer** [comment]
@TigerCrafter so?

![Image](https://github.com/user-attachments/assets/9cd3cca3-79e9-4e13-bddc-235e36ef1017)

**Comment by TigerCrafter** [comment]
> @TigerCrafter so?
> 
> ![Image](https://github.com/user-attachments/assets/9cd3cca3-79e9-4e13-bddc-235e36ef1017)
> 
> 

Ja so passt es
