### ISSUE TITLE
[Bug]: Fehlende DB einträge

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#37]
### What happened?

Wenn jmd neues dezu kommt wird nur in noriskUsers ein doc erstellt, sonst nirgends.
Das führt dazu, dass man wuasi nix machen kann.

**Vermutung**
Durch die addition vom "rank" beim noriskUser gehen die enums in den anderen backends kaputt und erstellen ihr doc nicht.

Update: (ich hatte recht)

![Image](https://github.com/NoRiskClient/issues/assets/55639047/e294eec6-e587-45ee-b303-d4a8f23b2e25)

### Where is this happening?

Backend

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Höö durch meine Rank addition oder deine damals?
