### ISSUE TITLE
[Bug]: Frinds Last Online Time

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#373]
### How to reproduce ?

Das ist mir jetzt schon öfters aufgefallen: Wenn ein Freund das Spiel verlässt, steht dort z.B.: "Offline for 2 hours". 
![image](https://github.com/user-attachments/assets/8d574246-628e-42f9-839a-f043c8230df4)

(Das Bild habe ich gemacht, wo NoRiskk gerade offline gegangen ist)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
Timezone Problem denke ich

**Comment by BigBrainRobin29** [comment]
Oder last online time beginnt beim Starten und nicht beim Beenden der Session.

**Comment by SleepyPxnda** [comment]
Nene, das ist ein Zeitzonen Problem :D

**Comment by copyandexecute** [comment]
@enricoxD wir tracken ja nur wann er das letzte mal gejoint ist und nicht geleaved, du wolltest da eh mal was einbauen right?

deswegen assign ich dir das !
