### ISSUE TITLE
[Bug]: Namen in Friendlist abgeschnitten

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#374]
### How to reproduce ?

In der Friendlist sind die Namen von ein paar Leuten abgeschnitten. z.B. bei PhantomiasDuck
![image](https://github.com/user-attachments/assets/8d574246-628e-42f9-839a-f043c8230df4)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/cc948652-f608-4231-8d61-ba49354bdbab)
konnte es aktuell nicht reproduzieren, schau mal obs mit dem nächsten update gefixed ist

**Comment by TigerCrafter** [comment]
> ![grafik](https://github.com/user-attachments/assets/cc948652-f608-4231-8d61-ba49354bdbab)
> konnte es aktuell nicht reproduzieren, schau mal obs mit dem nächsten update gefixed ist

Ist nur so, wenn der Player online ist
