### ISSUE TITLE
[SECURITY-ISSUE]: Spamming the Websocket makes the friends api respons with 500 server error on client side

### ISSUE THREAD

**Issue by FabCodeDE** [NoRiskClient/issues#375]
### Contact Details

itsmefab

### What happened?

Stress testing the websocket with around 500 connections at the same time brings down the websocket i guess.
Dont want to do more testing. Maybe sort out the connection on server side that dont contain valid data, and also add an authentication to the websocket including the connection or something to block something like that.
![image](https://github.com/user-attachments/assets/08acb377-6f2b-41e1-879f-267496444756)

### Where is this happening?

Backend

### What platform are you seeing the problem on?

Not a launcher related problem

**Comment by onlyJakob** [comment]
afaik the client don't use websockets and authentication doesn't protect against a DOS attack.

**Comment by copyandexecute** [comment]
Hi, hast du lust mir auf Discord zu schreiben was du gemachst hast?
Ich wäre dir sehr dankbar, mach einfach ein Ticket auf

**Comment by FabCodeDE** [comment]
Hi, hab schon ein Ticket im Discord aufgemacht

**Comment by FabCodeDE** [comment]
https://discord.com/channels/774271756549619722/1280164524783304744

**Comment by copyandexecute** [comment]
Cloudflare ratelimit eingebaut + websocket internal ratelimit
