### ISSUE TITLE
[Bug]: Profile switching not working 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#380]
### How to reproduce ?

Wenn man auf ein anderes profile klickt und es dann starten wird es nicht aktualisiert (es sind immernoch die gleichen mods drinnen wie beim profile das man ursprünglich hatte) 

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.6

**Comment by copyandexecute** [comment]
Ist noch immer der Fall oder? Kannst du nochmal schreiben wie man das reproduziert

**Comment by copyandexecute** [comment]
uuuh tim ich sehe btw die launcher_profiles sind alle in einer .json, würde es vlt sinn machen die per file zu machen, damit wir in zukunft ein feature haben wo wir easy bestimmte profile sharen können?

**Comment by MeisterAH** [comment]
> Ist noch immer der Fall oder? Kannst du nochmal schreiben wie man das reproduziert

uh, jetzt ist nur noch so das die texturepacks in das andere profile gecopied werden und nicht mehr die Mods

How to reproduce 

1. profile erstellen 
2. jeweils eine mod und ein tp zum profile hinzufügen
3. neues profile erstellen 
4. mc starten
5. mod menu auf die mod durchsuchen
6. texturepack menu durchsuchen

**Comment by TimLohrer** [comment]
@MeisterAH das ist acctually "intended" bzw das habe ich nie codet, weil das immer nur pro mc version is und ich dachte, das wäre evtl sogar relativ praktisch. Dass die pro profil automatisch andere selected sind, kann ich sowieso nicht machen, deshalb kp was das geanu bringen soll.. Oder vergesse ich was? Sonst is das sehr viel Arbeit

**Comment by MeisterAH** [comment]
also wenn es nur die texturepacks sind dann ist das gut 👍

**Comment by TimLohrer** [comment]
Also dann is das kein bug

**Comment by MeisterAH** [comment]
jup is fixed, davor wurden auch die mods in die verschiedenen profiles copiert
