### ISSUE TITLE
[Bug]: Launcher skalirung

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#381]
### How to reproduce ?

ich wollte das spiel starten und auf einmal war das launcherfester kommplet komisch!
![skalirunge fehler](https://github.com/user-attachments/assets/bbb3baf2-3cb0-4bbd-8ea5-d03053bc9c48)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by McCram12** [comment]
wen man es nich siet der bereich unten soll eigentlich oben sein

**Comment by McCram12** [comment]
![Screenshot 2024-09-05 160858](https://github.com/user-attachments/assets/e11cfe82-950c-4a27-8d25-c42e8728c50e)

**Comment by TigerCrafter** [comment]
Duplicate of #336
