### ISSUE TITLE
[Bug]: Launcher correctly states that the API is offline

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#383]
### How to reproduce ?

1. Internet ausschalten
2. Launcher starten

![image](https://github.com/user-attachments/assets/5f99b2ef-f661-4c4b-9d66-d7e3d4bd6c5f)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.6

**Comment by MeisterAH** [comment]
launcher ist nicht für das offline spielen gedacht

**Comment by 0x3C50** [comment]
ist richtig so

**Comment by BigBrainRobin29** [comment]
Ist mir schon klar, aber in dem Fall bin ich offline und nicht die API. Egal, wenn ihr es so lassen wollt, dann lasst es.
