### ISSUE TITLE
[Bug MCREAL-APP]: Kommentar-Bug: Strich leicht versetzt

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#385]
### How to reproduce ?

Wenn man einen Kommentar schreibt ist der Strich, der anzeigt wo man gerade ist, ein bisschen nach oben versetzt

### Where is this happening?

McReal-App

### What platform are you seeing the problem on?

Android

### Version

1.0.4

**Comment by TimLohrer** [comment]
Ja habe das nt anders hinbekommen... war cursed.... bleibt erstmal
