### ISSUE TITLE
[Bug MCREAL-APP]: Kommentar-Bug: Kommentar nicht sichtbar

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#386]
### How to reproduce ?

Wenn man neben die Kommentarbox klickt steht nichts mehr in ihr, wenn man erneut draufklickt, jedoch schon. (Die Zeichenanzahl wird jedoch angezeigt)

### Where is this happening?

McReal-App

### What platform are you seeing the problem on?

Android

### Version

1.0.4

**Comment by BigBrainRobin29** [comment]
@TigerCrafter noch valid?

**Comment by BigBrainRobin29** [comment]
Dann close ich das erstmal
