### ISSUE TITLE
[Bug]: Emote Lib, emote spielt zur falschen zeit ab

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#387]
### How to reproduce ?

Spiel ein emote ab in der normalen perspektive und geh dann in F5, es sollte aber unabhängig von der perspektive direkt abspielen
(Schicke Video privat lol)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
das emote wird erst abgespielt wenn der spieler sichtbar ist

**Comment by 0x3C50** [comment]
c3caf092

**Comment by copyandexecute** [comment]
https://github.com/NoRiskClient/noriskclient-client-modules/commit/c3caf0924bfb4d640f09125c4163626568668dde
