### ISSUE TITLE
[FEATURE-REQUEST]: Decrease nearby nametag opacity when playing minigame

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#388]
### Your idea

![2024-09-09_17 47 02](https://github.com/user-attachments/assets/1456e18a-6195-425e-988b-ee9485e266b0)

Die Nametags stören halt

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by MeisterAH** [comment]
ist glaube ich die selbe idee oder? https://github.com/NoRiskClient/issues/issues/350

**Comment by Kolpixx** [comment]
Ja, isn duplicate.

**Comment by Kolpixx** [comment]
Ja is'n duplicate.
