### ISSUE TITLE
[FEATURE-REQUEST]: Option to select mod version

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#389]
### Your idea

Bspw. ein Dropdown Menü in den "Installed" Mods Tab im Launcher, wo man die Version der Mod auswählen kann. Könnte helfen, wenn man inkompatible mods hat.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
Geile Idee und nötig! Ich frage mal @SirKnubble ob er das codet, wäre mega

**Comment by copyandexecute** [comment]
SirKnubble ist raus da muss @TimLohrer ran, ich packs mal zum RELEASE Milestone
