### ISSUE TITLE
[FEATURE-REQUEST]: Emote Shop UI

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#390]
### 1.

Erstell ein neues `ShopItemInformationDto` mit id: **UUID**, name: **String**, price: **Int**, creator: **String?**, rarity: **Rarity**
 (halte es generisch will das später auch für ränge, skins o.a nutzen) 
_angelehnt an die `norisk.json` von den cosmetics_

pack das Dto in `gg.norisk.backend.networking.model.shop` von der `backend-base-api` (kannst natürlich erst alles am ende moven, weil sonst kacke zum coden imo)

### 2.

Erstell einen neuen **IdentifiableResourceReloadListener** für den pfad `shop/emotes` (siehe `GeckolibCacheMixin`, `EmoteLibCache`) und lad alle ShopItemInformationDto
(TODO: irgendwie geil die Referenz auf die `emote.animation.json` einbauen)

### 3. 

Neuen Emotes Tab Button Adden

![grafik](https://github.com/user-attachments/assets/8b3ba5bf-d807-459d-83af-10b7addda60e)

### 4. 

Emotes ähnlich wie die Cosmetics im **loop** anzeigen mit pricetag, ownedtag, name, rarity 
![grafik](https://github.com/user-attachments/assets/5937e71b-3b45-4f63-b58e-07dd0efe70ba)

### 5. 

Wenn man Emote anklickt -> sollte die Playerpreview den emote auch im loop abspielen

### 6.

Emote Purchase Button adden einmal rechts über PlayerPreview und einmal als Option 

![grafik](https://github.com/user-attachments/assets/ced031df-dd3d-4945-a8b9-af7db29fd194)

![grafik](https://github.com/user-attachments/assets/7043cbc0-6422-4b96-b110-77e9b02bff27)

**WIP**
Wir brauchen einen intuitiven geilen weg emotes von der ui in das wheel reinzubekommen kp wie aktuell lol
Sollte es sowas wie Emote Categories geben? "Movement", "Funny", ...

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by 0x3C50** [comment]
Shop UI ist auch relativ weit
- [x] An sich die emotes anzeigen
- [x] Emote preview abspielen
- [ ] Tatsächlich mit dem server syncen
