### ISSUE TITLE
[FEATURE-REQUEST]: Emote Backend / Client Sync

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#391]
### 1.

`CosmeticShopUser` erweitern mit 
`val ownedItems: MutableSet<@Serializable(with = UUIDSerializer::class) UUID> = mutableSetOf()`

### 2.

Im `cosmetics-backend` eine weitere `EmoteRoute` adden

- [ ] **POST** um emotes abzuspielen 
- Überprüfen, ob der Spieler das Emote gekauft hat
- Jetzt gibt es 2 Optionen wie du das den Spielern mitteilst 
Entweder 
1. Option: Du cachest es in redis für x sekunden und machst es ähnlich wie die cosmetics -> EmoteSender schickt ein ModelPart update und alle anderen Clients fetchen über einen **/get** request den redis cache
2. Option: Du machst es wie wir anfangs geschnackt haben mit deiner diese Spieler spielen auf dem Server Map und schickst es via websocket an die jeweiligen connections

### 3.

Generischer `POST` Endpoint zum kaufen von ShopItems mit Error Handling, Authentication Check, AlreadyOwned Check, Price Check, Transaction speichern etc...

### 4.

**WIP** Infinite Emotes, Emotes abbrechen durch aktionen wie laufen, abbauen, schlagen, damage?

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by 0x3C50** [comment]
87c79c2, mein teil wär damit ja eigentlich fertig. enrico würde den shop machen
