### ISSUE TITLE
[FEATURE-REQUEST]: Emote Wheel

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#392]
### Your idea

**1.**

Keybind erstellen und default auf B setzen -> Öffnet Emote Wheel
Emote Wheel soll nur offen bleiben während man Keybind **gedrückt hält**

Mach das ding in der mitte weg und dann ist fürs erste fine 

![grafik](https://github.com/user-attachments/assets/d6d15c76-7516-45f8-864e-c9d6f4ff90b8)

**2.**

Emotes anklicken -> Man kommt automatisch in F5, Wheel schließt sich und der Teil kommt ins Spiel <https://github.com/NoRiskClient/issues/issues/391>

**3.**

Gleiches TODO wie bei <https://github.com/NoRiskClient/issues/issues/390>
>  Wir brauchen einen intuitiven geilen weg emotes von der ui in das wheel reinzubekommen kp wie aktuell lol

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by 0x3C50** [comment]
idee für's emote wheel: manager um bis zu 5 emotes auswählen zu könenn die dann aufs wheel gehen. alles andere muss durch den manager abgespielt werden (wäre sowas wie eine liste)

**Comment by 0x3C50** [comment]
emote wheel wär fürs erste fertig. dinge die noch gemacht werden müssen:
- [ ] Favoriten auswählen die aufs wheel kommen

**Comment by copyandexecute** [comment]
NAILED IST @0x3C50
