### ISSUE TITLE
[FEATURE-REQUEST]: Horizontal Scroll Bar in Crash Report window

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#396]
### Your idea

Eine horizontale Scroll Leiste um die ganze log Zeile zu sehen

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows

**Comment by copyandexecute** [comment]
Einfach fenster größer machen oder geht es garnicht gar nicht

**Comment by BigBrainRobin29** [comment]
Geht auch, aber es gibt teilweise Logzeilen, die dann immer noch nicht hinpassen. Text wrapping als option wäre auch ne Idee.

**Comment by TimLohrer** [comment]
Ich mache text wrap, das andere is goofy mit scrollen, weil die scrollbar so dünn is und vertikal scrollen eh immer sehr userunfreundlich
