### ISSUE TITLE
[Bug]: Mod Dependencies nicht als "Installed" angezeigt

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#397]
### How to reproduce ?

Wenn ich bspw die Mod [Hudify](https://modrinth.com/mod/hudify) (Nicht mit dem Client kompatibel, aber ist für dieses Issue egal) installiere, dann lädt der Launcher auch automatisch die benötigten dependencies ([CustomHUD](https://modrinth.com/mod/customhud) und [MidnightLib](https://modrinth.com/mod/midnightlib)) runter, aber wenn ich nach denen im Discover Menü suche, dann werden sie nicht als Installiert angezeigt:
![grafik](https://github.com/user-attachments/assets/b403285e-c293-454d-b7d0-56fe7c9122b5)
Und im "Installed" Tab werden die Dependencies auch nicht angezeigt (ka ob das gewollt ist).

Das der Launcher die Dependencies installiert und deinstalliert funktioniert natürlich trotzdem, aber sie werden halt einfach nicht als Installiert angezeigt.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.6

**Comment by SirKnubble** [comment]
Der Punkt ist valid, schau ich mir an während ich Version Selector mach. 🤌

**Comment by TimLohrer** [comment]
Kein bock das zu coden aber muss wohl 💀 
Entweder bin ich grad zu optimistisch oder es wird schwer, aber vllt habe ich ja glück xd

**Comment by TimLohrer** [comment]
![Image](https://github.com/user-attachments/assets/d752edc3-d656-41f9-9c2a-af1811d27137)

**Comment by SleepyPxnda** [comment]
I guess damit ist das durch ? @TimLohrer

**Comment by TimLohrer** [comment]
> I guess damit ist das durch ? @TimLohrer 

Ja, aber würde erst of done wenn am ende alles zsm getestet ist
