### ISSUE TITLE
[Bug]: Glow layer geht nicht

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#40]
### What happened?

kp warum, sobald man "GLOW" als layer added buggt die textur und glowen tut nix

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Glow Sections für nicht animierte Texturen: 

![Image](https://github.com/NoRiskClient/issues/assets/58366920/253ca781-74c2-40e9-a4f4-3960e8f7b50c)

in der norisk.json muss man das hier providen: 
```
    "layers": [
        "GLOW"
    ],
```

und in der png.mcmeta muss man die sections so providen:

```
{
  "glowsections": {
    "sections": [
      {
        "x1": 24,
        "y1": 0,
        "x2": 33,
        "y2": 3
      }
    ]
  }
}
```

Ich mache jetzt weiter mit animierten Texturen

**Comment by copyandexecute** [comment]
Animierte Texturen aktuell keine Ahnung... hab mal im Gecko Lib Discord gefragt obs dafür ein Beispiel gibt

**Comment by TimLohrer** [comment]
![Image](https://github.com/NoRiskClient/issues/assets/55639047/340e2e14-1cf3-4931-a7c3-ea330d1accb2)
