### ISSUE TITLE
[Bug]: Wavey Capes incompatible with cosmetic previews

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#400]
### How to reproduce ?

Wenn man die Mod installiert hat sind alle capes in der preview verbuggt.

Cosmetic shop preview:
<img width="363" alt="image" src="https://github.com/user-attachments/assets/38dc4224-42b2-45a4-840c-6bb23b5681f7">

Outfit preview:
<img width="274" alt="image" src="https://github.com/user-attachments/assets/8d4c5051-48bb-4581-93e5-f8e73410dab1">

### Where is this happening?

Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
cant reproduce 
![grafik](https://github.com/user-attachments/assets/dc3e102b-e899-4a9c-bb20-84406a95c9a3)
