### ISSUE TITLE
[FEATURE-REQUEST]: Capes browsen (cape databank)

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#402]
### Your idea

Derzeit ist es nicht möglich, neu erstellte Capes von anderen Leuten zu finden und somit auf das Leaderboard zu kommen. Deshalb wäre es sinnvoll, wenn man Capes durchsuchen könnte. Also, dass da dann noch ein Button mit 'Browse Capes' ist und man dadurch alle Capes suchen kann, die es gibt. (=cape databank)

<img width="520" alt="image" src="https://github.com/user-attachments/assets/093ee748-152f-47ab-be96-cbb285f6d43d">

Norisk approved :^)

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by MisterDoenerHD** [comment]
Würde dazu dann maybe auch nen tag system adden, das man seinen eigenen capes tags zuweisen kann nach denen dann gefiltert werden kann
