### ISSUE TITLE
[Bug]: Minigames gegen sich selbst

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#403]
### Describe your problem

Man kann z.B. Teris gegen sich selbst spielen, indem man den Command `/nrc minigames tetris invite [Dein Spielername]` ausführt. Es gibt natürlich ein paar Bugs, diese sind jedoch unwichtig, da man den Command einfach blockieren und dem Spieler eine Message wie "You can't invite yourself to a minigame!" schreiben sollte.

### Where is this happening?

Client

### Branch

1.21

**Comment by copyandexecute** [comment]
See also https://github.com/NoRiskClient/issues/issues/338
