### ISSUE TITLE
[FEATURE-REQUEST]: toggle if emotes are infinte

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#405]
### Your idea

man sollte es togglen können ob alle emotes infinte abgespielt werden oder ab einer bestimmten Zeit abgebrochen werden

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Aktuell haben wir uns dafür dagegen entschieden weil der emote an sich das bereitstellen soll, also wenn ein emote infinite ist ist er es, ansonsten nicht

Mal schauen wie das Community feedback ist

**Comment by copyandexecute** [comment]
Bisherige Entscheidung: Der Emote entscheidet ob infinite, hold oder once
