### ISSUE TITLE
[FEATURE-REQUEST]: stop emoting

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#406]
### Your idea

man kann grade noch nicht aufhören zu emoten (außer man verlässt den server)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
fixed oder?

**Comment by MeisterAH** [comment]
äh warte

**Comment by MeisterAH** [comment]
jup is fixed
