### ISSUE TITLE
[FEATURE-REQUEST]: too many emotes

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#407]
### Your idea

es sind imo ein paar zuviele emotes in dem wheel
![9F22A89C-BFCE-4DB6-867A-84689C8B9A1B](https://github.com/user-attachments/assets/ed0404f6-bbac-4b50-985d-7ce6d3880306)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SirKnubble** [comment]
Hättest du für alles neue Issue aufmachen müssen? 😭 

https://github.com/NoRiskClient/issues/issues/410#issuecomment-2378949171

**Comment by MeisterAH** [comment]
jaa sry haha
