### ISSUE TITLE
[Bug]: able to stack emotes

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#408]
### How to reproduce ?

man kann mehrere emotes gleichzeitig abspielen

reported by ƁaboƁastisch
https://discord.com/channels/774271756549619722/1288859976277823561

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by 0x3C50** [comment]
zumindest im jetzigen zustand war das so beabsichtigt. @copyandexecute ich glaube wir sollten uns da tatsächlich nochmal gedanken zu machen ob wir das so wollen

**Comment by copyandexecute** [comment]
Jup, aktuelle meinung: Wir habens mal drin gelassen, das chaos passt irgendwie zum noriskclient 
Endgültige meinung kommt nach community feedback!

**Comment by copyandexecute** [comment]
Bisherige Entscheidung: Ist geil wenn man mehrere abspielen kann
