### ISSUE TITLE
[FEATURE-REQUEST]: show second skin layer in emote wheel

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#409]
### Your idea

:^) 
![image](https://github.com/user-attachments/assets/87506003-4c6b-4e8d-b52d-293caf8c337a)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SirKnubble** [comment]
Check nicht

**Comment by MeisterAH** [comment]
das der second layer von skin im emote wheel angezeigt wird

**Comment by copyandexecute** [comment]
Fixed oder?
