### ISSUE TITLE
[Bug]: unable to click on lowest emote

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#410]
### How to reproduce ?

man kann nicht auf das unterste emote klicken da es aus dem bild geht
https://i.imgur.com/pvyXkjy.mp4

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Ist ja nicht die Final Version, später hast du nicht alle in dem Menü sondern kannst welche da "anpinnen".

**Comment by 0x3C50** [comment]
um dazu noch anzuhängen, die finale version wird sich an die bildschirmgröße anpassen. dazu hast du im video tatsächlich das emote ausgewählt, auch wenn du nicht komplett mit dem cursor drauf bist.
