### ISSUE TITLE
[Bug]: missing translation

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#411]
### How to reproduce ?

im emote module ist eine fehlerhafte translation

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/fe75cc5f-6dfd-47a3-8050-87e9c0bad34a">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Ich adde hier https://github.com/NoRiskClient/issues/issues/480
