### ISSUE TITLE
[Bug]: When enabling "NoFog", blocks are invisible

### ISSUE THREAD

**Issue by 8droid** [NoRiskClient/issues#412]
### How to reproduce ?

- (Disable shaders)
- Start NRC (1.21)
- Load into a world
- Enable "NoFog" (Default Settings)

### **Result:**
<img src="https://github.com/user-attachments/assets/7668e8e6-754f-4084-bfc9-224d17b95f7a" width=600px>

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
@Greeenman999 es hat auf jeden fall mit nvidium zu tun ohne geht es, und wenn man bei nofog die fogdistance größer macht wird es auch gefixed, müssen da denke in nvidium was reininjecten? guck mal gerne nach!

**Comment by Greeenman999** [comment]
Kann nachschauen, hab aber keine NVIDIA gpu

**Comment by copyandexecute** [comment]
fixed mit nächsten update
