### ISSUE TITLE
[Bug]: Emojiful not compatible with custom NRC+ Effects

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#413]
### How to reproduce ?

Die Mod Emojiful ist nicht mit den Nametags von NRC+ kompatibel

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SleepyPxnda** [comment]
@TimLohrer können wir das auf die Blocked Liste nehmen ?

**Comment by TimLohrer** [comment]
Ne, einfach nt benutzen

**Comment by TimLohrer** [comment]
@SleepyPxnda

**Comment by TimLohrer** [comment]
Selber schuld, würde es aber nt verbieten wenn man es will
