### ISSUE TITLE
[FEATURE-REQUEST]: Subwaysurfer lobby: Berd der Baum

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#417]
### Your idea

kann man in der subway surfers lobby einen baum also der **https://imgur.com/85WZy4h** mit einem schiel geben ich nenne icn Berd der Baum! 
![berd_der_baum](https://github.com/user-attachments/assets/aa16fac6-975c-4786-b12e-e00ad7536b9b)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Das ist crazy
