### ISSUE TITLE
[Bug]: Screenshot after MCReal → crash

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#418]
### How to reproduce ?

Wenn man einen screenshot macht, nachdem man ein mcreal hochgeladen hat, crasht das game

https://mclo.gs/NlJVL0w

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Scheint ein MacOs problem zu sein

**Comment by copyandexecute** [comment]
Sind dran

**Comment by copyandexecute** [comment]
nojoke da einfach if (macos) dann nicht copy grünner man du findest was

**Comment by copyandexecute** [comment]
Liegt an copy to clipboard

**Comment by copyandexecute** [comment]
Konnte es aktuell nicht fixen, wenn das problem öfter kommt, wird @Greeenman999 sich drum kümmern 😭
