### ISSUE TITLE
[Bug]: F5 and Try to open cosmetics crashes the game

### ISSUE THREAD

**Issue by HeroOfDungeon** [NoRiskClient/issues#419]
### How to reproduce ?

1. In F5 gehen
2. Emote-Menu öffnen (Standartmässig [B], bei mir [Y])

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug, Windows

### Relevant log output

```shell
Error-Code: -1
Error-Logs: https://mclo.gs/TZVFhmj
```

**Comment by MeisterAH** [comment]
ist bei mir nicht so, welchen emote hast du den ausgewählt?

**Comment by copyandexecute** [comment]
ist das noch valid?

**Comment by SleepyPxnda** [comment]
Ich schließe es, da nixmehr kam, sollte es noch auftreten @HeroOfDungeon bitte reopen 😄
