### ISSUE TITLE
Ping-System 

### ISSUE THREAD

**Issue by Naaam23** [NoRiskClient/issues#42]
### STAND: 3.12.2023 15:36

**Legende**: In () steht woher die Ideen kommen und wer sie geschrieben hat. Das -> steht für meine persönlichen Anmerkungen/Ideen.

**Generell:** Objekte/Spieler pingen und diesen Ping für andere sichtbar machen.

**Priorität:** Wird von vielen gewünscht. (Quelle NoRisk)

**Genauere Beschreibung/Visuell:**  (Idee aus einem Discord Thread, von SpeedyT14) Die Pings sollen im Grunde ein Kreis in der Nähe des Spielers/Objekt sein, indem der Spielerkopf/Item/Block drinnen ist. -> Eigene Anmerkung: Soweit ich es mitbekommen habe, ist es manchmal problematisch/relativ langsam den Playerkopf aus der API zu kriegen. Das wäre zwar perfekt, aber man muss schauen ob sich das so schnell updaten kann.

**Dauer:** (Idee aus einem Discord Thread, von SpeedyT14) Ca. 5 Sekunden, (slxme Vorschlag wäre einen Slider einzubauen, welche die Dauer zwischen 3-30 Sekunden verändern kann -> Das sollte vom den anzuzeigenden Pings ausgehen, nicht von dem Spieler welche die Pings markiert.)

**Wer sieht die Pings?**: (slxme) Party/Gruppen-System mit Einladungen, die Gruppen sind nur temporär und verschwinden sobald kein Spieler mehr in der Gruppe ist. -> Würde das genauso machen, sonst würde es zu viele Trolls geben.

**Sound**: -> Soundeffekt ist relativ variabel, würde schon einen Sound nehmen, aber eher einen kleinen Sound, welcher auch ausstellbar sein sollte, da damit auch gespammt werden könnte.

Zusatzidee: (Idee aus einem Discord Thread, von SpeedyT14) Im Grunde wie WayPoints indem man Blöcke/Items markiert, welche solange markiert bleiben, bis diese abgebaut/eingesammelt wurden.

**WICHTIG:** Die Pings markieren die Position des aktuellen anvisierten Objekts/Spieler, manche Leute wollten auch, dass sie die Bewegung für ein paar Sekunden tracken. Logischerweise ist das ein Cheat, weswegen wir das besser gar nicht erst einbauen sollten. (Außer NoRisk gefällt die Idee so sehr, dass man das für den Singleplayer/eigene Server aktivieren kann)

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@PSJahn ich ping dich einfach mal j4f

**Comment by PSJahn** [comment]
> @PSJahn ich ping dich einfach mal j4f

Guter Reminder, diese Woche wird wohl zeitlich etwas schwer für mich aber mal gucken was sich machen lässt
