### ISSUE TITLE
[Bug]: "Man ist im login screen gefangen und kann nichts einstellen"

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#427]
### How to reproduce ?

https://discord.com/channels/774271756549619722/1293118440285933610

er ist sofort in einem verbuggtem anmelde screen auch nach neustart, neuinstallation und allen Dateien löschen
er hat einen m1 chip 
https://github.com/user-attachments/assets/ef1b7870-8dfb-4989-b6fe-cc967d767115

latest.log (launcher log existier bei ihm nicht??)
[latest.log](https://github.com/user-attachments/files/17296195/latest.log)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

**Comment by TigerCrafter** [comment]
Was meinst du mit "Launcher Log existiert bei ihm nicht"? Das ist dich der Launcher Log

**Comment by MeisterAH** [comment]
das ist der latest.log gibt ja noch den launcher log oder?

**Comment by TigerCrafter** [comment]
> das ist der latest.log gibt ja noch den launcher log oder?

Es gibt einmal latest.log bei dem Client und latest.log bei den Launcher

**Comment by TigerCrafter** [comment]
Wenn man sich den Launcher Log anschaut steht ja auch "New Launcher Log"

**Comment by MeisterAH** [comment]
schon, aber es gibt noch eine datei die eine noch detaillierteren log hat, verstehe das ganze aber auch nicht so wirklich tbh 
<img width="194" alt="image" src="https://github.com/user-attachments/assets/0d8f6fed-a00e-4a52-9021-fe687f89b6ae">

**Comment by copyandexecute** [comment]
@TimLohrer das hier ist das Macos 12 supported <dialog> nicht issue (ab jetzt)

**Comment by MeisterAH** [comment]
jo sehr stark, warte ich füg dich zu der gruppe mit dem macos leuten hinzu

**Comment by MeisterAH** [comment]
sryy
