### ISSUE TITLE
[Bug]: Second Layer nicht rendern wenn Cosmetic an ist

### ISSUE THREAD

**Issue by Antowkaa** [NoRiskClient/issues#428]
### How to reproduce ?

1

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
Kannst du zeigen was du meinst

**Comment by Antowkaa** [comment]
z.B. bei einem hat cosmetic: Wenn ich es anziehe, soll der second layer des Kopfes nicht mehr gerendert werden, weil second Layer durch des Cosmetic "bugt". Siehe Bild.
![image](https://github.com/user-attachments/assets/6094620c-9cab-48e5-a71c-9a20d9197b57)

**Comment by SleepyPxnda** [comment]
Schon wieder das second Layer Thema 😆 Ich glaube das wird uns für immer verfolgen 😮‍💨

**Comment by copyandexecute** [comment]
ah also eine einstellung es im cosmetic zu forcen?

**Comment by copyandexecute** [comment]
https://gyazo.com/e0b4f3e6692e6001cffa0f3f4177b0d6
