### ISSUE TITLE
[FEATURE-REQUEST]: IsRunning After Launcher Restart

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#429]
### Your idea

@TimLohrer 
ähnlich wie du es bei deinen custom server gecodet hast, bräuchten wir etwas dass der launcher weiß dass wir ingame sind damit isClientRunning auf true geflagged wird und wir zu den logs etc kommen!

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows

**Comment by TimLohrer** [comment]
@copyandexecute das Problem wird jetzt sein, dass die live logs trotzdem nt gehen werden, aber das man nt startetn kann könnte ich coden... Das würde dann aber verhinden, dass man 2 Instanzen launchen kann, wie willst du das?

**Comment by TimLohrer** [comment]
TODO: Check ob das window in der terminate function auf MacOS und Windows auch "java" heißt und ggf. alternativen in's "if" einbauen

**Comment by TimLohrer** [comment]
Klappt!
