### ISSUE TITLE
[Bug]: Module list is empty if the searchbar is empty

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#43]
### What happened?

![Image](https://github.com/NoRiskClient/issues/assets/55639047/48b0025f-eaa8-40b9-b462-3e0078f7b746)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
@copyandexecute was meinst du? Passt das so?

**Comment by copyandexecute** [comment]
Yes sieht gut aus
