### ISSUE TITLE
[FEATURE-REQUEST / BUG]: Minigames websocket nicht verbennen lassen

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#434]
### Your idea

Anderer server und skalieren boom,

ich teste mal senden ohne pretty print vlt fixed das schon einiges

### Where would this be applied?

Backend

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
@Alex1607 ich assign dich einfach mal aber noch nichts machen, will mal gucken wie sehr es besser wurde ohne pretty print

**Comment by Alex1607** [comment]
Ich habe dafür ein minigames relay erstellt, alle details wie man es benutzt findet ihr in der README.md und ich schreibe euch nochmal was in den Dev Chat auf DC @copyandexecute

**Comment by copyandexecute** [comment]
@Alex1607 du hast die ehre

**Comment by SirKnubble** [comment]
@Alex1607 @copyandexecute "Spectating Game" permanent da fixen (Auftrag von Tim bitti nicht hauen)

**Comment by copyandexecute** [comment]
Wichtig, mach ich
