### ISSUE TITLE
[FEATURE-REQUEST]: Launcher Look and Feel verbessern

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#435]
### Your idea

![grafik](https://github.com/user-attachments/assets/99f4d68c-d567-4a28-95e0-ae1046080c0d)
ich will vermeiden dass alles hier rechts klebt und es smarter gestalten, zb legal-info will ich wo anders hinpacken
quit maybe als kreuz oben rechts?

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
@copyandexecute  Kan ich auch noch machen, wenn wir da dann n Konzept haben... Lass mich auf jeden Fall noch früber schauen falls du's spontan machst! Aber focus du lieber auf Client, da bin ich weniger drinne!

**Comment by copyandexecute** [comment]
Haben nichts gefunden, habe nochmal mit @TimLohrer überlegt
Folgendes Fazit: Wenn etwas kommt was geil ist und wir alle geil finden, dann ändern wirs
anders hat sich ja noch keiner beschwert...

**Comment by Kolpixx** [comment]
Fühl ich nicht zu 100%, aber weils sonst niemand macht. Habe letztens in Streams gehört/gelesen, dass der Launcher unübersichtlich ist .-.
![Image](https://github.com/user-attachments/assets/1b0dd2b6-5f32-463d-8814-91da3b0f1ec4)
https://www.figma.com/design/SrINrijQCEEUmsSy3C7yH1/Launcher-Redesign-v2?node-id=0-1&p=f&t=Tyvgm25Hb6Bmhcu9-0

- Legal-Info Button entfernt, weils schon unter dem Copyright dings ist
- "Servers" Button Entfernt (Sehe halt irgendwie noch nicht den use dafür tbh, aber sonst kann mans ja auch noch lassen)

**Comment by Kolpixx** [comment]
https://www.figma.com/proto/3Hdwehy4f75d5O7qaUVhlV/Launcher-Redesign-v3?node-id=0-3&p=f&t=t1bvVylEQvHAKuy2-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=0%3A3

Oder sowas in der Art. Finde ich garnicht mal so kacke:

https://github.com/user-attachments/assets/85ee3928-38d9-45bf-890f-0133fb00882f

@copyandexecute

**Comment by Kolpixx** [comment]
ja geiles timing halt sorry hahaha
