### ISSUE TITLE
[Bug]: MCReal crasht auf Cytooxien

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#436]
### How to reproduce ?

Wenn man auf Cytooxien.net das MCReal Menü öffnet, dann crasht der Client.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell
Crash Report: https://mclo.gs/OpVpJzp
Logs: https://mclo.gs/CE3SXri#L1275
```

**Comment by Kolpixx** [comment]
Duplicate von https://discord.com/channels/774271756549619722/1293160347275890731

Kann man aber trotzdem offen lassen, damit man es auf GitHub hat oder?

**Comment by TimLohrer** [comment]
[6Zf4mUl.txt](https://github.com/user-attachments/files/17535451/6Zf4mUl.txt)

**Comment by 0x3C50** [comment]
> `applyCustomTextShader$lambda$3$lambda$1`
da stimmt was mit dem text nicht. der loader zeichnet den loading text mit der animation und das scheint nicht zu gehen. 
> `ResettableManagedCoreShader[noriskclient-fabric-utils:nrc_rendertype_text]`
der shader hat aber erfolgreich gebaut

**Comment by 0x3C50** [comment]
![image](https://github.com/user-attachments/assets/b90412a6-3a29-425b-a2fb-8dad46f9b665)
@Kolpixx hattest du shader an, wenn ja welche?

**Comment by Kolpixx** [comment]
> ![image](https://private-user-images.githubusercontent.com/99053360/380807318-b90412a6-3a29-425b-a2fb-8dad46f9b665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMzY4MzcsIm5iZiI6MTczMDEzNjUzNywicGF0aCI6Ii85OTA1MzM2MC8zODA4MDczMTgtYjkwNDEyYTYtM2EyOS00MjViLWEyZmItOGRhZDQ2ZjliNjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE3Mjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTVkMTVlNTZlZGE0YzU0ZmI2NjU2ODZjYTQwN2U3NjIzZTY4NzUzZjMzNjUyMWU2NDAyYjJjMGM3NjQxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YHSFzHlwY7enF6sfUImyvcxmqixqyeRTO65HkQGM0tM) @Kolpixx hattest du shader an, wenn ja welche?

Hatte keinen Shader drinnen. Der Client crasht einfach, wenn man "/mcreal" eingibt oder "MCReal" im Mod Menu auswählt. Das Upload Fenster crasht den Client aber nicht.

**Comment by 0x3C50** [comment]
habs rausgefunden, hängt mit dem resource pack von cytooxien zusammen, die einen shader den wir auch verwenden überschreibt, und somit unseren kaputt macht. können wir beheben. sie selbst wollten aber ihren shader nicht fixen.
