### ISSUE TITLE
[Bug]:  Nitro Boost Cosmetic Free ohne Boost

### ISSUE THREAD

**Issue by einfachyannikDev** [NoRiskClient/issues#440]
### How to reproduce ?

Im Shop befindet sich das Item "Nitro Boost" for Free obwohl man kein Booster ist.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.10

**Comment by einfachyannik** [comment]
@TimLohrer hier

**Comment by TimLohrer** [comment]
@einfachyannikDev is fixed. Danke @enricoxD 😊
