### ISSUE TITLE
[Bug]: Falsches Cape wird im McReal Profil angezeigt

### ISSUE THREAD

**Issue by Kartoffelschaeler** [NoRiskClient/issues#441]
### How to reproduce ?

wenn man in seinem McReal profil seinen skin anschaut hat man das cape von minecraft an, obwohl man eins vom norisk-client ausgewählt hat
https://discord.com/channels/774271756549619722/1294293534089674872/1294293534089674872

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/06a4a13e-d593-493d-9c2b-26b514772e01)
fixed mit nächsten update

**Comment by copyandexecute** [comment]
bitte macht es nichts kaputt
