### ISSUE TITLE
[Bug]: Cape reseted wenn man diese animierten Capes auswählt

### ISSUE THREAD

**Issue by copyandbuild** [NoRiskClient/issues#442]
### How to reproduce ?

wenn man ein Custom cape im launcher ausgewählt hat wird das cape auf das default cape zurückgesetzt wenn man eines der animierten capes auswählt

### Where is this happening?

Client, Shop

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

/

**Comment by copyandexecute** [comment]
Wird mit dem nächsten Update gefixed!
