### ISSUE TITLE
[Bug]: MCReal Profil leere Felder

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#443]
### How to reproduce ?

Weiß nicht, ob das gewollt ist, aber in den letzten 12 Posts sind leere Felder, wenn man an den jeweiligen Tagen nichts gepostet hat. Falls das gewollt ist würde ich es besser finden, wenn man das dort auch irgendwie steht.
![grafik](https://github.com/user-attachments/assets/82371c1e-6483-44a1-a791-8eed929b91ff)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Ahh checke, was würdest du erwarten? maybe nur das datum groß? oder NO POST at ...

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/11065090-8951-49d9-a3be-287ed7a96b01)
