### ISSUE TITLE
[FEATURE-REQUEST]: Profile/Modpack installing

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#446]
### Your idea

Bei Profiles einen Button "Browse Modpacks" mit dem Modrinth Modpacks als Profiles installiert werden können.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by MeisterAH** [comment]
wird nicht kommen wegen Kompatibilitäts problemen

**Comment by BigBrainRobin29** [comment]
Ok
