### ISSUE TITLE
[FEATURE-REQUEST]: Bot auf nrc discord moven

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#45]
### Your idea

Ja.

### Where would this be applied?

Backend

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
@enricoxD wie geht das muss ich da moozi anschreiben?

**Comment by enricoxD** [comment]
@copyandexecute bin mir da unsicher aber ich glaube ja
