### ISSUE TITLE
[Bug]: Verschwundenes costmetic

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#450]
### How to reproduce ?

ich hatte den hotdog anzug aber nun ist er weg

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Bekannt.
Mach bitte ein [Ticket](https://discord.com/channels/774271756549619722/1193515290512863412) im Discord.
