### ISSUE TITLE
[Bug]: Startup Error with client.

### ISSUE THREAD

**Issue by Rotstein007** [NoRiskClient/issues#451]
### How to reproduce ?

Vor einigen Tagen konnte ich den NoRisk Client noch normal starten, jedoch kommt nun immer ein Error beim starten. Sowohl das AppImage als auch die AUR installation haben nicht funktioniert. Ebenfalls habe ich mit paru versucht diesen zu updaten, allerdings war alles aktuell.

-> Falls der Fehler daher kommen sollte, dass ich nicht mehr gewhitelistet bin, dann frag ich mich warum ich das nicht mehr bin...

OS: Manjaro
Kernel: 6.9.12-3
CPU: Ryzen 7 3800x
GPU: RX 6650 xt oc

![Bildschirmfoto vom 2024-10-20 11-42-39](https://github.com/user-attachments/assets/460475d3-6fac-4669-b8ee-9012afb09eec)
![Bildschirmfoto vom 2024-10-20 11-42-30](https://github.com/user-attachments/assets/d664144a-7682-414f-9858-1e17b02cc1c2)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Version (for launcher bugs)

0.5.10

### Relevant log output

```shell
Siehe screenshot
```

**Comment by TigerCrafter** [comment]
Hi @Rotstein007! Einfach anmelden sollte funktionieren. Wenn das nicht funktioniert schau dir mal das an: https://discord.com/channels/774271756549619722/1276193700019437578

**Comment by Rotstein007** [comment]
Ja das hat das problem gelöst, dennoch ist das ja ein weiterhin bestehendes Problem.

**Comment by SirKnubble** [comment]
> Ja das hat das problem gelöst, dennoch ist das ja ein weiterhin bestehendes Problem.

Muss man schauen ob das im nächsten Big Update fixed wird. Glaube schon.

**Comment by SirKnubble** [comment]
> @SirKnubble müsste an zu vielen Token Regens liegen. Meinte Tim zumindest letztens.

?

**Comment by Rotstein007** [comment]
Ja dann müsste das aber trotzdem gefixed werden. Ich werde den [Bug] daher mal offen lassen.

**Comment by SirKnubble** [comment]
Aber warum pingst du mich? 😭

**Comment by SirKnubble** [comment]
Fixed. (Oder so.)
