### ISSUE TITLE
[FEATURE-REQUEST]: McReal Streaks

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#458]
### Your idea

"Ich fände es cool, wenn man eine Streak in Mcreals aufbauen könnte. Beim Profil könnte dann die momentane und die Top Streak gezeigt werden und es könnte Belohnungen geben, wenn man z.B. zehn Tage in Folge rechtzeitig gepostet hat." by istaleigse: https://discord.com/channels/774271756549619722/1299597961004584960

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by Kolpixx** [comment]
Ähnlich wie #426

**Comment by copyandexecute** [comment]
Closing weil https://github.com/NoRiskClient/issues/issues/555
