### ISSUE TITLE
[NRC-EXP] [Bug]: Pets to big

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#461]
### How to reproduce ?

<img width="1809" alt="image" src="https://github.com/user-attachments/assets/562f7576-7fdc-4912-b079-42ead529abc2">
alle pets sind etwas zu groß (inklusive der Trinkvogel)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/3b8d7dca-a0da-41ae-a6d0-2ea78dc9e133)
