### ISSUE TITLE
[NRC-EXP] [Bug]: Tetris buttons are not centered

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#463]
### How to reproduce ?

Die Tetris Buttons sind nicht in der mitte
<img width="738" alt="image" src="https://github.com/user-attachments/assets/88138918-5ad0-47c8-bef7-53a55971c9a8">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TigerCrafter** [comment]
I guess sie sind in der Mitte vom ganzen, also auch mit dem Score usw. links.

**Comment by copyandexecute** [comment]
won't fix fürs erste
