### ISSUE TITLE
[NRC-EXP] [Bug]: Day Counter and Uptime are the same

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#464]
### How to reproduce ?

Der day Counter ist das gleiche wie Uptime 
<img width="698" alt="image" src="https://github.com/user-attachments/assets/f29c74cc-9779-420b-9952-b294946787bc">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
Bei mir gehts

**Comment by MeisterAH** [comment]
das ist eine andere nrc version, oder hast du zugriff auf den experimental branch?

**Comment by Flytzer** [comment]
achso habs nich gesehen sry

**Comment by SirKnubble** [comment]
@MeisterAH Bugs von Experimental sind nochmal special... solang die nicht in Prod kommen ist das fine ig

**Comment by MeisterAH** [comment]
jup, aber hat norisk nicht einmal gesagt wir sollen bugs bei nrc exp sammeln?

**Comment by BigBrainRobin29** [comment]
@MeisterAH noch aktuell?
