### ISSUE TITLE
[NRC-EXP] [Bug]: Hit Boxes doesn't work

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#465]
### How to reproduce ?

Wenn man die Hit Box mod auswählt, wird nur die hitbox von einem selber angezeigt, bei anderen entitys nicht
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/d8e57cb5-fdb8-4e8f-bf5f-b2e7749e1b09">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/8ded023f-6700-4fec-a441-44be775ba253)
hast du das an?

**Comment by MeisterAH** [comment]
ja
