### ISSUE TITLE
[FEATURE-REQUEST]: Render Cosmetic preview over cosmetics

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#466]
### Your idea

Die cosmetic Preview sollte über den eigentlichen cosmetics gerendert werden, sieht imo etwas besser aus.
<img width="789" alt="image" src="https://github.com/user-attachments/assets/2b52681e-2e6b-46ca-8297-9f48f2b337a2">

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
xd...

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/67bd62a2-1341-483d-828f-b49ca5187a0c)
here you go
