### ISSUE TITLE
[FEATURE-REQUEST]: McReal Post Validation

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#467]
### Your idea

Nachdem ein Post geposted wird soll eine KI + (maybe zusätzlich) ein Discord Bot validieren ob der post NSFW ist

Einmal über KI @Alex1607 (welche seite hast du da nochmal empfohlen?)
Und einmal über bot @TimLohrer 

### Where would this be applied?

Client, Backend

### What platforms would this affect?

Not a launcher feature

**Comment by Alex1607** [comment]
Habe dir auf DC alle Infos geschickt 👀

**Comment by copyandexecute** [comment]
- [ ] Post beim hochladen mit OpenAI überprüfen
- [ ] Wenn es flagged trotzdem hochladen aber dann via code den post löschen (damit er nicht nochmal an dem tag hochladen kann)
- [ ] Alle Posts in Discord schicken mit remove button

**Comment by copyandexecute** [comment]
@Greeenman999 kannst du noch den code pls linken?

**Comment by Greeenman999** [comment]
https://github.com/NoRiskClient/noriskclient-backend/commit/423b01343e5ba2bee45d90928255291d8a41e2b5
https://github.com/NoRiskClient/noriskclient-backend/commit/dbad992b3770215c9846fc1b641a06c5bbb738aa
https://github.com/NoRiskClient/noriskclient-backend/blob/55df6380ebe05ccf5c254de460d767a1c27ecafb/backend-base/src/main/kotlin/gg/norisk/backend/router/mcreal/utils/McRealManager.kt#L376-L560
