### ISSUE TITLE
[Bug]: Client reserviert sich mehr RAM als eingestellt

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#469]
### How to reproduce ?

Wenn man z.B. 4GB RAM im Launcher zuweist, dann werden 4448MB RAM reserviert (steht zumindest so im F3 Screen)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.10

**Comment by Flytzer** [comment]
ist normal. kommt darauf an wie viel ram du hast

**Comment by Kolpixx** [comment]
> ist normal. kommt darauf an wie viel ram du hast

Bei Vanilla Minecraft oder bei anderen Clients ist das bei mir aber nicht der Fall

**Comment by Flytzer** [comment]
Das ist komisch

**Comment by Flytzer** [comment]
nur bei nrc ?

**Comment by Kolpixx** [comment]
> nur bei nrc ?

Ja, bei mir schon.

**Comment by Flytzer** [comment]
ist das denn schlimm so weil es sind ja trzdm 4gb ram wenn du verstehst was ich meine

**Comment by Flytzer** [comment]
Ja aber ich glaube da kann man nix machen ich weiß aber nicht genau

**Comment by TimLohrer** [comment]
![Image](https://github.com/user-attachments/assets/e7c982ea-067a-47ec-bc27-7f41cdb25ce2)![Image](https://github.com/user-attachments/assets/0fe1f75f-99e4-4735-a2d3-cfd5c03c5510)
