### ISSUE TITLE
[Bug]: Colossal Enchanted Books haben keine Textur

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#475]
### How to reproduce ?

![grafik](https://github.com/user-attachments/assets/7df1e4e9-95bc-4e7f-bd26-4809f2ece163)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
wont fix (außer es nervt alle)
