### ISSUE TITLE
[Bug]: MCReal - wrong delete Message 

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#481]
### How to reproduce ?

Wenn man die mülltonne anklickt, um das mcreal zu löschen, steht dort "you can't post twice a day" was glaub ich nicht so passend ist ig?
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/05d5a01c-fe81-4430-bc81-40e678235778">

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Empfehlung

**Comment by MeisterAH** [comment]
maybe sowas wie "your post will be away forever"

**Comment by copyandexecute** [comment]
Ich habe mich mit enricoe besprochen, wir lassen erstmal so
