### ISSUE TITLE
[Bug]: Can't scroll up after loading more mods

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#490]
### How to reproduce ?

Man kann nicht mehr hoch scrollen nachdem man auf den "load more" button gedrückt hat bzw es wird nicht mehr das geladen was davor angezeigt wurde. Ist btw bei tps/shaders/datapacks auch so 

video in https://github.com/NoRiskClient/issues/issues/489

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

0.5.11

**Comment by copyandexecute** [comment]
Duplicate of https://github.com/NoRiskClient/issues/issues/489 ?
