### ISSUE TITLE
[Bug NoRisk-EXP]: Tetris Keybinds don't work in 2D Mode

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#491]
### How to reproduce ?

Wenn man bei Tetris im 2D Modus sneakt, oder jumped, passiert nichts

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
fixed mit nächsten update
