### ISSUE TITLE
[Bug]: Pong Crash

### ISSUE THREAD

**Issue by T4bzzz** [NoRiskClient/issues#493]
### How to reproduce ?

hab nur ping pon gespielt amk nach 10 sekunden gecrashet

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Relevant log output

```shell
https://mclo.gs/fLgCYhZ LOG FILE
```

**Comment by SirKnubble** [comment]
Variation: Pong 1v1 crasht fast immer einer von beiden

**Comment by SirKnubble** [comment]
#551
