### ISSUE TITLE
[Bug]: FPS anzeige oben links bugt

### ISSUE THREAD

**Issue by GamecraftTV** [NoRiskClient/issues#495]
### How to reproduce ?

Beim einstellen meiner Overlays 

https://github.com/user-attachments/assets/2ca7016b-a188-49d0-920a-7a0cd3d5ba85

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Relevant log output

```shell
wichtig
```

**Comment by SirKnubble** [comment]
#494
