### ISSUE TITLE
custom crosshair

### ISSUE THREAD

**Issue by JannisJYT** [NoRiskClient/issues#497]
### How to reproduce ?

wen man das custom crosshair aktiwirt und man subway surfers spielt wirt das crosshair nicht ausgeblendet
![Screenshot 2024-11-04 172232](https://github.com/user-attachments/assets/a00d9dd2-fd75-4874-a41f-f05f1d9da5fe)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.11

**Comment by MeisterAH** [comment]
subwayssurfers issues in https://github.com/HGLabor/issues senden
