### ISSUE TITLE
[Bug]: Creeperlighting flackert mit 3d skin layer mod

### ISSUE THREAD

**Issue by derlukaskk2** [NoRiskClient/issues#498]
### How to reproduce ?

3d skin layer mod installienren und creeperlighting auswählen.
hier ein video wie es aussieht (war zu groß für github)
https://cdn.discordapp.com/attachments/774273183804948500/1303034901049643068/2024-11-04_17-34-15.mp4?ex=672a4951&is=6728f7d1&hm=6171ae07549f03107b641a54eec147ed3e9959ae0a3b38ffaf9ca8a600219224&

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

latest

**Comment by Flytzer** [comment]
Video ist nicht verfügbar

**Comment by Flytzer** [comment]
nich mehr relevant i guess?
