### ISSUE TITLE
[Bug]: Fehlendes Power Icon bei SubWay Surfer wenn "Armor Display" an

### ISSUE THREAD

**Issue by MaNameisNick** [NoRiskClient/issues#502]
### How to reproduce ?

![2024-11-04_20 43 53](https://github.com/user-attachments/assets/f9ac7f88-a1e8-4db7-a839-bb4276d11c86)

Wenn man "Display Armor" an hat und in Subway Surfer das Boarditem einsammelt, wird einfach nur eine fehlende Tuxture links angezeigt :)
Ich hoffe das hat hier noch niemand gepostet hat, wenn doch tut es mir leid dass ich es doppelt poste D:
(Ich selbst konnte zumind. noch keinen solchen Bugreport hier auf GitHub finden)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SirKnubble** [comment]
Bugreports in [NoRiskClient/issues](https://github.com/NoRiskClient/issues/issues/new?labels=bug%2Cneeds+validation&projects=github%2F2&template=bug_report.yml&title=%5BBug%5D%3A+)

**Comment by MaNameisNick** [comment]
oh sorry, wusste ich nicht^^
