### ISSUE TITLE
[Bug]: Nachdem man eine Welt gehosted hat verändert sich der Host World Button zu Report Player Button

### ISSUE THREAD

**Issue by TigerCrafter** [NoRiskClient/issues#504]
### How to reproduce ?

Mehr Infos + Original Post: https://discord.com/channels/774271756549619722/1295081665349161042
By flazockt

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TigerCrafter** [comment]
Hab jetzt nicht überprüft, ob es schon fixed ist, denke aber nicht ,da es noch kein Issue dazu gab

**Comment by BigBrainRobin29** [comment]
Ist immer noch valid. Nachdem man eine World hostet und wieder stoppt, verändert sich der Button zu Player Reporting.

**Comment by TigerCrafter** [comment]
> Ist immer noch valid. Nachdem man eine World hostet und wieder stoppt, verändert sich der Button zu Player Reporting.

Danke fürs überprüfen!
