### ISSUE TITLE
[Bug]: TicTacToe raytracing bug

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#505]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/665b9f3b-fbc6-4752-a3a8-c267588abe48)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
(Notiz ist für jedes Minigames)

**Comment by copyandexecute** [comment]
@Greeenman999 wenn du das siehst und gut in mathe bist meld dich mal, ich weiß wo man suchen muss

**Comment by copyandexecute** [comment]
danke grüner mann, kommt mit dem nächsten update!

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/6aeb6a5f-de92-4076-a397-39b1a4e17c51)
leider gibts noch einen bug wodurch die fläche unendlich groß ist

**Comment by copyandexecute** [comment]
@Greeenman999 close erstmal bis du wieder motivation hast

**Comment by Greeenman999** [comment]
:)
