### ISSUE TITLE
[FEATURE-REQUEST]: Join friend

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#506]
### Your idea

Es wäre cool wenn man wen einer von der Freundesliste wen er auf einem Server ist betretten kann.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by MisterDoenerHD** [comment]
wär blöd wenn dadurch dann server ips geleakt werden

**Comment by McCram12** [comment]
Lösung es gibt eine Einstellung die automatisch blockiert das Freunde deinen Server sehen und man mus Manuel für einen Server es auf true setzen

**Comment by BigBrainRobin29** [comment]
Maybe eine Request an den Freund senden, welcher annehmen muss, damit man joinen kann.

**Comment by copyandexecute** [comment]
Wurde jetzt gecodet!
