### ISSUE TITLE
[Bug]: SecondHydra Capes: Missing Elytra Texture

### ISSUE THREAD

**Issue by SirKnubble** [NoRiskClient/issues#507]
### How to reproduce ?

Norsik weiß

**Comment by copyandexecute** [comment]
fixed auf norisk-dev?

**Comment by Technicfan** [comment]
bei mir ist es fixed

**Comment by copyandexecute** [comment]
Ich close es mal!

**Comment by SirKnubble** [comment]
@copyandexecute es ging nicht drum, dass die garkeine haben, sondern sind die einzigen vom Shop die keine Custom Elytra haben xD
