### ISSUE TITLE
[Bug]: Armor Bar (Any feature, thats adjustable in hud menu [Coordinates,..])

### ISSUE THREAD

**Issue by Trick-Sammy** [NoRiskClient/issues#509]
### How to reproduce ?

Most features, that are moveable in the hud, wont align to the right, instead they get missing in the left border and the right border is left with space, this probably collaborates with the scaling issue too

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by MeisterAH** [comment]
bekannt

**Comment by MeisterAH** [comment]
bekannt

**Comment by MeisterAH** [comment]
bakannt

**Comment by SirKnubble** [comment]
@MeisterAH kannsu linken? Ich finds nd mehr

**Comment by SirKnubble** [comment]
#494
