### ISSUE TITLE
[Bug]: Wheel selection is weird

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#510]
### How to reproduce ?

Die Wheel Selection funktioniert nicht richtig 
![image](https://github.com/user-attachments/assets/7cf464d1-dfed-49d6-b8e4-726ada65e8ab)
![image](https://github.com/user-attachments/assets/786a695b-14f9-4b9e-8969-fe892ceba0cc)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
was genau meinst du ?

**Comment by BigBrainRobin29** [comment]
Ich hab nicht dran gedacht, dass man den Mauszeiger auf den Screenshots nicht sieht, aber ich kann die Entities nicht richtig selecten.

**Comment by BigBrainRobin29** [comment]
Liegt wahrscheinlich an Mods, ich versuch später rauszufinden welche.

**Comment by BigBrainRobin29** [comment]
Hab jetzt MiniHud rausgemacht, jetzt gehts, aber wenn ich ein Profile nur mit MiniHud mache gehts auch, also muss eigentlich noch eine andere Mod mit reinspielen.

**Comment by BigBrainRobin29** [comment]
Ich close das jetzt mal, wenn es bei jemandem nochmal auftritt, können wir reopen.
