### ISSUE TITLE
[Bug]: Mac Launcher startet nicht

### ISSUE THREAD

**Issue by Nirnoo** [NoRiskClient/issues#513]
### How to reproduce ?

Wenn ich den Launcher auf meinem 2020 MacBook Pro M1 öffne, kommt nur ein grau-schwarzes Fenster. Der Launcher hat vorher irgendwann mal funktioniert, dann auf einmal nicht mehr. Ich habe auch schon alles gelöscht und mir die neueste Version runtergeladen (Version 0.5.11 (20241101.195445)), aber das ändert auch nichts.
<img width="1440" alt="Bildschirmfoto 2024-11-05 um 19 17 55" src="https://github.com/user-attachments/assets/a6973ba0-3684-4dce-bed1-ea3b0ce14798">

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

Version 0.5.11 (20241101.195445)

**Comment by FelixTPG** [comment]
Habe genau dasselbe MacBook (M1 Pro) und keine Probleme (bis jetzt)

**Comment by MeisterAH** [comment]
hast du bereits all das probiert was in https://discord.com/channels/774271756549619722/1276193700019437578 steht

**Comment by Nirnoo** [comment]
Ich kann irgendwie nicht auf den dc-channel zugreifen oder so, aber habs selber gelöst. Ich musste auch aus der Library alle Folder einmal löschen, die werden nur angezeigt, wenn ich explizit in ihr danach suche. Dann neu runterladen und es geht wieder. Danke für die Hilfe aber
