### ISSUE TITLE
[BUG] Visual Bug und SubwaySurfers bug

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#514]
### How to reproduce ?

Keine ahnung aber Clip

https://github.com/user-attachments/assets/ec44cdf8-4283-4f00-b644-081866add235

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug, Windows

### Version (for launcher bugs)

0.5.11

**Comment by Flytzer** [comment]
Bitti runter ladi die video weil Github rumbugged

**Comment by RadFlunder** [comment]
Hey! Subwaysurfer Bugs haben hier nichts zu suchen, bitte auf https://github.com/hglabor/issues/issues.^^ Brauchst du aber nicht zu reporten, ist schon bekannt und kommt auch mit dem nächsten update.
