### ISSUE TITLE
[Bug]: Äußere skin layer ändern

### ISSUE THREAD

**Issue by FabiHQ** [NoRiskClient/issues#518]
### How to reproduce ?

Wenn ich ingame durch das wheel meinen skin ändern möchte bleibt die zweite schick gleich. Heißt: wenn ich zum beispiel ein wheinachtsskin mit einer Mütze habe (die auf der 2. Layer liegt) und ich dann zu einem anderen skin wechsle hat er immernoch die wheinachtsmütze an und di3 richtige 2. Layer fehlt.

Wenn das nicht beheben bar ist bitte ändern es so das wenn man die Welt oder den Server verlässt (also nicht direkt game schließen) und man wieder joint das es dann gefixt ist.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
Bei mir gehts :)

**Comment by SirKnubble** [comment]
@FabiHQ Mod? (3D Skin Layers)

**Comment by Flytzer** [comment]
Ja liegt an 3D Skin Layers wenn du die installiert hast pack sie mal raus und probiere mal ohne die mod

**Comment by SirKnubble** [comment]
Reopen falls es an was anderen liegen sollte!
