### ISSUE TITLE
[FEATURE-REQUEST]: minecraft version ändern

### ISSUE THREAD

**Issue by FabiHQ** [NoRiskClient/issues#519]
### Your idea

Im launcher kann ich nur die 1.21 spielen anstatt die neuste 1.21.3 außerdem sind ältere sowie snapshots nicht möglich bitte fixen.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows

**Comment by SirKnubble** [comment]
Wird es nicht geben
