### ISSUE TITLE
[Bug]: McReal 

### ISSUE THREAD

**Issue by Lowkey-Louis** [NoRiskClient/issues#520]
### How to reproduce ?

wenn man ein McReal machen möchte und die mod essentials beutzt kommt dieser fehler und es funktioniert nicht https://prnt.sc/fQS-2GRdcvpt
Wenn man dann in gespeicherten screenshots geht wird das angezeigt https://prnt.sc/eQLebge_pYke und es wird kein McReal hochgeladen.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SirKnubble** [comment]
Essential ist nicht mit dem NoRiskClient kompatibel.
