### ISSUE TITLE
[Bug]: Tetris: Arrow-keys not working in 2D

### ISSUE THREAD

**Issue by SirKnubble** [NoRiskClient/issues#522]
### How to reproduce ?

Seit dem Update kann man Tetris in 2D nicht mehr steuern D:

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Noch valid?

**Comment by BigBrainRobin29** [comment]
Bei mir geht's jetzt.
