### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lowkey-Louis** [NoRiskClient/issues#523]
### How to reproduce ?

ich habe versucht den acc zu wechseln aber wenn ich jetzt den luncher starte passiert nix mehr 

https://prnt.sc/tp_tSEnTq8Ie

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

nicht einsehbar

_No response_

**Comment by MeisterAH** [comment]
hast du schon alles von hier versucht? https://discord.com/channels/774271756549619722/1276193700019437578
