### ISSUE TITLE
[Bug]: Emote Bug

### ISSUE THREAD

**Issue by RadFlunder** [NoRiskClient/issues#524]
### How to reproduce ?

Wenn man einen endlichenEmote(z.b. waving) nach einem unendlichen Emote(z.B sitonhead) wird nach Ende des endlichen Emotes der unendliche beendet. Im Video erkennt mans nochmal:

https://files.fm/u/ashhnm95s6#/view/5mtd84tank

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by 0x3C50** [comment]
die perspektive sollte sich eigentlich überhaupt nicht in first person ändern? das wheel ändert nur in f5 wenn die einstellung an ist, mehr macht das nicht

**Comment by 0x3C50** [comment]
btw: das unendliche emote wird nicht beendet, es wird neu gespielt wenn dus vom wheel aus neu anmachst. der eigentliche bug existiert nicht, aber das f5 ding ist ein wenig seltsam

**Comment by 0x3C50** [comment]
![image](https://github.com/user-attachments/assets/86fb958c-5727-4153-b008-1de2184dd4e0)
:skull: vielen dank norisk
