### ISSUE TITLE
[Bug]: Tetris, tic tac toe, profil info nicht nutzbar

### ISSUE THREAD

**Issue by VirtuousPanda15** [NoRiskClient/issues#533]
### How to reproduce ?

Wenn ich mich im Chat befinde und auf andere Spieler drauf clicke wird die Auswahl rechts oben und zum groß teil außerhalb halb des Bildschirm angezeigt

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

**Comment by SirKnubble** [comment]
Duplicate #287
