### ISSUE TITLE
[Bug]: Fps Mod verschiebt sich nicht korrekt

### ISSUE THREAD

**Issue by farmer-pj** [NoRiskClient/issues#534]
### How to reproduce ?

https://youtu.be/h6KwIuNxrok

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.11

### Relevant log output

```shell
In der Log wird nichts relevantes dazu angezeigt.
```

**Comment by farmer-pj** [comment]
Passiert auch bei anderen Mods. Es passiert wenn man die Mods kleiner als Standartgröße stellt und dann zum Bildschirmrand zieht

**Comment by SirKnubble** [comment]
#494
