### ISSUE TITLE
[Bug]: Unsichtbarer Hintergrund

### ISSUE THREAD

**Issue by Lauch2777** [NoRiskClient/issues#535]
### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Relevant log output

```shell
Wenn man Minecraft strtet hat man ja den Landschafts Hintergrund bei mir war der weg und ich habe meinen Normalen Desktop und meine Offenen fenster gesehen
```

**Comment by SirKnubble** [comment]
Hast du die "Blurred Window" Mod drin?

**Comment by SirKnubble** [comment]
@Lauch2777 ?

**Comment by Lauch2777** [comment]
Ja habe ich, entschuldigung für die späte antwort

**Comment by Lauch2777** [comment]
> schon versucht, custom texturepacks zu disablen?

Ja hab ich der fehler war eine mod die ich drin hatte entschuldigung für diesen unnötigen report
