### ISSUE TITLE
[Bug]: Chroma Button hat keine Funktion bei Enchantment Glint

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#536]
### How to reproduce ?

Referenz: https://discord.com/channels/774271756549619722/1304953410524545076

Der Chroma Button bei dem Enchantment Glint Effekt toggelt nichts.  

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
Ist aktuell so gewollt
