### ISSUE TITLE
[Bug]: Tic Tac Toe Crash beim spectaten/spielen

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#540]
### How to reproduce ?

Crash Report ist in folgendem Video auf Discord:

https://github.com/user-attachments/assets/bbf5c315-ffb9-43fc-b267-8f9862d47d48

https://discord.com/channels/774271756549619722/1304500394163961856/1304508318903173221

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
Wie reproduzieren?
