### ISSUE TITLE
[Bug]: Cosmetic GUI player displays active emotes from other players

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#543]
### How to reproduce ?

Kavatch hat hotdog an, macht 5head emote und der hotdog in meinem gui macht die transformation auch
![Image](https://github.com/user-attachments/assets/6f1e28ad-1eca-4953-91de-91ef1abbeea8)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell

```

**Comment by 0x3C50** [comment]
fixed
