### ISSUE TITLE
[FEATURE-REQUEST]: Launcher saves skins

### ISSUE THREAD

**Issue by MisterDoenerHD** [NoRiskClient/issues#545]
### Your idea

Gibts schon von Mojang, das halt in nrc
![IMG_7422](https://github.com/user-attachments/assets/c70203d9-3276-485e-b1bc-06f6980c4779)

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by SirKnubble** [comment]
Also, in NRC gibts das ja schon.
Nur nicht im Launcher.

**Comment by copyandexecute** [comment]
Ne, will das im Client lassen
