### ISSUE TITLE
[Bug]: armor trim funktioniert nicht

### ISSUE THREAD

**Issue by FabiHQ** [NoRiskClient/issues#546]
### How to reproduce ?

Als ich einen enchantete Diamanten rüstung mit dem eye (also dem end armor trim) armor trim aufwerten wollte habe ich meine ganze rüstung mit emeralds und dem trim ausgelegt. Jedoch wurde als ich f5 drückte nur die Hose verändert (als ich die volle rüstung an hatte) außerdem wurde der character im Inventar ichtig angezeigt. Nur wenn ein rüstungsteil angelegt ist wir auf diesem der trim geladen.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by BigBrainRobin29** [comment]
Ist valid, aber übertrieben weird. Ich versuch grad herauszufinden, wann genau es passiert, weil es da anscheinend einige Regeln gibt.

**Comment by BigBrainRobin29** [comment]
Ich glaube, wenn man eine trimmed Chestplate und trimmed Schuhe hat, dann verschwindet das Trim auf der Hose. Vielleicht finde ich morgen noch andere Sachen.

**Comment by SirKnubble** [comment]
Reopen von #363 ja juhu

**Comment by SirKnubble** [comment]
@FabiHQ keine TPs oder Shader drin?

**Comment by FabiHQ** [comment]
Schon shader drin aber nicht aktiviert hab shader noch ausgemacht hat trotzdem nicht funktioniert.
Bei TPs das selbe

**Comment by SirKnubble** [comment]
Move to old issue -> https://github.com/NoRiskClient/issues/issues/363
