### ISSUE TITLE
[Bug]: Crossair Pfeil dicke einstellen geht nicht 

### ISSUE THREAD

**Issue by NiyogotNrc** [NoRiskClient/issues#547]
### How to reproduce ?

Hab versucht bei dem Pfeil crossair die dicke zu veränder und es ist nicht passiert.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by copyandexecute** [comment]
Kanns nicht reproduzieren

**Comment by Flytzer** [comment]
https://youtu.be/J9FANBu1d5I hier ist es reproduced

**Comment by SirKnubble** [comment]
hä @copyandexecute du wählst "ARROW" aus und verändert "THICKNESS" slider und der ist einfach useless xD

**Comment by copyandexecute** [comment]
fixed auf norisk-dev
