### ISSUE TITLE
[Bug]: Scoreboard updates sometimes kick player from game

### ISSUE THREAD

**Issue by Alex1607** [NoRiskClient/issues#548]
### How to reproduce ?

Sometimes when the scoreboard updates, it results in the client disconnecting from the game. It most likely a server bug, but most clients do not have the same issue / fixed it. 
To reproduce: Play KnockPVP on Greev and get a few kills / die a few times. 
Logs: https://mclo.gs/K7EhlMe
There also already is a mod which can fix it: https://modrinth.com/mod/cannot-remove-from-team-workaround

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
ja i guess
