### ISSUE TITLE
[Bug]: Free Cape's verschieben sich beim sneaken nicht mit

### ISSUE THREAD

**Issue by MaNameisNick** [NoRiskClient/issues#549]
### How to reproduce ?

Normal:

![2024-11-11_22 02 25](https://github.com/user-attachments/assets/324bcc63-d925-4931-8d79-41820cd6cdc0)

Sneak:
![2024-11-11_22 02 37](https://github.com/user-attachments/assets/41f98446-1867-4016-bd87-b1b82e55f808)
![2024-11-11_21 57 10](https://github.com/user-attachments/assets/edaea010-63bd-499c-8c59-420c38672ab6)

Ich hoffe das hat hier noch niemand gepostet hat, wenn doch tut es mir leid dass ich es doppelt poste D:
(Ich selbst konnte zumind. noch keinen solchen Bugreport hier auf GitHub finden)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SirKnubble** [comment]
Was genau meinst du? Konnte das Bild bei mir nicht nachstellen.

Hast du Mods installiert? (bspw. Wavy Capes)

**Comment by MaNameisNick** [comment]
Musst eigentlich nur irgendein Cape im NoRisk Launcher auswählen beim starten.
Ich habe keine zusätzlichen Mods installiert, die irgendwie mit Capes interagieren, ich kann dir aber meine zusätzlich installierten Mods auflisten, neben den schon vorher installierten NoRisk Mods:

- ChatHead (von dzwdz, Fourmisain)
- BetterF3 (von cominixo und TreyRuffy)
- 3D-Skin-Layer (von tr7zw)

**Comment by MaNameisNick** [comment]
Oh wow, ich merk aber selber gerade schon, dass es sich irgendwie von selbst gefixt hat.... Jetzt ist es bei mir auch nicht mehr verbuggt, sehr seltsam
