### ISSUE TITLE
[FEATURE-REQUEST]: Custom Kacheln für Nrc/Freunde Server

### ISSUE THREAD

**Issue by Kartoffelschaeler** [NoRiskClient/issues#556]
### Your idea

es gibt beim Multiplayers tab custom kacheln wo server angezeigt werden. Da könnte man aktuelle von freunden gehostete Welten oder auch HGLab oder so anzeigen

### Where would this be applied?

Client, Launcher

### What platforms would this affect?

Windows

**Comment by copyandexecute** [comment]
wird doch nicht kommen weil gruselig außer @Alex1607 findet ein tcp problem

**Comment by copyandexecute** [comment]
Kommt! mit nächsten update
