### ISSUE TITLE
MCReal kann nicht gelöscht werden

### ISSUE THREAD

**Issue by EinfachEhrenlos** [NoRiskClient/issues#56]
### What happened?

Ich kann mein hochgeladenes MCReal nicht löschen
![MCreal del](https://github.com/NoRiskClient/issues/assets/76598540/20208643-0317-4fc9-88f4-b92e78914cad)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by TimLohrer** [comment]
Ich close das erstmal, bitte bei erneutem auftreten wieder öffnen @EinfachEhrenlos
