### ISSUE TITLE
[Bug]: Mehrere Minigames auf einmal

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#561]
### How to reproduce ?

Wenn man jemanden zum spielen von mehreren Minigames auffordert, kann man ein zweites und auch ein drittes Minigame nebeneinander spielen. Alle Minigames können dabei gesteuert werden. 

1. Jemanden zu einem Minigame einladen. Egal ob per cmd oder Wheel
2. eine zweite invite senden. (/nrc minigames SPIEL invite USER) kann wiederholt werden
3. die andere Person kann im chat alle anfragen annehmen

![2024-11-16_16 01 45](https://github.com/user-attachments/assets/e5fe4192-48c9-4369-abad-dd8fd5058e6c)
![discord image Antowka](https://github.com/user-attachments/assets/1b1e70af-a844-448a-9b2f-bac1c5d1de9a)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
Feature
