### ISSUE TITLE
[Bug]: Can't join server when a geyser/floodgate bedrock player is online

### ISSUE THREAD

**Issue by AlexDerProGamer** [NoRiskClient/issues#563]
### How to reproduce ?

Ich habe einen 1.21.3 Fabric Server mit Floodgate und Geyser. Wenn kein Bedrock Spieler auf dem Server ist, kann ich ohne Probleme beitreten. Aber wenn ein Bedrock Spieler online ist, dann wird man mit folgendender Message gekickt:

![image](https://github.com/user-attachments/assets/4744e9b8-ce5d-4472-8e97-a74d2dc2c7ad)

Ich denke es liegt anm Handling von Custom NRC+ Nametags

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Version (for launcher bugs)

---

### Relevant log output

```shell
[Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/clientbound/minecraft:player_info_update (class_2703) was larger than I expected, found 1 bytes extra whilst reading packet clientbound/minecraft:player_info_update
```

**Comment by BigBrainRobin29** [comment]
Ist bei mir nicht so.

**Comment by BigBrainRobin29** [comment]
@AlexDerProGamer noch aktuell?

**Comment by AlexDerProGamer** [comment]
Ich glaube schon, aber ich weiß es nicht. Bin auf Paper geswitched

**Comment by BigBrainRobin29** [comment]
Dann close ich das hier mal, wenn nochmal jemand das Problem hat reopen
