### ISSUE TITLE
[FEATURE-REQUEST]: Select custom default profile

### ISSUE THREAD

**Issue by MeisterAH** [NoRiskClient/issues#567]
### Your idea

Wäre imo ganz bequem wenn man immer sein default profile auswählen kann und es nicht immer das eine ist 
<img width="707" alt="image" src="https://github.com/user-attachments/assets/90c025ed-ec25-462d-80f4-d7794e21c17b">

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Das macht wenig sinn, weil das nur dafür da ist, dass man immer eins hat. Das default hat keine bedeutung
