### ISSUE TITLE
[Bug]: game start error

### ISSUE THREAD

**Issue by McCram12** [NoRiskClient/issues#571]
### How to reproduce ?

mein game crsht die gnaze zeit mit verschiedenen error (immer zwei und sehr fielen warnings) error beim  ersten mal: Uncaught exception in thread "DefaultDispatcher-worker-5"

Failed to disconnect from discord ipc: lateinit property ipc has not been initialized

eros vom zweiten mal: Uncaught exception in thread "DefaultDispatcher-worker-6" kotlin.UninitializedPropertyAccessException: lateinit property mcClientCoroutineScope has not been initialized at knot/net.silkmc.silk.core.task.MinecraftClientSyncKt.getMcClientCoroutineScope(MinecraftClientSync.kt:18) ~[silk-core-1.10.7-bd65c9a7469083c.jar:?] at knot/gg.norisk.utils.extensions.ResultExtensionsKt.onSuccessSync(ResultExtensions.kt:32) ~[NoRiskClient-Fabric-Utils.jar:?] at knot/gg.norisk.utils.extensions.ResultExtensionsKt.onSuccessSync$default(ResultExtensions.kt:5) ~[NoRiskClient-Fabric-Utils.jar:?] at knot/gg.norisk.cosmetics.networking.CosmeticApiManager$fetchCurrentWardrobe$$inlined$mcCoroutineTask-ML416i8$default$1.invokeSuspend(CoroutineTask.kt:56) ~[NoRiskClient-Cosmetics.jar:?] at knot/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?] at knot/kotlinx.coroutines.Dispat

Failed to disconnect from discord ipc: lateinit property ipc has not been initialized

fü ganzen zweiten log: https://mclo.gs/lEPROzg

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by BigBrainRobin29** [comment]
Update mal Wavey Capes und wenn es dann immer noch nicht geht, schick mal den crash report.

**Comment by McCram12** [comment]
Ich habe alle mods weg und uninstall und Install gemacht jetzt sagt er kein Zugriff obwohl ich in der Beta bin

**Comment by BigBrainRobin29** [comment]
Vielleicht neu anmelden. Das hilft da meistens.

**Comment by BigBrainRobin29** [comment]
Ok, dann weiß ich auch nicht weiter.

**Comment by SirKnubble** [comment]
@McCram12 noch aktuell?

Vollständiger uninstall, also auch AppData?

**Comment by McCram12** [comment]
Es geht wieder.
