### ISSUE TITLE
[Bug]: Friend list not long enought GUI scale 3

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#572]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/bbd0422f-d9a6-4c48-a302-746747f09f59)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TigerCrafter** [comment]
#327

**Comment by TigerCrafter** [comment]
Duplicate of: #327

**Comment by Flytzer** [comment]
nicht ganz duplicate weil ich kann ja scrollen nur nich lang genug.

**Comment by TigerCrafter** [comment]
Achso du meinst dass nicht alle Friends gedisplayed werden?

**Comment by Flytzer** [comment]
Ja

**Comment by Flytzer** [comment]
also ich hab so ca 70 freunde bei nrc und mittlerweile egalwelches gui ich drinne hab werden die friends nicht mehr displayed

**Comment by copyandexecute** [comment]
Hab ich schon probiert zu fixen :( Ich versuchs nochmal

**Comment by copyandexecute** [comment]
fixed auf norisk-dev bitte testen
