### ISSUE TITLE
[Bug]: Nametag 

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#573]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/bac87765-79fc-445c-aea4-7f3081c605e8)
bin halt server gejoint 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by MeisterAH** [comment]
wenn du dich gerade hinstellst /in eine andere Richtung schaust, ist es dann immernoch so?

**Comment by TigerCrafter** [comment]
Ist das nur mit NRC+ Nametag Rendering?

**Comment by Flytzer** [comment]
hab noch nix getestet ausser wenn ich woanders hinschau das ist dann so das es sich mit bzw nicht mitbewegt

**Comment by Flytzer** [comment]
war auf twerion und da is das bei anderen server nich glaube

**Comment by SirKnubble** [comment]
#452
