### ISSUE TITLE
[Bug]: "Iceberg" Mod nicht auffindbar

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#574]
### How to reproduce ?

Ich kann die [Iceberg library](https://modrinth.com/mod/iceberg/versions) nicht im Discover tab finden. Wenn ich bspw. versuche [Advancement Plaques](https://modrinth.com/mod/advancement-plaques) zu installieren, dann kriege ich folgendede Fehlermeldung:
![grafik](https://github.com/user-attachments/assets/d6007a1d-4f1f-4e60-9b9a-03f4698ebd41)

Verstehe nicht was inkompatibel ist. Alles funktioniert auch, wenn ich die Mods einfach als custom mod hinzufüge.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.13

**Comment by Kolpixx** [comment]
Check Check danke

**Comment by SirKnubble** [comment]
@BigBrainRobin29 alle, die rot sind, sind Inkompatible.
Heißt führt zu crash.
