### ISSUE TITLE
[Bug]: Alle Kurzlinks im Legal-Info Menü öffnen sich nicht da wo sie es sollen

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#576]
### How to reproduce ?

Im Legal-Info Menü klickt man auf einen der Links und wird in eine Webview2 Ansicht weitergeleitet, anstatt beispielsweise in einen externen Browser, so wie es in den Addons geregelt ist. (Bei den Legal-Infos öffnet sich bei einem Mittelklick nichts)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by BigBrainRobin29** [comment]
Soll das so?

**Comment by TimLohrer** [comment]
Das soll so, weil browser nicht mit linux etc immer geht und bei dem legal stuff müssen wir sicherstellen, dass das geht
