### ISSUE TITLE
[FEATURE-REQUEST]: Clone Profiles

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#578]
### Your idea

Eine Möglichkeit Profiles zu klonen, um neue Mods hinzuzufügen, ohne das Default Profile zu verändern.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TigerCrafter** [comment]
Export + Import geht nicht?

**Comment by BigBrainRobin29** [comment]
```
            // Check if profile already exists -> replace if id is matching
            if launcher_profiles
                .experimental_profiles
                .iter()
                .any(|profile| &profile.id == &import_profile.id)
            {
                launcher_profiles.experimental_profiles.iter_mut().find(|p| p.id == import_profile.id).unwrap().mods = import_profile.mods;
            } else {
                launcher_profiles.experimental_profiles.push(new_profile);
            }
```
Wird replaced, was ja auch Sinn macht, aber dann ist ein Clone Feature auch wichtig.

**Comment by copyandexecute** [comment]
@TimLohrer (same here du bist busy) aber das wäre auch sehr geil

**Comment by BigBrainRobin29** [comment]
Habt ihr euch schon angeschaut was ich da gecodet hab? (https://github.com/NoRiskClient/noriskclient-launcher/pull/82)

**Comment by BigBrainRobin29** [comment]
Ist im nächsten Update drin (ig)
