### ISSUE TITLE
[Bug]: McReal Token abfrage nrc 

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#579]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/dcef0df4-07ba-40c5-8ca4-d20cda60453e)
Ist passiert bei ner vm als ich das erste mal in die settings gegangen bin. Falls fragen oder zugriff auf die vm benötigt einfach fragen schicke dann einlogdaten (nur das team und @enricoxD )

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Bitte keine vm errors
