### ISSUE TITLE
[Bug]: The accepted friend request message is little broken

### ISSUE THREAD

**Issue by BlueSneakers** [NoRiskClient/issues#58]
### What happened?

![Screenshot_2023-12-29_171008](https://github.com/NoRiskClient/issues/assets/76217953/2f8d0c4e-dd07-4edb-a13a-bf41230a6850)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Edit: Fast alle %s messages bei friends sind glaube ich kaputt

**Comment by TimLohrer** [comment]
Fixed in Friends 2.0.0
