### ISSUE TITLE
[FEATURE-REQUEST]: Rechtsklick zum cyclen in die andere Richtung bei Moduloptionen

### ISSUE THREAD

**Issue by brentspine** [NoRiskClient/issues#589]
### Your idea

![image](https://github.com/user-attachments/assets/b103b84e-7d97-4f45-b77e-f3e993d302ed)

Durch klicken auf das "Dark Panel" Feld kann man durch die Background-Optionen cyclen. Ich finde es intuitiv, dass man mit Rechtsklick in die andere Richtung cyclen sollen könnte. 

Keine hohe Priorität, nur Quality of Life

### Where would this be applied?

Client

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by brentspine** [comment]
Bei Coordinates könnte man das Padding ein bisschen erhöhen

![image](https://github.com/user-attachments/assets/f5a27807-d7ff-42bc-b194-564021450775)

**Comment by copyandexecute** [comment]
Coole Idee, mach ich dir

**Comment by copyandexecute** [comment]
kommt auf norisk-dev
