### ISSUE TITLE
[Bug]: NoRisk Client icon is going through walls

### ISSUE THREAD

**Issue by BlueSneakers** [NoRiskClient/issues#59]
### What happened?

https://github.com/NoRiskClient/issues/assets/76217953/ced8c5d9-09c5-4ab7-9176-a27394696432

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
Haben was ähnliches gefixt, kp ob das das auch fixt.. Wir hoffen 👍

**Comment by TimLohrer** [comment]
<https://github.com/NoRiskClient/noriskclient-fabric/commit/022f125a21a46d0a1defc8449b5ec67e87460242>
