### ISSUE TITLE
[Bug]: Tetris Spiel schließt sich ohne Anfrage auf Rematch

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#590]
### How to reproduce ?

zum Teil schließt sich das Spiel random während des Spiels (Ein genauer Zeitpunkt, also Punktestand oder Zeit, konnten wir nicht ausfindig machen)
beim beenden der Runde, also durch verlieren, wird das UI geclosed, ohne nach einem Rematch zu fragen

Referenz:
https://discord.com/channels/774271756549619722/1264524228615602249/1309196675645964418

Mögliche Lösung von Kavatch:
```
dass ist weil wir ja jetzt die connection closen was dafür führt das du auf client seite wohl auch das game direkt zu machst
Ich kann das einfach wieder entfernen oder du baust einen check clientseitig ein
```

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
@Alex1607 das ist nicht mehr valid oder?

**Comment by Alex1607** [comment]
> @Alex1607 das ist nicht mehr valid oder? 

Ja sollte fixed sein
