### ISSUE TITLE
[Bug NORISK-EXP]:  Keine Anmeldung möglich (non whitelisted o.ä.)

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#591]
### How to reproduce ?

Durch anklicken des Exp Buttons in den Settings wird einen normale Anmeldung getoggelt, um einen EXP Token zu generieren.
Danach folgt eine der beiden Fehlermeldungen:
![Screenshot 2024-11-20 213618](https://github.com/user-attachments/assets/5a603b07-d81d-4369-98b6-82a719f2fe3c)
![Screenshot 2024-11-21 174035](https://github.com/user-attachments/assets/3aaeaead-fe5e-48af-a88f-931edc67b581)

Auffälligkeiten:
- nach Anmeldung für EXP Token Generierung erscheint non whitelisted auch nach löschen der Config (1. Bild tritt manchmal auf)
- "experimental": null (2. Bild)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by Flytzer** [comment]
is fixed ^^
