### ISSUE TITLE
[Bug]: Ich habe Betacode Freunde eingegeben aber ich habe keine Betaacess bekommen.

### ISSUE THREAD

**Issue by Boomer202122** [NoRiskClient/issues#594]
### How to reproduce ?

Es waren noch Betaplätze frei. Ich habe den Code Freunde eingegeben Dort stand keine Bestätigung bekommen. Habe ich beta oder nicht? Heiße Ingame ZUckerGElenk68. Es ist ein Discord Bug.

### Where is this happening?

Backend

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Nein, hast du nicht.
Dann war der Code wahrscheinlich abgelaufen.
