### ISSUE TITLE
[Bug]: Website inconsistency

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#598]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/e47ffc2b-2df1-4a93-a033-1b52efef674d)
1. Der Light Button ist verschoben
2. Die anderen Buttons haben cursor: pointer, aber der Light Button nicht.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by SirKnubble** [comment]
Ultra-Low-Prio, moved to [Suggestion](https://discord.com/channels/774271756549619722/1306068130027540490)
