### ISSUE TITLE
[Bug]: Discord Bot is broken

### ISSUE THREAD

**Issue by BlueSneakers** [NoRiskClient/issues#60]
### What happened?

![Screenshot 2023-12-29 211953](https://github.com/NoRiskClient/issues/assets/76217953/e8a91bf6-ea1d-47c8-a65d-5c5410f85160)

### Where is this happening?

Backend

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by BlueSneakers** [comment]
it is not working in general*

**Comment by TimLohrer** [comment]
hmmmmm idk, das muss miraculix fixen ig

**Comment by TimLohrer** [comment]
@copyandexecute kannst du da mal mit miraculix reden?

**Comment by TimLohrer** [comment]
@enricoxD @copyandexecute ich nutze das hier mal auch direkt für das splitten in die verschiedenen bots, @enricoxD ich gebe dir die tokens dann per dm

**Comment by enricoxD** [comment]
@TimLohrer werden jetzt neue Bots erstellt oder wie ist der Plan?

**Comment by TimLohrer** [comment]
> @TimLohrer werden jetzt neue Bots erstellt oder wie ist der Plan?

Jap, ich mache das gleich
