### ISSUE TITLE
[Bug]: MacOS low FPS when punching

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#602]
### How to reproduce ?

Referenz: https://discord.com/channels/774271756549619722/1310335356012335186

Daten: M1 Chip

Avg: 200 FPS
wenn geschlagen wird: ca 30 FPS

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

**Comment by MeisterAH** [comment]
einf runtime löschen hats gefixed
