### ISSUE TITLE
[FEATURE REQUEST]: Deleting capes

### ISSUE THREAD

**Issue by ProxylacherDev** [NoRiskClient/issues#603]
### Your idea

A feature to remove uploaded capes completely frome the cape section

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@enricoxD @TimLohrer idee? oder meinung

**Comment by TimLohrer** [comment]
Oh sry habe jz schon commit hier mapped, close das hier dann mal, obwohl eig das andere das duplicate ist LOL
