### ISSUE TITLE
[Bug]: Custom NameTags werden nicht gerendert bei aktivem Shader

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#604]
### How to reproduce ?

wenn man nen Shader, beispielsweise den Subway Surfers Shader anmacht, dann verschwinden alle custom name tags oder werden schwarz, je nach Shader

![image](https://github.com/user-attachments/assets/20457d50-b278-41d9-8c6e-bf7f69bd1645)
![image](https://github.com/user-attachments/assets/3c237927-2cd0-4f9a-b820-852629092a95)

https://discord.com/channels/774271756549619722/1095740246802579487/1310986683906523157

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Adde ich mal hier https://github.com/NoRiskClient/issues/issues/452
