### ISSUE TITLE
[Bug]: Tetris Anzeige der Nächsten Blöcke stimmen nicht.

### ISSUE THREAD

**Issue by Grosserkill4** [NoRiskClient/issues#605]
### How to reproduce ?

Wenn ich Tetris normal Spiele Stimmen die Blöcke welche Rechts angezeigt werden nicht immer mit dem kommenden block überein. 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by SirKnubble** [comment]
Ja, die sind aktuell noch randomized. 
![image](https://github.com/user-attachments/assets/0abace7a-576a-4c72-ac6d-1c2d88c63d9b)
https://cdn.discordapp.com/attachments/1308484441865326722/1308528803550597192/ApplicationFrameHost_5lD9n0Tuv5.mp4?ex=6747806a&is=67462eea&hm=313e31ad4f0f4614e4fbb8e600db8734770659a6072464d1d06fb2eeb12aa899&

**Comment by SirKnubble** [comment]
@PSJahn

**Comment by copyandexecute** [comment]
Hat @Alex1607 jetzt für euch gefixed!
