### ISSUE TITLE
[FEATURE-REQUEST]: Cosmetic Kaufbestätigung

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#606]
### Your idea

Bevor man ein Cosmetic kauft sollte nochmal ein Bestätigungsscreen kommen mit der Summe und maybe den Cosmetics die man kauft. So könnten Fehlkäufe wie dieser hier vermieden werden: https://discord.com/channels/774271756549619722/1311011067916324875 (Discord Ticket falls das noch offen ist)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Ja why not

**Comment by copyandexecute** [comment]
bitte auf norisk-dev testen

**Comment by Kolpixx** [comment]
> bitte auf norisk-dev testen

Passt alles!
