### ISSUE TITLE
[FEATURE-REQUEST]: Launcher soll Resourcepacks/Shaders direkt runterladen/entfernen

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#615]
### Your idea

Zurzeit muss man Minecraft erst (neu-)starten, damit der Launcher Resourcepacks oder Shader runterlädt. Fände es super, wenn der Launcher sie direkt runterlädt/entfernt. Ist halt etwas umständlich Minecraft immer neustarten zu müssen, wenn man ein Resourcepack/Shader runterladen will.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by copyandexecute** [comment]
@TimLohrer das hast du gecodet oder?

**Comment by Flytzer** [comment]
Fetig i guess?

**Comment by TimLohrer** [comment]
> Fetig i guess?

Yes, danke
