### ISSUE TITLE
[Bug]: Knockback not working

### ISSUE THREAD

**Issue by Technicfan** [NoRiskClient/issues#616]
### How to reproduce ?

Enchant a sword with any level of knockback and attack a mob.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
valid  btw

**Comment by copyandexecute** [comment]
Liegt am stupid-enchantments, kann man über launcher ausschalten
aber fixe es!

**Comment by copyandexecute** [comment]
fixed auf norisk-dev bitte testen @NoRiskClient/bughunter

**Comment by copyandexecute** [comment]
kommt mit nächsten update auf 1.21
