### ISSUE TITLE
[FEATURE-REQUEST]: Reset perspective after emote

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#617]
### Your idea

Wenn man ein Emote startet, geht man automatisch in F5 und wäre gut wenn man danach wieder in die alte Perspective zurück geht.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Ist eigentlich der fall außer bei den infinite emotes, gucke mal rein

**Comment by copyandexecute** [comment]
okay da ist echt was bruch gg

**Comment by copyandexecute** [comment]
bitte auf nrc-dev den fix testen @NoRiskClient/bughunter

**Comment by BigBrainRobin29** [comment]
ist fixed
