### ISSUE TITLE
[Bug]: Skin ingame anpassen und das confirmen noch nicht translated

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#618]
### How to reproduce ?

![image](https://github.com/user-attachments/assets/308a88ca-be0d-4ce3-bf12-12750afe68a1)
![image](https://github.com/user-attachments/assets/c7a63f98-aa78-4595-b190-8a6e96f931a9)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
@copyandexecute

**Comment by TigerCrafter** [comment]
Könntest du auch gerne in #480 hinzufügen

**Comment by Flytzer** [comment]
danke, tim hat gesagt soll das uploaden ^^
