### ISSUE TITLE
[FEATURE-REQUEST]: shield height & fire height

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#62]
### Your idea

- a slider to adjust the fire height
- a slider to adjust the shield height

like this:
![image](https://github.com/NoRiskClient/issues/assets/68741965/98194e8d-279d-40be-ae94-f762d7a346b6)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@Kolpixx gibt es nicht sowas wie "low utils"?

**Comment by Kolpixx** [comment]
Ja es gibt etliche mods wo man das einstellen kann. Dachte aber das wäre evt. passend bei den pack tweaks modul im nrc.
