### ISSUE TITLE
[Bug]: Amour Trims werden nicht angezeigt

### ISSUE THREAD

**Issue by Scablyy** [NoRiskClient/issues#620]
### How to reproduce ?

Amour trims werden nicht angezeigt wenn man in Freelock, F5 oder in den Modulen ist

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

2.0.19 i guess ( neueste halt )

**Comment by MeisterAH** [comment]
ist bekannt

**Comment by MeisterAH** [comment]
https://github.com/NoRiskClient/issues/issues/363
