### ISSUE TITLE
[Bug]: McReal 0min Late

### ISSUE THREAD

**Issue by Technicfan** [NoRiskClient/issues#622]
### How to reproduce ?

Send your McReal less than one minute late and get `0min Late` as status.

![grafik](https://github.com/user-attachments/assets/d89940ac-9aca-4b68-ac20-f6bb6aa21a37)

Maybe add a condition that displays the time in seconds if it is smaller than `60s`.

### Where is this happening?

Client, Backend

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Danke fürs reporten!

**Comment by copyandexecute** [comment]
![grafik](https://github.com/user-attachments/assets/96a3b664-0876-4afb-b359-ad713784dea8)

**Comment by Technicfan** [comment]
?

**Comment by copyandexecute** [comment]
bug habe ich heute auf norisk-dev gefixed
