### ISSUE TITLE
[Bug]: Dynamic launcher invites 

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#624]
### How to reproduce ?

@TimLohrer 

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.16

**Comment by copyandexecute** [comment]
@TimLohrer kannst closen oder?

**Comment by Flytzer** [comment]
@copyandexecute Ich close ^^
