### ISSUE TITLE
[Bug]: File Dialog für Custom Java Path öffnet sich nicht

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#625]
### How to reproduce ?

Der File Dialog, um ein custom java path auszuwählen kann sich nicht öffnen.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.16

### Relevant log output

```shell
[29-11-2024 23:20:22] | ERROR | Failed to select file using dialog: TypeError: Cannot read properties of undefined (reading 'replace')
```

**Comment by BigBrainRobin29** [comment]
Hoffentlich fixed mit https://github.com/NoRiskClient/noriskclient-launcher/pull/83
