### ISSUE TITLE
[FEATURE-REQUEST]: Cape Preview

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#626]
### Your idea

Im Capes Tab einen Button mit dem man ein Cape anschauen kann, bevor man es zur Überprüfung einsendet.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by BigBrainRobin29** [comment]
Als Alternative kann man auch https://skinview3d-demo.vercel.app/ verwenden.

**Comment by copyandexecute** [comment]
Coole Idee

**Comment by copyandexecute** [comment]
@TimLohrer ich weiß du bist busy, das ist ein freundlicher du hast es mal gelesen ping

**Comment by TimLohrer** [comment]
![Image](https://github.com/user-attachments/assets/41e32675-abdd-4a45-9663-105738098b67)

**Comment by TimLohrer** [comment]
![Image](https://github.com/user-attachments/assets/ab926b70-86a7-47d9-af15-1e3cdab8d92b)

**Comment by TimLohrer** [comment]
Man kann jz auch jeden cape in trending anklicken und previewen
