### ISSUE TITLE
[Bug]: Spactate Game stackbar

### ISSUE THREAD

**Issue by HeroOfDungeon** [NoRiskClient/issues#629]
### How to reproduce ?

Schnell mehrmals auf den "Specate Game"-Button drücken
![Screenshot](https://github.com/user-attachments/assets/f821e811-a111-4ebc-bf50-3a84b68bdf77)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Flytzer** [comment]
Get nicht also denke mal invalid

**Comment by BigBrainRobin29** [comment]
Kann wahrscheinlich nur passieren, wenn es stark laggt, oder so. Wir konnten es nicht reproduzieren.

**Comment by Flytzer** [comment]
geredet wie eine möwe

**Comment by HeroOfDungeon** [comment]
> Kann wahrscheinlich nur passieren, wenn es stark laggt, oder so. Wir konnten es nicht reproduzieren.

Habe es bei ~60 FPS mit Autoklicker erreicht

**Comment by BigBrainRobin29** [comment]
> > Kann wahrscheinlich nur passieren, wenn es stark laggt, oder so. Wir konnten es nicht reproduzieren.
> 
> Habe es bei ~60 FPS mit Autoklicker erreicht

Ja gut, mit Autoclicker kann das natürlich sein, ich teste es maybe später nochmal. Aber wenn man es nicht versucht, kann das eigentlich nicht passieren.

**Comment by copyandexecute** [comment]
Habe einen 1 sekunden cooldown eingebaut
Aber ja man kann wenn man spectatet trotzdem noch spectaten, aber das bleibt erstmal so
