### ISSUE TITLE
[Bug]: Can't disable background blur

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#63]
### What happened?

The background blur still shows after disabling the **blur background option** in the **pack tweaks** and enabling the **clear background module**.

https://github.com/NoRiskClient/issues/assets/68741965/d687e36f-1768-454c-8570-f1135a811de0

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
@PSJahn ich gebe dir das mal, sollte eig. ez sein oder?

**Comment by PSJahn** [comment]
> @PSJahn ich gebe dir das mal, sollte eig. ez sein oder?

Eh joa gute frage warum es diese options überhaupt gibt, das einzigste was nämlich den Blur beeinflusst ist das Blur module selbst

**Comment by PSJahn** [comment]
> @PSJahn ich gebe dir das mal, sollte eig. ez sein oder?

Also TLDR; Ist bereits fixed in der development version also einfach aufs nächste update warten
