### ISSUE TITLE
[Bug]: Load More springt nicht an Seitenanfang

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#639]
### How to reproduce ?

War fixed aber ist bei filtern immer noch da. 
Kurze Erklärung: Filter auf Optimization beispielsweise stellen und bis zum Ende scrollen. Dann auf Load More. Man muss nun manuell hochscrollen zum Anfang der Seite

Launcher -> Addons -> Installed -> oben rechts die Filter -> Filter auswählen (z.B. Optimization) -> runterscrollen bis Load More -> auf Load More klicken

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by Flytzer** [comment]
aber das ist doch kein Bug load more soll doch mehr mods loaden oder verstehe ich was falsch ?

**Comment by BigBrainRobin29** [comment]
War grad verwirrt, das ist doch ein Launcher Bug. Warum dann "Where is this happening? Client"?
Und ig das Problem ist, dass man am Ende der Liste ist, obwohl man am Anfang der neu geladenen Mods sein sollte. Aber das ist nicht nur beim Filtern oder?

**Comment by MeisterAH** [comment]
ist doch er hier https://github.com/NoRiskClient/issues/issues/489 oder?
