### ISSUE TITLE
[Bug]: Enum lists in ui modules don't work

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#64]
### What happened?

The dot doesn't show when activated
The crosshair types (cross, circle, arrow) don't work

https://github.com/NoRiskClient/issues/assets/68741965/caad8d05-08da-4b70-9806-eeff842aa620

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
@Kolpixx das ist bekannt und auch bei allen anderen modules die so eine liste verwenden ein problem 👍
