### ISSUE TITLE
[Bug]: NoFog Probleme

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#641]
### How to reproduce ?

NoFog scheint wohl wieder Probleme zu machen
https://discord.com/channels/774271756549619722/1309090373003382794

#412 Referenz zum vorherigen Issue mit NoFog (Zusammenhang?)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
Hi kannst du die bilder, sachen von discord hier reinposten?

**Comment by copyandexecute** [comment]
@SirKnubble hau raus

**Comment by SirKnubble** [comment]
> @SirKnubble hau raus

Das ist schnell erklärt: NoFog ändert bei mir nichts. Lava-, Wasser-, und Terrain-Fog bleiben gleich.

**Comment by copyandexecute** [comment]
brauche bilder, mehr infos zum reproduzieren pls

**Comment by copyandexecute** [comment]
nvm bin dran

**Comment by copyandexecute** [comment]
fixed auf norisk-dev testen

**Comment by TimLohrer** [comment]
klappt!
