### ISSUE TITLE
[Bug]: Game laggt nach 30 Minuten

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#644]
### How to reproduce ?

```Nach 30 min spielen (singelplayer ohne zusätzliche mods) droppt das game von 500-600 FPS auf 5-10 FPS. Um es zu beheben muss [man] das Game neustarten``` 
https://discord.com/channels/774271756549619722/1313198806782967808

Memory Usage ist normal und es tritt wohl auch nach restart immer auf.

![Screenshot_2024-12-03_163230](https://github.com/user-attachments/assets/5f1b2be2-347c-45c8-a6be-d692d93cc7f9)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by SirKnubble** [comment]
Zu wenig Infos.
@TQSHY machst du das?
