### ISSUE TITLE
Armor Rendering - Suits/cosmetics allgemein 

### ISSUE THREAD

**Issue by HitzlikeaBanana** [NoRiskClient/issues#645]
### Your idea

Suits

Standart: Wenn man ein Suit an hat, dann Rüstung anlegt, wird der jeweilige Tell des suits disabled. (bsp: ich ziehe eine Diamant Hose an = cubes im bipedright- leftleg werden versteckt. Und das bei jedem Client User, nicht nur für dich selbst) 

Neuer Knopf im gleichen Panel wo man die Position/Farbe ändern kann (allgemein für alle cosmetics die am Kopf, Brust, Bein oder Fuß cube sind [Suits/Hats/etc. Aber keine Pets oder Back cosmetics]

- „Replace for Armor“ Oder so ähnlich 
Wenn aktiv = lässt die jeweilige Rüstung im f5 *nur für sich selbst* verschwinden, und zeigt stattdessen das ausgewählte Cosmetic an. Egal ob man dann tatsächlich einen z.b Helm auf hat oder nicht, man sieht durchgehend nur das Hat cosmetic. FÜR SICH SELBST ONLY 

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
added auf norisk-dev

**Comment by copyandexecute** [comment]
@HitzlikeaBanana hat confirmed, bald kommt noch head

**Comment by HitzlikeaBanana** [comment]
Mehrheitlicher Wunsch:
Einstellung für Hat-Cosmetics: "Replace for Armor" 

Es gibt eine Einstellung, die global für alle Hat-Cosmetics gilt. Diese legt fest, ob bei jedem Spieler – auch bei dir selbst – statt eines normalen Helms (z. B. Diamanthelm) immer das Hat-Cosmetic angezeigt wird, wenn der Spieler eines besitzt.

- **Einstellung AN:** Das Hat-Cosmetic wird unabhängig davon ob du einen Helm trägst angezeigt. _Falls du einen Helm trägst_, wird dieser **nicht** für dich im f5 und auch nicht für andere angezeigt. Stattdessen wird für jeden (sofern er "change for armor" auch an hat) dein cosmetic als Helm angezeigt. _Hast du keinen Helm auf_, zeigt sich das cosmetic regulär für alle.

 (Beachte: Dadurch siehst du nicht, welchen Helm jemand tatsächlich trägt, z. B. in Skywars)

- **Einstellung AUS:** Die Anzeige des Hat-Cosmetics ist von davon abhängig ob du oder andere einen Helm tragen. _Ist dies der Fall_, dann wird dein cosmetic für alle versteckt. _Trägst du oder jemand anderes keinen Helm_, wird dein/sein cosmetic für alle gezeigt. 

Dies sorgt für Fairness im PvP, da man den Helm sehen kann.
Es verhindert außerdem, dass sich das Cosmetic und der Helm visuell überlappen und „verbuggen“.

Jeder kann dann entscheiden, ob man lieber drip hat oder sehen will, welchen Helm ein Gegner beim pvpn hat.

**Comment by copyandexecute** [comment]
1. test auf norisk-dev verfügbar

**Comment by SirKnubble** [comment]
Geht auf Prod

**Comment by technicfan** [comment]
Das Feature funktioniert nicht richtig bei anderen Spieler, die auch auf dem Server sind (ich hab das bis jetzt nur auf 1.21.8 dev getestet).
Da wird dann nämlich das Cosmetic (hier der Fedora) angezeigt, der Helm aber nicht versteckt:
| So sieht man sich selbst | So sehen andere einen |
|:-:|:-:|
|<img width="330" height="405" alt="Image" src="https://github.com/user-attachments/assets/81002825-f633-4ed2-812a-8b74b3a017b8" />|<img width="320" height="348" alt="Image" src="https://github.com/user-attachments/assets/03fc8df7-bd8a-454e-b81e-a7b6376d3bb4" />|

Beide Spieler haben die "Rüstung durch Cosmetics ersetzen" Option aktiviert.

Hab das jetzt hier rein geschrieben, kann aber auch ein neues Issue erstellen.
