### ISSUE TITLE
[Bug]: Blank screen in launcher on Zorin OS (Ubuntu)

### ISSUE THREAD

**Issue by RafaeloxMC** [NoRiskClient/issues#646]
### How to reproduce ?

Start the launcher via the installed .deb file or by using `npm run tauri dev` in a dev environment, screen will go blank in launcher as well as login window.
![image](https://github.com/user-attachments/assets/e608792e-6c6d-4c69-9ccc-0e01d7176e16)

### Fix for this (in dev environment):
Run via `WEBKIT_DISABLE_COMPOSITING_MODE=1 npm run tauri dev`, launcher seems to work fine then.
### in production environment:
Run via `WEBKIT_DISABLE_COMPOSITING_MODE=1 no-risk-client`

### System specs (if needed):
CPU: AMD® Ryzen 7 5700x 8-core processor × 16
GPU: NVIDIA GeForce RTX 4070

nvidia-smi output:
```sh
rafa@zorinos:~/dev/noriskclient-launcher$ nvidia-smi
Wed Dec  4 21:31:09 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.100                Driver Version: 550.100        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070        Off |   00000000:06:00.0  On |                  N/A |
|  0%   49C    P5             22W /  200W |     887MiB /  12282MiB |     35%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

Please integrate a fix for this into production. More information on this [here](https://github.com/tauri-apps/tauri/issues/5143#issuecomment-1311815517)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Linux

### Version (for launcher bugs)

0.5.16 & latest dev build

### Relevant log output

```shell
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  | ###############################
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  |       NEW LAUNCHER LOG
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  | ###############################
[04-12-2024 21:36:31] | INFO  | 
[04-12-2024 21:36:31] | INFO  | Rosetta: false
[04-12-2024 21:36:31] | INFO  | Architecture: x64
[04-12-2024 21:36:31] | INFO  | Creating launcher directories...
[04-12-2024 21:36:31] | INFO  | Finish launcher directories...
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)


** (no-risk-client:834535): WARNING **: 21:36:31.757: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
[04-12-2024 21:36:31] | DEBUG | Found 0 Last Instances
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

21:36:32 [vite-plugin-svelte] /src/components/instances/InstancesHotbar.svelte:28:4 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
21:36:33 [vite-plugin-svelte] /src/components/account/AccountListItem.svelte:8:15 AccountListItem has unused export property 'dialog'. If it is for external reference only, please consider using `export const dialog`
21:36:33 [vite-plugin-svelte] /src/components/account/AccountListLoading.svelte:96:4 Unused CSS selector ".remove-button"
21:36:33 [vite-plugin-svelte] /src/components/account/AccountListLoading.svelte:101:4 Unused CSS selector ".remove-button:hover"
[04-12-2024 21:36:34] | INFO  | Launcher Version: 0.5.16
[04-12-2024 21:36:34] | INFO  | URL: https://api.norisk.gg/api/v1/core/online
[04-12-2024 21:36:34] | DEBUG | starting new connection: https://api.norisk.gg/
[04-12-2024 21:36:34] | INFO  | Language set to en_US.
```

**Comment by RafaeloxMC** [comment]
Haven't tried it yet but I don't think it would work, multiple Tauri apps have this problem, same thing with e.g. the Modrinth app on Linux and the same env variable seems to fix the problem as well.
However, I will still try it and let you know if it works.

**Comment by SirKnubble** [comment]
@RafaeloxMC yo got a update?

**Comment by RafaeloxMC** [comment]
Yeah, removing the config does not seem to solve the issue.

**Comment by SirKnubble** [comment]
> Yeah, removing the config does not seem to solve the issue.

Aight, that´s a common fix. You can find all of them on the [Discord-Server](https://discord.norisk.gg/) in our [Bug-Collection](https://discord.com/channels/774271756549619722/1276193700019437578).

**Comment by RafaeloxMC** [comment]
> > Yeah, removing the config does not seem to solve the issue.
> 
> Aight, that´s a common fix. You can find all of them on the [Discord-Server](https://discord.norisk.gg/) in our [Bug-Collection](https://discord.com/channels/774271756549619722/1276193700019437578).

I dont know if I understand you wrong but I said deleting the config does **NOT** solve the issue

**Comment by BigBrainRobin29** [comment]
Wait, you already fixed it and just want us to implement the fix, right?

**Comment by RafaeloxMC** [comment]
> Wait, you already fixed it and just want us to implement the fix, right?

Yup, I said what fixed it for me and thought there has to be a way to do this in the code without setting an env var every time when launching the NRC launcher

**Comment by SirKnubble** [comment]
> Yup, I said what fixed it for me and thought there has to be a way to do this in the code without setting an env var every time when launching the NRC launcher

Hard to get what you meant when its not feature request but bug report 😁 

Will look into implementing the fix! <3
