### ISSUE TITLE
[Bug]: Missing Tranlation

### ISSUE THREAD

**Issue by Tangmuzhul** [NoRiskClient/issues#650]
### How to reproduce ?

![2024-12-05_14 38 20](https://github.com/user-attachments/assets/729d0291-c93f-4dd6-9661-402b61fdd230)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by BigBrainRobin29** [comment]
https://github.com/NoRiskClient/issues/issues/480#issuecomment-2466694298 Ist bekannt

**Comment by Tangmuzhul** [comment]
ok
