### ISSUE TITLE
[Bug]: Outlayers in hglabor (clientside)

### ISSUE THREAD

**Issue by Kimi4427** [NoRiskClient/issues#653]
### How to reproduce ?

Join HGLABOR.de or MC.norisk.gg
Look at an outlayer of an player, then switch the see Players button to hide and show.
You should not see an outlayer from a player anymore.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

1.21

### Relevant log output

```shell
none
```

before: https://imgur.com/KHh04tE
bug: https://imgur.com/Ld6oXVh
Discord:Kimi4427
MC:KimiKaccess
Github:IDK?

**Comment by Kimi4427** [comment]
wusste nicht das norisk haare hat

**Comment by enricoxD** [comment]
Danke fürs reporten aber das ist kein Problem des Clients. Daher werde ich das erstmal closen 😊

**Comment by Kimi4427** [comment]
achso sry hab falsch angegeben danke!

**Comment by TigerCrafter** [comment]
> Danke fürs reporten aber das ist kein Problem des Clients. Daher werde ich das erstmal closen 😊

Hängt das echt nicht mit dem Client zusammen? Wenn es an HGLabor liegt soll ich dafür ein Issue [hier](https://github.com/HGLabor/issues/issues) öffnen?

**Comment by enricoxD** [comment]
> > Danke fürs reporten aber das ist kein Problem des Clients. Daher werde ich das erstmal closen 😊
> 
> Hängt das echt nicht mit dem Client zusammen? Wenn es an HGLabor liegt soll ich dafür ein Issue [hier](https://github.com/HGLabor/issues/issues) öffnen?

Bitte nicht, Bugs aus der Lobby bitte nur reporten, wenn sie auch in der nrc-lobby (aktuell offline) auftreten.
