### ISSUE TITLE
[FEATURE-REQUEST]: Ladeanimation Component

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#656]
### Your idea

Wenn man z.b. clear data macht oder zu exp switch oder generell es kurz laden muss
@TimLohrer kannst du da bitte was zaubern

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
@copyandexecute sag mal wie das ca aussehen soll.. kann mir da grad nix vorstellen

**Comment by copyandexecute** [comment]
Du bist der Css koch

**Comment by TimLohrer** [comment]
@copyandexecute sag mal bitte genau wo das hin soll, weil sehe nicht so krass den usecase 🤔

**Comment by SirKnubble** [comment]
> @copyandexecute sag mal bitte genau wo das hin soll, weil sehe nicht so krass den usecase 🤔

Enablen von EXP-Mode :^) ([Discord](https://discord.com/channels/774271756549619722/1264524228615602249/1318657493425062069))
