### ISSUE TITLE
[MCReal Bug]: Blur Bar verdeckt Content

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#660]
### How to reproduce ?

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/5ed1e348-34fd-49d4-8ac4-059485d47a9c">
Die Bar verdeckt ein paar pixelreihen des neuesten Posts

### Where is this happening?

—

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
No official tablet / ipad support
