### ISSUE TITLE
[Bug]: Launcher logs wenn minecraft noch offen

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#662]
### How to reproduce ?

![Image](https://github.com/user-attachments/assets/a2e2d914-3d24-43d8-ae08-6f2f0550071d)
Shadow ist noch rot

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.16

### Relevant log output

```shell

```

**Comment by TimLohrer** [comment]
name macht zwar keinen Sinn aber is ok
wird gefixt
