### ISSUE TITLE
[Bug]: Pong funktioniert teilweise nicht

### ISSUE THREAD

**Issue by minecraftfanxy** [NoRiskClient/issues#668]
### How to reproduce ?

![2024-12-08_09 25 10](https://github.com/user-attachments/assets/fa213977-b74f-4dd7-b7cc-190f9ec46b79)

bei jeglichen Shadern verschwindet der Hintergrund des Spiels und öfters lässt sich das Paddle nicht bewegen, was das Spiel unspielbar macht.
![2024-12-08_09 25 21](https://github.com/user-attachments/assets/b242f381-3a2d-4edb-a853-ecf3b8e22b1c)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.16

**Comment by minecraftfanxy** [comment]
*außerdem kann der Ball aus dem Spiel fliegen, heißt er fliegt hinter ein Paddle aber der Punkt wird nicht gezählt und das Spiel geht unendlich ohne Ball weiter (siehe Bild 2)

**Comment by Flytzer** [comment]
> *außerdem kann der Ball aus dem Spiel fliegen, heißt er fliegt hinter ein Paddle aber der Punkt wird nicht gezählt und das Spiel geht unendlich ohne Ball weiter (siehe Bild 2)

known

**Comment by TimLohrer** [comment]
Ja Jungs das ist nicht shader kompatibel, wird es aber glaube ich auch nicht werden...

**Comment by TigerCrafter** [comment]
Duplicate of #347
