### ISSUE TITLE
[FEATURE-REQUEST]: NoRiskClient UI Übersicht aller Mods

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#67]
### Your idea

Mit RShift sollte anstatt die Suchleiste eine Liste aller Mods kommen

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@copyandexecute Das muss so langsam echt her, das ist ein Muss...
