### ISSUE TITLE
[Bug]: Client Messages not showing

### ISSUE THREAD

**Issue by SecretBot155** [NoRiskClient/issues#670]
### How to reproduce ?

Keine PopUp Message rechts oben (Freundschaftsanfragen, Minigameanfragen, usw...) werden angezeigt, es kommt der ton aber nicht die grafik, jedes mal auch wenn ich neustarte, muss nichts besonderes dafür machen ...

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by MeisterAH** [comment]
hast du irgendwelche externen Mods drin?

**Comment by SecretBot155** [comment]
> hast du irgendwelche externen Mods drin?

hab grad den übeltäter gefunden: advancement plagues
danke für den hinweis
