### ISSUE TITLE
[Bug]: options button visible without use

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#671]
### How to reproduce ?

![Image](https://github.com/user-attachments/assets/30e33cb9-34f2-4f57-b2c4-aeba31ef7be4)
Hier gibts keine menüpunkte aber der button ist trotzdem da

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell

```

**Comment by copyandexecute** [comment]
angepasst auf norisk-dev bitte testen

**Comment by TimLohrer** [comment]
klappt!
