### ISSUE TITLE
[Bug]: Capes

### ISSUE THREAD

**Issue by Kimi4427** [NoRiskClient/issues#672]
### How to reproduce ?

![grafik](https://github.com/user-attachments/assets/1af01f96-3ceb-42c5-bb96-bad40e18a27d)
Wenn du diese einstellung auf false hast bist du oft der standart skin

**Video (wenn es funktioniert):**
[![Watch the video](https://github.com/user-attachments/assets/e5701452-f76d-436b-8958-1ce680d69b43)](https://firebasestorage.googleapis.com/v0/b/homepage-80149.appspot.com/o/Aufzeichnung%202024-12-10%20174625.mp4?alt=media&token=c7fc6cf7-aa22-4e68-9693-f9a86a5d8ec8)
 Logs: [![logs](https://github.com/user-attachments/assets/a3b7f8a4-3b9f-41de-ba84-fece8ab0b78a)](https://firebasestorage.googleapis.com/v0/b/homepage-80149.appspot.com/o/latest.log?alt=media&token=3e3700f8-1d53-4471-ac84-4062412cb78c)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows, Linux

### Version (for launcher bugs)

1.21

### Relevant log output

```shell
none
```

**Comment by BigBrainRobin29** [comment]
Ich bezweifle eigentlich, dass das damit zusammen hängt. Wie kommst du zu diesem Schluss? Und meinst du mit false, dass die Einstellung aus ist, oder dass Capes aus sind?

**Comment by BigBrainRobin29** [comment]
> @BigBrainRobin29 denke es ist der allgemeine Bug mit den Skins

@TQSHY Ja, schon, aber er meinte ja, dass das was mit Capes zu tun hätte.

**Comment by Flytzer** [comment]
Jungs einfach testen und schaun obs valid oder invalid is

**Comment by Kimi4427** [comment]
ich hab keine ahnung davon aber (fast) immer wenn ich diese Funktion aus habe bin ich der standart skin (noriskk)
btw. früher stand da was anderes irgendwie wie nrc.hide.capes oder so

**Comment by Flytzer** [comment]
Tot dann @copyandexecute weißt du da was?

**Comment by Kimi4427** [comment]
ich hab linux und windows

**Comment by SirKnubble** [comment]
Cool aber auch getestet?
Maybe schlechtes Internet, Antivirus, Firewall, weil ich hab gestern alles vom Update getestet und das ging bei mir.

**Comment by Kimi4427** [comment]
könnte sein das es schon gefixt ist, weil ja letzens update kam

**Comment by Kimi4427** [comment]
Video Windows: https://firebasestorage.googleapis.com/v0/b/homepage-80149.appspot.com/o/Aufzeichnung%202024-12-10%20174625.mp4?alt=media&token=c7fc6cf7-aa22-4e68-9693-f9a86a5d8ec8

**Comment by BigBrainRobin29** [comment]
Weird, kann ich auch nicht reproducen, aber da muss NoRisk reinschauen.

**Comment by SirKnubble** [comment]
@Kimi4427 bitte deine Logs hier rein senden um zu verifizieren, dass das am Client liegt und nicht an dir.

**Comment by Kimi4427** [comment]
Logs: [![logs](https://github.com/user-attachments/assets/a3b7f8a4-3b9f-41de-ba84-fece8ab0b78a)](https://firebasestorage.googleapis.com/v0/b/homepage-80149.appspot.com/o/latest.log?alt=media&token=3e3700f8-1d53-4471-ac84-4062412cb78c)` (bitte benutzt es nur zum verifizieren, wenn ihr verifiziert habt lösche ich die datei)`

**Comment by Kimi4427** [comment]
**da ich im channellog gesehen habe das der bug gelößt wurde**
 (https://ptb.discord.com/channels/774271756549619722/1253287826498519060/1321930698206085191)
 zitiere: _Es wurde der NoRisk Skin fälschlicherweise angezeigt https://github.com/NoRiskClient/issues/issues/701 (kann noch immer auftreten wenn mc server down sind btw)_
und in https://github.com/NoRiskClient/issues/issues/701 #701 
![grafik](https://github.com/user-attachments/assets/020afa77-a892-4bf3-895d-c6c57900f3b0)
das steht denke ich mal das ich mein bugreport jetzt schließen kann.
