### ISSUE TITLE
[Bug]: ToggleSprint verliert enabled-state

### ISSUE THREAD

**Issue by SirKnubble** [NoRiskClient/issues#674]
### How to reproduce ?

ToggleSprint vergisst nach jedem Restart ob er enabled war und disabled sich wieder.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
fixed auf norisk-dev bitte testen

**Comment by SirKnubble** [comment]
@copyandexecute so halb.

Wenn man das Modul disabled bleibt ToggleSprint noch an bis man das
1. entweder disabled durch einmaliges drücken der Sprint-Taste
2. oder durch ESC-Menü öffnen und wieder schließen
toggled.

Kleinigkeit. Kannst sonst auch closen, weil so dramatisch ist das nicht.

**Comment by copyandexecute** [comment]
konnte das gerade nicht reproduzieren,
bzw kannst du unterschieden zwischen ToggleSprint MC und ToggleSprint NRC?

werde es noch fixen, aber ballere den hotfix mal auf prod

**Comment by SirKnubble** [comment]
> kannst du unterschieden zwischen ToggleSprint MC und ToggleSprint NRC?

Ja, kann ich? xD Ich rede hier ausschließlich vom NRC ToggleSprint.
Also, wenn ich das im R-Shift Menü disable und vorher Sprint toggled war (also ich sprinte direkt), dann bleibt der Effekt vom ToggleSprint Modul immernoch (also er sprintet immernoch direkt), bis man im Pause-Menü ist, nochmal sprintet, etc.
