### ISSUE TITLE
[Bug]: Nametags Enabled/Disabled gamble

### ISSUE THREAD

**Issue by SirKnubble** [NoRiskClient/issues#678]
### How to reproduce ?

Ob NRC+ Nametag im Chat rendered wird ist gamble.

![image](https://github.com/user-attachments/assets/95484384-a364-4649-ad3b-345555e99da3)
![image](https://github.com/user-attachments/assets/06b6734f-b80a-450e-92d0-505b41bffaf6)
![image](https://github.com/user-attachments/assets/8514fcdb-2f24-4856-a054-3a09b6c30632)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by 0x3C50** [comment]
Kann ich aufs erste nicht nachvollziehen. Ich schreib ein kleinen command der die letzten paar zeilen aus dem chat dumpt. Wenn das wieder vorkommt, dem command ausführen und den output in der log datei in das issue senden.

**Comment by copyandexecute** [comment]
bin drani

**Comment by copyandexecute** [comment]
test auf norisk-dev pls

**Comment by copyandexecute** [comment]
@SirKnubble ich schließe ja?
