### ISSUE TITLE
[Bug]: Subway Surfer sneak button is not recognized

### ISSUE THREAD

**Issue by leeonwde** [NoRiskClient/issues#679]
### How to reproduce ?

I wanted to play Subway Surfer yesterday, but then I realized that I have my sneak button on an extra mouse button and so I can't “scroll” because Subway Surfer doesn't recognize it

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by BigBrainRobin29** [comment]
@RadFlunder https://github.com/HGLabor/issues/issues/98 war das nicht das?

**Comment by Flytzer** [comment]
@leeonwde HGLabor/Subwaysurfers issues bitte in den hglabor github

**Comment by hennycraft52** [comment]
> @RadFlunder https://github.com/HGLabor/issues/issues/98 war das nicht das? 

Bin zwar nd Rad, aber ja das ist dass. Wir sind grade dabei Einstellungen hinzuzufügen mit denen das dann, glaube ich, auch möglich sein sollte.
@BigBrainRobin29

**Comment by RadFlunder** [comment]
> > @RadFlunder https://github.com/HGLabor/issues/issues/98 war das nicht das? 
> 
> Bin zwar nd Rad, aber ja das ist dass. Wir sind grade dabei Einstellungen hinzuzufügen mit denen das dann, glaube ich, auch möglich sein sollte.
> @BigBrainRobin29 

Genau haha. Aber mach mal die ui bitte <3

**Comment by hennycraft52** [comment]
> > > @RadFlunder https://github.com/HGLabor/issues/issues/98 war das nicht das? 
> > 
> > Bin zwar nd Rad, aber ja das ist dass. Wir sind grade dabei Einstellungen hinzuzufügen mit denen das dann, glaube ich, auch möglich sein sollte.
> > @BigBrainRobin29 
> 
> Genau haha. Aber mach mal die ui bitte <3
> 
> 

Bin dabei...

**Comment by SirKnubble** [comment]
@Flytzer sowas dann bitte auch closen wenn du es zu "Wont Fix" movest. 😉
