### ISSUE TITLE
[Bug]: Cosmetic Preview broken (nur capes & emotes funktionieren)

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#682]
### How to reproduce ?

![grafik](https://github.com/user-attachments/assets/20fcbdb4-9136-4217-be89-b948d400782e)
Die Cosmetics werden in der Preview nicht angezeigt. Also halt nur Capes und Emotes.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by BigBrainRobin29** [comment]
@Kolpixx Bei mir gehts jetzt wieder

**Comment by Kolpixx** [comment]
> @Kolpixx Bei mir gehts jetzt wieder

Komisch. Bei mir ist es immernoch broken

**Comment by BigBrainRobin29** [comment]
Ah, kanns jetzt reproduzieren. Wenn ich die Distance hochstell gehts und bei 128 nicht.

**Comment by BigBrainRobin29** [comment]
Ne jetzt gehts auch mit höchster Distance nicht mehr

**Comment by copyandexecute** [comment]
bitte auf norisk-dev testen + gucken ob das bei mcreal profilen auch der fall ist

**Comment by SirKnubble** [comment]
> bitte auf norisk-dev testen + gucken ob das bei mcreal profilen auch der fall ist

Nicht fixed für den McReal. Profile 3d-Char.

**Comment by copyandexecute** [comment]
angepasst für mcreal bitte testen

**Comment by SirKnubble** [comment]
> angepasst für mcreal bitte testen

Jooar. Also geht... nur sind die irgendwie durchsichtig von der Seite von der man den Skin anschaut (dreh den einfach mal bisschen dann checkst du).
Gilt für Bandana, Vision Pro, Hats, ...

**Comment by SirKnubble** [comment]
![image](https://github.com/user-attachments/assets/7deb629c-a6e0-4422-b672-6f62b40d3e03)
![image](https://github.com/user-attachments/assets/604c85bb-acf6-4418-a707-1bcfdfba2ad3)

**Comment by copyandexecute** [comment]
bin dran

**Comment by copyandexecute** [comment]
bekomms gerade irgendwie nicht fixed... gucke morgen nochmal rein

**Comment by copyandexecute** [comment]
für mcreal pls neues ticket machen, cosmetcis sind fixed
