### ISSUE TITLE
[FEATURE-REQUEST]: Capes > In Review

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#684]
### Your idea

In Capes einen Tab in dem man sehen kann, welche Capes noch nicht überprüft wurden.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Check, aber kp wie ich das vom ui her machen soll + low prio also erstmal auf die Bank damit, sorry!
