### ISSUE TITLE
[Bug]: Refresh Capes After Delete (Launcher)

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#686]
### How to reproduce ?

cape löschen

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
👍🤝

**Comment by TimLohrer** [comment]
@copyandexecute habe das codet aber die sind halt wie schonmal gesagt noch cached.. ich mache jz einfach ne client side delete list, die sich nach 5min selber cleared, dann siehts so aus als wäre es deleted, bei anderen is es natürlich trotzdem noch da in den 3min bis es weg ist.
