### ISSUE TITLE
[FEATURE-REQUEST]: Allow to select items with mouse to run wheel commands

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#689]
### Your idea

Title, um z.B. Items in der Nähe zu sich zu teleportieren, zu entfernen, etc. Könnte man auch als Einstellung machen, sehe aber keinen Grund warum man das nicht wollen sollte.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
passt!
