### ISSUE TITLE
[FEATURE-REQUEST]: Partikel für Emotes Supporten

### ISSUE THREAD

**Issue by HitzlikeaBanana** [NoRiskClient/issues#690]
### Your idea

^titel, issue auf Anfrage von Norisk erstellt 

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
Ready To Test Auf NoRisk-Dev https://github.com/NoRiskClient/noriskclient-client-modules/commit/15303aad0c2fa71b79a8e5033c4c971a2d3bad04
