### ISSUE TITLE
[Bug]: Addon filters not working

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#695]
### How to reproduce ?

Die filter werden nicht mehr angezeigt
![image](https://github.com/user-attachments/assets/481ee119-9d3b-4101-aabd-cf84877af32a)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.5.19

**Comment by TimLohrer** [comment]
Ja man alles blöd... ich schaue morgen dannach

**Comment by BigBrainRobin29** [comment]
https://github.com/TimLohrer/noriskclient-launcher/pull/26
