### ISSUE TITLE
[FEATURE-REQUEST]: Emote mit sounds

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#699]
### Your idea

easy setup for emotes with sounds

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by copyandexecute** [comment]
ready to test auf norisk-dev

**Comment by copyandexecute** [comment]
ist done... muss aber noch so coden dass es aufhört wenn der emote nicht mehr played
weißte was ich machs jetzt

**Comment by Flytzer** [comment]
Bei winner wird sound garnich abgebrochen bei present schon @copyandexecute
