### ISSUE TITLE
[Bug]: NoRisk Default Skin (Mojang Ratelimit?)

### ISSUE THREAD

**Issue by copyandexecute** [NoRiskClient/issues#701]
### How to reproduce ?

How to reproduce

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
@NoRiskClient/bughunter help needed, aber denke es liegt an ratelimit?

**Comment by SirKnubble** [comment]
> @NoRiskClient/bughunter help needed, aber denke es liegt an ratelimit?

Idk, laut Logs requested der beim Joinen nicht immer Player Progress für alle Personen.
Nur die mit Request laden auch Skins. Leute die neu joinen requesten auch.

Aber die leere Zeile `[DefaultDispatcher-worker-4/WARN]:` die nach den ersten Paar Requests kommt verwirrt mich noch

**Comment by SirKnubble** [comment]
Wollte grad testen obs an Simple Voice Chat liegt, #705

**Comment by BigBrainRobin29** [comment]
Ich glaub nicht, dass das am Ratelimit liegt, bei mir ist auch oft so, dass wenn ich capes disable, dass dann die skins da sind.

**Comment by BigBrainRobin29** [comment]
Das wurde ja schon in #672 erwähnt.

**Comment by copyandexecute** [comment]
OHHH
wenn du die capes disablest? wie interessant danke

**Comment by copyandexecute** [comment]
1. fix ist auf nrc-dev bitte testen
