### ISSUE TITLE
[Bug]: Mob Spectator Mode Coordinate Module

### ISSUE THREAD

**Issue by TQSHY** [NoRiskClient/issues#709]
### How to reproduce ?

1. In den Spectator Mode gehen
2. sich in ein Mob hineinversetzen
3. die Maus bewegen
--> trotzdessen, dass man sich innerhalb eines Mob nicht drehen kann, ändert sich die Himmelsrichtung

![image](https://github.com/user-attachments/assets/2d85995e-c404-4a0f-85e7-88f8ba7acfe0)

![image2](https://github.com/user-attachments/assets/5d37c906-7a86-41c5-b798-cbe3e841c748)

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by copyandexecute** [comment]
lol gucke rein

**Comment by copyandexecute** [comment]
fixed auf norisk dev bitte gucken ob ich die himmelsrichtungen des normalen spielers nicht verkackt habe
