### ISSUE TITLE
[FEATURE-REQUEST]: Instances

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#71]
### Your idea

Ich fände es nützlich, wenn man Instanzen im Launcher erstellen könnte.

Warum? 
Damit man z.B. für seine Survival Welt andere Mods benutzen kann als auf Servern ohne immer mods zu disablen/enablen.

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
![Image](https://github.com/NoRiskClient/issues/assets/55639047/a924eb64-8c43-4a7f-97d0-03e6d690d5e0)
