### ISSUE TITLE
[Bug]: Wrong default filepath for cloning mc instance

### ISSUE THREAD

**Issue by sailex428** [NoRiskClient/issues#710]
### How to reproduce ?

I logged into the launcher for the first time and then clicked on the head skin to start the client. Then I was asked if I wanted to clone the data of my normal mc instance. This didnt work because the path was set incorrectly. Then I simply changed the path (via the folder button) and it worked. 

On macos the default path to the minecraft data is: /Users/sailex/Library/Application Support/minecraft 
and not /Users/sailex/Library/Application Support/.minecraft, as specified in the launcher. (i think on Windows the directory is called .minecraft)

This is not really a bug, but simply a small improvement so that macos users don't have to search for their minecraft directory.

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

v0.5.19

**Comment by copyandexecute** [comment]
@TimLohrer dass muss ich dann mergen oder?

**Comment by copyandexecute** [comment]
@sailex428 danke fürs reporten

**Comment by sailex428** [comment]
Kein Problem!

**Comment by BigBrainRobin29** [comment]
https://github.com/TimLohrer/noriskclient-launcher/pull/26

**Comment by copyandexecute** [comment]
Können wir closen?

**Comment by BigBrainRobin29** [comment]
Ja
