### ISSUE TITLE
[Bug]: jegliche hut cosmetics werden nach game restartet resettet

### ISSUE THREAD

**Issue by Flytzer** [NoRiskClient/issues#714]
### How to reproduce ?

@copyandexecute 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

### Relevant log output

```shell

```

**Comment by copyandexecute** [comment]
das ist ein developer / admin only problem (so halb)

**Comment by copyandexecute** [comment]
rdy to test (aber nur für mich)

**Comment by copyandexecute** [comment]
fixed mit nächsten restart
