### ISSUE TITLE
[FEATURE-REQUEST]: Wither Armor Chroma effect

### ISSUE THREAD

**Issue by TimLohrer** [NoRiskClient/issues#73]
### Your idea

Jap, das ist die Idee, was meint ihr?

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@PSJahn meinste das kriegst du hin? 👀

**Comment by PSJahn** [comment]
> @PSJahn meinste das kriegst du hin? 👀

![image](https://github.com/NoRiskClient/issues/assets/66626848/c1398a79-8449-4615-849e-7bb6e0fa38d5)

**Comment by copyandexecute** [comment]
Aber ist noch nicht live...
