### ISSUE TITLE
[Bug]: Fullbright 

### ISSUE THREAD

**Issue by DoctorDepp** [NoRiskClient/issues#75]
### What happened?

Wenn man den Client restartet und Fullbright an war ist es zwar noch an, jedoch funktioniert es nicht.

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by Greeenman999** [comment]
Ich kann es nicht reproduzieren. Hast du das Problem immer noch?

**Comment by DoctorDepp** [comment]
ja hab ich, ich kann dir auf dc auch einen aufnahme schicken wenn du willst, dm einfach

**Comment by TimLohrer** [comment]
> ja hab ich, ich kann dir auf dc auch einen aufnahme schicken wenn du willst, dm einfach

Kannst auch hier hochkaden.. dann ist alles an einem ort und wir sehen's alle

**Comment by DoctorDepp** [comment]
https://www.youtube.com/watch?v=KveQ78VVOew 
link zum video, kanns nicht als mp4 hier hochladen weil das file zu groß ist

**Comment by Greeenman999** [comment]
Ist das nur auf Hypixel so oder ist das Problem auch im Singleplayer?

**Comment by DoctorDepp** [comment]
überall, auf gomme, auf dem testserver und im singleplayer

**Comment by Greeenman999** [comment]
Kannst du mal beide Logs hier hochladen? Also vor dem restart und nach dem restart?

**Comment by Greeenman999** [comment]
Wenn du Fullbright enabled hast und dann stoppst, kannst du mir die Options.txt schicken?
 Wichtig nicht aus .minecraft sondern aus NoRiskClient

**Comment by DoctorDepp** [comment]
wo genau ist die?

**Comment by Greeenman999** [comment]
@TimLohrer Kannst du mal grad den Windows Pfad raussuchen?

**Comment by TimLohrer** [comment]
C:\Users\{WINDOWS_USER}\AppData\Roaming\norisk\NoRiskClient\data\gameDir\{branch}\options.txt

**Comment by DoctorDepp** [comment]
[options.txt](https://github.com/NoRiskClient/issues/files/14065764/options.txt)

**Comment by Greeenman999** [comment]
Hm sehr komisch. Kannst du mal `gamma:1.0` in die Datei schrieben?

**Comment by DoctorDepp** [comment]
kann sein dass ich das falsche geschickt hab. es gibt 3 branches, development, norisk-dev und production, allerdings hat nur development gamme drinstehen

**Comment by DoctorDepp** [comment]
hab ich, aber es ist immernoch das gleiche

**Comment by Greeenman999** [comment]
hmm das ist alles seehr komisch. Was hast du für mods installiert?

**Comment by DoctorDepp** [comment]
no_fog und noxesium, sollte aber an beiden nicht liegen, da das problem schon davor da war

**Comment by DoctorDepp** [comment]
es kann sein dass ich irgendwas verkake die ganze zeit und falsche sachen schick oder so, aber ich wüsste nicht was

**Comment by Greeenman999** [comment]
Hm ich melde mich demächst nochmal. Danke für deine Hilfe
