### ISSUE TITLE
[Bug]: Fenster Bug

### ISSUE THREAD

**Issue by MrMendel** [NoRiskClient/issues#77]
### What happened?

Wenn man das Minecraft Fenster im Fenstermodus auf nen Zweiten Bildschirm zieht während man im Cosmetic-Fenster ist kommt man in ein verzogenes Fenster
![Bild_2024-01-04_234612990](https://github.com/NoRiskClient/issues/assets/155688870/76cd978f-4892-47ee-aef7-036ffa74dc94)
 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

1.0.5

**Comment by TimLohrer** [comment]
Das ist aktuell noch abhängig von deiner gui scale

**Comment by TimLohrer** [comment]
Hängt an gui scale, ist kein bug, wird nt gefixt sry
