### ISSUE TITLE
[Bug]: Es ist möglich das settings menu zu öffnen und zwischen dem light und dark theme zu wechseln während man im login screen ist

### ISSUE THREAD

**Issue by Asimoaiii** [NoRiskClient/issues#79]
### What happened?

Wie im Titel gesagt, ist wahrscheinlich ein ez fix, aber ich glaube das wäre gut weil man dadurch viele Bugs verhindern könnte die in zukunft auftauchen könnten
![Screenshot 2024-01-05 at 12 43 31](https://github.com/NoRiskClient/issues/assets/64749998/c745aeee-c73f-428e-bd8b-6f4986625ed4)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

v0.3.5

**Comment by TimLohrer** [comment]
nur auf mac, is mir zu blöd... sry
