### ISSUE TITLE
[Bug]: Es ist nicht möglich den login screen zu schließen

### ISSUE THREAD

**Issue by Asimoaiii** [NoRiskClient/issues#80]
### What happened?

https://github.com/NoRiskClient/issues/assets/64749998/387fe482-4b62-4048-b883-923d480bbe9c

Das genze scheint nur ein MacOS bug zu sein. Ich habe schon probiert überall herumzuclicken und andere Fenster zu öffnen. bringt alles nix

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

MacOS

### Version (for launcher bugs)

v0.3.5

**Comment by TimLohrer** [comment]
Ok, auf meiner macos version geht das nicht mal... das is jz blöd :D

**Comment by SleepyPxnda** [comment]
Fixed
