### ISSUE TITLE
[Bug]: Schwarze Ränder bei Checking for Updates

### ISSUE THREAD

**Issue by Tiutus** [NoRiskClient/issues#81]
### What happened?

![Bild_2024-01-05_181148289](https://github.com/NoRiskClient/issues/assets/155762660/07efca42-5e95-4f52-b869-ec60bb8a70f8)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.3.5

**Comment by enricoxD** [comment]
Die Ränder sind in gesamten Launcher vertreten - Ich schätze mal, dass es gewollt ist, dass sie auch dort sind

**Comment by TimLohrer** [comment]
> Die Ränder sind in gesamten Launcher vertreten - Ich schätze mal, dass es gewollt ist, dass sie auch dort sind

Jap, so siehts aus
