### ISSUE TITLE
[FEATURE-REQUEST]: password requirement to enter experimental mode

### ISSUE THREAD

**Issue by polylymer** [NoRiskClient/issues#82]
### Your idea

before you can activate experimental mode in the launcher, you should be forced to enter a password or some kind of code. This prevents anyone from entering experimental mode and reporting bugs or problems that only occur there due to unfinished releases/testing purposes

### Where would this be applied?

Launcher

### What platforms would this affect?

Windows, MacOS, Linux

**Comment by TimLohrer** [comment]
Dafür brauchen wir erst einen endpoint im backend zum verifizieren
