### ISSUE TITLE
[Bug]: Launcher stuck bei "Checking for Updates"

### ISSUE THREAD

**Issue by Tiutus** [NoRiskClient/issues#85]
### What happened?

![image](https://github.com/NoRiskClient/issues/assets/155762660/14fc91ba-c0ca-455d-b244-15931641456a)

Alles mögliche zusammen mit Tim versucht, noch kein einziges mal weitergekommen als das

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows

### Version (for launcher bugs)

0.3.5

**Comment by TimLohrer** [comment]
Hast du die NoriskClientLauncher app Datei in deinem applications Ordner?

**Comment by Tiutus** [comment]
> Hast du die NoriskClientLauncher app Datei in deinem applications Ordner?

nicht das ich wüsste, wo finde ich den bin dumm

**Comment by TimLohrer** [comment]
@copyandexecute ich bin da mit meinem Latein am Ende... Er ist wirklich zwischen 2 Welten verloren oderso 💀

**Comment by Tiutus** [comment]
![image](https://github.com/NoRiskClient/issues/assets/155762660/68f6a01b-fee8-464c-b04b-529e95c88d21)
das richtig so?

**Comment by Tiutus** [comment]
@TimLohrer

**Comment by TimLohrer** [comment]
> @TimLohrer 
> 

Schreibe in 30min... Koche grad

**Comment by Tiutus** [comment]
@TimLohrer was soll ich denn jz machen 😭😭😭bro ich bin halt dumm

**Comment by Tiutus** [comment]
soll ich wen anders fragen

**Comment by TimLohrer** [comment]
> @TimLohrer was soll ich denn jz machen 😭😭😭bro ich bin halt dumm
> 

Ey sorry, habe vergessen zu checken wegen dem ordner... Ich versuche dran zu denken

**Comment by TimLohrer** [comment]
@Tiutus nur so, wir sind drann, aber wissen selber noch nicht wie man das fixt :/

**Comment by TimLohrer** [comment]
duplicate <https://github.com/NoRiskClient/issues/issues/95>

**Comment by TimLohrer** [comment]
nvm is eig. nt unbedingt doppelt

**Comment by copyandexecute** [comment]
Gibts dich noch tititus?

**Comment by Tiutus** [comment]
> Gibts dich noch tititus?

ja?

**Comment by copyandexecute** [comment]
Ach interessant jetzt weiß ich glaube worans lag

**Comment by SleepyPxnda** [comment]
Besteht das Problem noch ?

**Comment by SleepyPxnda** [comment]
Ja ne wenn hier nixmehr kam dann weg damit
