### ISSUE TITLE
smooth zoom

### ISSUE THREAD

**Issue by Katzenbastler** [NoRiskClient/issues#86]
### Your idea

an developer/evtl. designer, würde bei der zoom funktion vorschlagen, das es ne smooth übergang option gibt(nicht beim bewegen, sondern beim anzoomen)

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by enricoxD** [comment]
@Katzenbastler hast du dir das so vorgestellt?

https://github.com/NoRiskClient/issues/assets/71661047/e3dc9a9c-d528-4260-9004-41208fc82456

**Comment by enricoxD** [comment]
@Katzenbastler hast du dir das so vorgestellt?

https://github.com/NoRiskClient/issues/assets/71661047/aff124e5-f325-44bc-9097-6c9d52a6e004

**Comment by Katzenbastler** [comment]
Ja etwa ausser die 180 grad drehung aber die ist glaube ungewollt.
Aber sonst sehr gut so hab ich’s mir vorgestellt . Super!

Von meinem iPhone gesendet

Am 17.02.2024 um 20:47 schrieb Enrico ***@***.***>:

﻿

@Katzenbastler<https://github.com/Katzenbastler> hast du dir das so vorgestellt?

https://github.com/NoRiskClient/issues/assets/71661047/e3dc9a9c-d528-4260-9004-41208fc82456
