### ISSUE TITLE
[Bug]: Screenshot module overrides McReal

### ISSUE THREAD

**Issue by Kolpixx** [NoRiskClient/issues#88]
### What happened?

Wenn man das Screenshot Modul aktiviert hat kann man kein McReal hochladen:

https://github.com/NoRiskClient/issues/assets/68741965/997c9873-3649-4dda-a07c-da3aa570db13

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Not a launcher bug

**Comment by TimLohrer** [comment]
rewrite :/

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/6feff19a-109f-403b-be9b-035d8a321338)
Hab ein Screenshot event zu Fabric-Utils gemoved, man kann jetzt beides machen wenn beide Module an sind 👍 

Hab nur kurz refactored, also man könnte noch mehr funktionalität zum Screenshot Module providen

**Comment by copyandexecute** [comment]
![grafik](https://github.com/NoRiskClient/issues/assets/58366920/41eedf34-d6cd-499f-9cd3-7f5e2851dd2b)
