### ISSUE TITLE
[FEATURE-REQUEST]: Borderless Window

### ISSUE THREAD

**Issue by Greeenman999** [NoRiskClient/issues#89]
### Your idea

Wie die Mod Borderless Mining damit man Fullscreen gut machen kann bei manchen dual monitor setups.

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by SleepyPxnda** [comment]
@enricoxD ist das hier noch in arbeit ?

**Comment by enricoxD** [comment]
@SleepyPxnda nein
