### ISSUE TITLE
[FEATURE-REQUEST]: Vsync

### ISSUE THREAD

**Issue by DoctorDepp** [NoRiskClient/issues#90]
### Your idea

vsync standartmäßig ausmachen, vsync verursacht teilweise einen delay bei der maus. wenn man nicht weiß, dass es an vsync liegt kann das sehr stören 

### Where would this be applied?

Client

### What platforms would this affect?

Not a launcher feature

**Comment by TimLohrer** [comment]
@copyandexecute das hat hohe prio wegen extremen lags bei einigen

**Comment by copyandexecute** [comment]
Hab das schon gecodet lol

**Comment by copyandexecute** [comment]
Duplicate of https://github.com/NoRiskClient/issues/issues/84
