### ISSUE TITLE
[Bug]: Featured mods don't get filtered based on client version

### ISSUE THREAD

**Issue by TomJuri** [NoRiskClient/issues#96]
### What happened?

When using experimental mode and a branch other than `NORISK-DEV` the featured mod `e4mc` will fail to install because it does not support 1.20.4 yet. It works when using `NORISK-DEV` because that branch is still on 1.20.2. Checking if a mod is compatible with the minecraft version of the selected branch and hiding it if that is not the case would fix this issue.
![image](https://github.com/NoRiskClient/issues/assets/99533320/773f8a67-29f2-41c8-a01c-59d04f81e46c)

### Where is this happening?

Launcher

### What platform are you seeing the problem on? (for launcher bugs)

Windows, Linux

### Version (for launcher bugs)

0.3.8

**Comment by TomJuri** [comment]
Stimmt schon, trotzdem kann es aber sein das die MC Version des Clients upgedatet wird, und dadurch manche gefeaturte Mods inkompatibel werden.  Dann wäre es doch besser, die Mods zu verstecken bis die Autoren die Mods upgedatet haben, anstatt dass sie da trotzdem stehen und dann ein User weitere unnötige Bug Reports erstellt. Hat sehr niedrige Priorität, kannst das Issue natürlich aber auch schließen, wenn du es nicht als notwendig empfindest.

**Comment by TimLohrer** [comment]
> Stimmt schon, trotzdem kann es aber sein das die MC Version des Clients upgedatet wird, und dadurch manche gefeaturte Mods inkompatibel werden.  Dann wäre es doch besser, die Mods zu verstecken bis die Autoren die Mods upgedatet haben, anstatt dass sie da trotzdem stehen und dann ein User weitere unnötige Bug Reports erstellt. Hat sehr niedrige Priorität, kannst das Issue natürlich aber auch schließen, wenn du es nicht als notwendig empfindest.

Nene, is schon valid under sollte fixed werden, wollte nur klarstellen, dass das nur bei den featured mods so ist
