### ISSUE TITLE
[Bug]: Freelook bug

### ISSUE THREAD

**Issue by MrMendel** [NoRiskClient/issues#97]
### What happened?

Wenn man nach vorne läuft dann Freelook  (R) drückt, weiterhin (W) gedrückt hält und dann versucht nach Rechts (D) zu laufen , läuft man nur gerade weiter. Bei (A) bewegt man sich allerdings nach links. Bei (S) bleibt man stehen. 

### Where is this happening?

Client

### What platform are you seeing the problem on? (for launcher bugs)

Windows

**Comment by TimLohrer** [comment]
Bug nicht reproduzierbar
